Repository Wikia/app, pull requests merged in 2018-09, with the labels that each got.

#15975 SUS-5531 | Apply cronjobs with each production Kubernetes deployment
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15980 SUS-5683 | update DeadWiki README.md and mention Kubernetes cronjob
  extensions/wikia/WikiFactory/DeadWikis/README.md
Labels: sus, sus-kubernetes

#15984 SUS-5531 | generate YAML file with cron jobs in Jenkins and apply it when making a code deploy
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15985 SUS-5660 | remove wgWikiFactoryRedirectForAlternateDomains
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  includes/wikia/VariablesBase.php
Labels: sus

#15989 SUS-5784 | remove maintenance/wikia/cronjobs/updateCurationCMSTopicRanks.ph
  lib/Swagger/src/CurationCMS/Api/CurationApi.php
  lib/Swagger/src/CurationCMS/Api/FollowApi.php
  lib/Swagger/src/CurationCMS/Api/StoriesApi.php
  lib/Swagger/src/CurationCMS/Api/StoriesFeedApi.php
  lib/Swagger/src/CurationCMS/Api/StoriesThemesApi.php
  lib/Swagger/src/CurationCMS/Api/StoriesTopicsApi.php
  lib/Swagger/src/CurationCMS/Api/TagsApi.php
  lib/Swagger/src/CurationCMS/Api/TopicsApi.php
  lib/Swagger/src/CurationCMS/Api/UrlSummaryApi.php
  lib/Swagger/src/CurationCMS/Models/AddTagsResponse.php
  lib/Swagger/src/CurationCMS/Models/Attribution.php
  lib/Swagger/src/CurationCMS/Models/AuthenticatedUser.php
  lib/Swagger/src/CurationCMS/Models/Chronology.php
  lib/Swagger/src/CurationCMS/Models/EditablePostFields.php
  lib/Swagger/src/CurationCMS/Models/EmbeddedTagResponse.php
  lib/Swagger/src/CurationCMS/Models/FeedResponse.php
  lib/Swagger/src/CurationCMS/Models/Image.php
  lib/Swagger/src/CurationCMS/Models/ImageUploadResponse.php
  lib/Swagger/src/CurationCMS/Models/Instant.php
  lib/Swagger/src/CurationCMS/Models/LocalDateTime.php
  lib/Swagger/src/CurationCMS/Models/PostAddTags.php
  lib/Swagger/src/CurationCMS/Models/PostCreate.php
  lib/Swagger/src/CurationCMS/Models/PostListElementResponse.php
  lib/Swagger/src/CurationCMS/Models/PostListResponse.php
  lib/Swagger/src/CurationCMS/Models/PostResponse.php
  lib/Swagger/src/CurationCMS/Models/PostUpdate.php
  lib/Swagger/src/CurationCMS/Models/StoriesPostResponse.php
  lib/Swagger/src/CurationCMS/Models/StoryStream.php
  lib/Swagger/src/CurationCMS/Models/StoryStreamCreate.php
  lib/Swagger/src/CurationCMS/Models/StoryStreamUpdate.php
  lib/Swagger/src/CurationCMS/Models/Tag.php
  lib/Swagger/src/CurationCMS/Models/TagsResponse.php
  lib/Swagger/src/CurationCMS/Models/Topic.php
  lib/Swagger/src/CurationCMS/Models/TopicCreate.php
  lib/Swagger/src/CurationCMS/Models/TopicListResponse.php
  lib/Swagger/src/CurationCMS/Models/TopicResponse.php
  lib/Swagger/src/CurationCMS/Models/TopicUpdate.php
  lib/Swagger/src/CurationCMS/Models/TopicsResponse.php
  lib/Swagger/src/CurationCMS/Models/UrlSummary.php
  lib/Swagger/src/CurationCMS/Models/UrlSummaryRequest.php
  lib/Swagger/src/CurationCMS/Models/Video.php
  lib/Swagger/src/CurationCMS/settings.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  maintenance/wikia/cronjobs/updateCurationCMSTopicRanks.php
Labels: sus, sus-kubernetes

#15991 SUS-5562 autoscale mediawiki-tasks
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#15990 SUS-5782 | introduce CleanupCityCreationLog maintenance script
  docker/maintenance/cleanup-city-creation-log.yaml
  docker/maintenance/cleanup-phalanx-stats.yaml
  docker/maintenance/send-confirmation-reminder.yaml
  docker/maintenance/send-weekly-digest.yaml
  extensions/wikia/CreateNewWiki/maintenance/cleanupCityCreationLog.php
  maintenance/Maintenance.php
Labels: sus

#15992 SUS-5562 allow sending tasks to k8s
  includes/wikia/DefaultSettings.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
Labels: sus, sus-kubernetes

#15981 SUS-5455
  docker/maintenance/README.md
  docker/maintenance/founder-emails-complete-digest.yaml
  docker/maintenance/founder-emails-days-passed.yaml
  docker/maintenance/founder-emails-views-digest.yaml
  extensions/wikia/FounderEmails/FounderEmailsMaintenance.php
  extensions/wikia/FounderEmails/maintenance.php
Labels: sus, sus-kubernetes

#16000 SUS-5786 | remove hostname entry from wgTransactionContext
  includes/wikia/transaction/Transaction.php
Labels: sus, sus-kubernetes

#16001 SUS-5785 | introduce an API for checking GDPR process status for a given user
  extensions/wikia/Privacy/RemoveUserDataController.php
Labels: sus, sus-gdpr

#16002 Enable FounderEmails while in CLI mode
  docker/maintenance/founder-emails-complete-digest.yaml
  docker/maintenance/founder-emails-days-passed.yaml
  docker/maintenance/founder-emails-views-digest.yaml
Labels: sus, sus-kubernetes

#16003 Merge pull request #16002 from Wikia/release-727-SUS-5455
  docker/maintenance/founder-emails-complete-digest.yaml
  docker/maintenance/founder-emails-days-passed.yaml
  docker/maintenance/founder-emails-views-digest.yaml
Labels: sus, sus-kubernetes

#15997 SUS-5678 deploy to sjc and res k8s clusters
  docker/prod/Jenkinsfile
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16005 SUS-5790 | FancyCaptcha - store captcha images on S3
  extensions/wikia/Captcha/Module/FancyCaptcha.class.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-kubernetes

#16019 add missing label to mediawiki-tasks to collect metrics
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16027 SUS-5807 | DumpsOnDemandTask - generate 7z dumps directly in /tmp directory (without entering subdirectories)
  extensions/wikia/WikiFactory/Close/maintenance.php
  extensions/wikia/WikiFactory/Dumps/runBackups.php
  lib/Wikia/src/Tasks/Tasks/DumpsOnDemandTask.php
Labels: sus, sus-kubernetes

#16008 SUS-5789 add rewrite for lyrics api
  docker/dev/site.conf
  docker/prod/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#16033 SUS-5813 | dumps queue monitoring improved
  extensions/wikia/WikiFactory/Dumps/README.md
Labels: sus

#16034 SUS-5799 | OOM errors - let's start with limits taken from production end-user facing MediaWiki template
  docker/maintenance/cronjob-template.yaml
Labels: sus, sus-kubernetes

#16038 SUS-5807 | DumpsOnDemandTask require 7za binary
  docker/README.md
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#16039 SUS-5813 | dumps queue - update README
  extensions/wikia/WikiFactory/Dumps/README.md
Labels: sus

#16046 SUS-8522 | handle /apple-touch-icon.png requests
  docker/dev/docker-compose.yml
  docker/prod/Dockerfile-nginx
  docker/sandbox/Dockerfile-nginx
Labels: sus, sus-kubernetes

#16047 nginx: rewrite /proxy.php requests on sandbox to handle Celery tasks properly
  docker/prod/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#16055 SUS-5825 | make nginx and Apache works similar when handling request paths
  LocalSettings.php
Labels: sus, sus-kubernetes

#16042 SUS-5798 SUS-5824 | nginx -handle alternative article paths: /wiki/index.php and /w
  docker/dev/site.conf
  docker/prod/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#16059 SUS-5792 | rewrite for legacy corporate pages with short article path
  docker/dev/site.conf
  docker/prod/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#16057 SUS-5819 | separate fastcgi_read_timeout for mediawiki-tasks
  docker/prod/Dockerfile-nginx
  docker/prod/prod.template.yaml
  docker/prod/site.conf.template
Labels: sus, sus-kubernetes

#16062 SUS-5829 | Improve crontabs scheduling
  docker/maintenance/cleanup-upload-stash.yaml
  docker/maintenance/update-special-pages.yaml
Labels: sus, sus-kubernetes

#16064 SUS-5839 new autoscaler config from mediawiki-tasks
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16065 SUS-5820 bump php memory limit for mediawiki-tasks
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16066 SRE-101 | don't return hardcoded 503 for api.php/wikia.php when read-only, for real this time
  includes/WebStart.php
Labels: SRE

#16067 SUS-5838 | nginx+fpm - preserve query string when redirect-canonical.php performs a redirect
  redirect-canonical.php
Labels: sus, sus-kubernetes

#16048 SRE | Active active phase two merge
  extensions/wikia/Chat2/ChatConfig.class.php
  extensions/wikia/Chat2/ChatController.class.php
  extensions/wikia/Chat2/tests/ChatConfigTest.php
  extensions/wikia/CreateNewWiki/classes/Starters.class.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: SRE

#16072 make trailing slash optional in language wiki root paths
  docker/dev/site.conf
  docker/prod/site.conf.template
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#16074 SUS-5842 | rewrite URLs that point to not existing PHP files
  docker/dev/site.conf
  docker/prod/site.conf.template
  docker/sandbox/site.conf
  extensions/3rdparty/LyricWiki/server.php
  server.php
  wikia-robots-txt.php
Labels: sus, sus-kubernetes

#15740 SUS-5530 | Add version check on deploy
  docker/prod/Jenkinsfile
  docker/sandbox/Jenkinsfile
  docker/sandbox/sandbox.template.yaml
Labels: Work in progress, sus, sus-kubernetes

#16051 SUS-5826 | prevent concurent cronjobs
  docker/maintenance/README.md
  docker/maintenance/cronjobs-generator.sh
  docker/maintenance/examples/example-founder-emails-complete-digest.yaml
  docker/maintenance/examples/example-founder-emails-days-passed.yaml
  docker/maintenance/examples/example-founder-emails-views-digest.yaml
  docker/maintenance/examples/example-maintenance-cronjob.yaml
  docker/maintenance/examples/example-one-time-job.yaml
  docs/maintenance.txt
  extensions/wikia/FounderEmails/FounderEmailsMaintenance.php
  includes/wikia/DefaultSettings.php
  maintenance/Maintenance.php
  maintenance/doMaintenance.php
  maintenance/utils/Status.php
Labels: sus, sus-kubernetes

#16075 Restore FounderEmails cronjobs
  docker/maintenance/founder-emails-complete-digest.yaml
  docker/maintenance/founder-emails-days-passed.yaml
  docker/maintenance/founder-emails-views-digest.yaml
Labels: sus, sus-kubernetes

#16079 SUS-5840 add var to control task flow globally
  includes/wikia/DefaultSettings.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
Labels: sus, sus-kubernetes

#16073 SUS-5841 use correct proxy for parsoid purges
  lib/Wikia/src/Tasks/Tasks/ParsoidCacheUpdateTask.php
Labels: sus, sus-kubernetes

#16093 SUS-5840 use correct wikifactory method
  lib/Wikia/src/Tasks/AsyncTaskList.php
Labels: sus, sus-kubernetes

#16096 SRE-105 | Avoid useless "USE ... " queries in MediaWiki
  includes/db/DatabaseMysqli.php
Labels: SRE, active-active

#16101 increase memory limit for mediawiki-tasks
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16094 SUS-5853 | make sandbox descriptor and job more generic
  docker/sandbox/Dockerfile-php.template
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#16100 SUS-5854 | add -k8s suffix to sandbox name if needed
  docker/sandbox/Jenkinsfile
  docker/sandbox/README.md
Labels: sus, sus-kubernetes

#16110 Disable adding '-k8s' suffix to sandboxes
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#16103 SUS-5857 | Sunset Special:Tasks - broken and rarely used
  extensions/wikia/Tasks/README.md
  extensions/wikia/Tasks/Tasks.i18n.php
  extensions/wikia/Tasks/Tasks.setup.php
  extensions/wikia/Tasks/TasksModel.class.php
  extensions/wikia/Tasks/TasksSpecialController.class.php
  extensions/wikia/Tasks/css/special_tasks.css
  extensions/wikia/Tasks/images/ajax-loader.gif
  extensions/wikia/Tasks/js/special_tasks.js
  extensions/wikia/Tasks/templates/TasksSpecial_index.php
  extensions/wikia/Tasks/templates/TasksSpecial_log.php
  includes/wikia/DefaultSettings.php
  includes/wikia/VariablesExpansions.php
Labels: sus, sus-sunsets-2018

#16114 Revert "Merge pull request #16084 from Wikia/SUS-5816"
  extensions/wikia/Tasks/proxy/proxy.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  includes/api/ApiMain.php
  includes/wikia/Wikia.php
  lib/Wikia/src/Tasks/TaskRunner.php
  maintenance/wikia/task_runner.php
  wikia-robots-txt.php
Labels: sus

#16117 SUS-5855 | TaskRunner - send metrics to Prometheus via Pushgateway
  lib/Wikia/src/Metrics/Collector.php
  lib/Wikia/src/Tasks/TaskRunner.php
Labels: sus, sus-kubernetes

#16115 SUS-5816 | set mServerName and langCode when X-Mw-Wiki-Id is passed with a request
  api.php
  extensions/wikia/Tasks/proxy/proxy.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/WikiFactory.php
  includes/DeferredUpdates.php
  includes/Wiki.php
  includes/wikia/nirvana/WikiaApp.class.php
  wikia.php
Labels: sus

#16109 SRE | in proxy.php perform normal MW shutdown procedure
  api.php
  extensions/wikia/Tasks/proxy/proxy.php
  includes/DeferredUpdates.php
  includes/Wiki.php
  includes/wikia/nirvana/WikiaApp.class.php
  wikia.php
Labels: SRE, active-active

#16105 SRE-106 | Don't fetch pending SiteStatsUpdate deltas if 0 <= $wgSiteStatsAsyncFactor <= 1
  includes/SiteStatsUpdate.php
Labels: SRE, active-active

#16086 SRE-103 | Optimize MW Rabbit resources usage
  .travis.yml
  extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobBase.php
  includes/Title.php
  includes/wikia/VariablesBase.php
  includes/wikia/VariablesExpansions.php
  includes/wikia/rabbitmq/ConnectionBase.class.php
  includes/wikia/rabbitmq/tests/RabbitConnectionBaseTest.php
  lib/Wikia/src/Factory/RabbitFactory.php
  lib/Wikia/src/Factory/ServiceFactory.php
  lib/Wikia/src/Rabbit/ConnectionManager.php
  lib/Wikia/src/Rabbit/DefaultTaskPublisher.php
  lib/Wikia/src/Rabbit/NullTaskPublisher.php
  lib/Wikia/src/Rabbit/TaskPublisher.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
  lib/Wikia/src/Tasks/DeferredTaskQueueUpdate.php
  lib/Wikia/src/Tasks/Queues/Queue.php
  lib/Wikia/src/Tasks/Tasks/BaseTask.php
  lib/Wikia/tests/Factory/RabbitFactoryTest.php
  lib/Wikia/tests/Rabbit/DefaultTaskPublisherIntegrationTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  tests/run-test.php
Labels: SRE, Work in progress, active-active

#16120 CAKE-2151 - FC CNW opt in prompt/modal
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/css/CommunityBuilderOptIn.scss
  extensions/wikia/CreateNewWiki/js/CommunityBuilderOptIn.js
  extensions/wikia/CreateNewWiki/js/WikiBuilder.js
  extensions/wikia/CreateNewWiki/templates/CreateNewWiki_CommunityBuilderModal.php
  extensions/wikia/CreateNewWiki/templates/CreateNewWiki_CommunityBuilderOptInPrompt.php
  extensions/wikia/CreateNewWiki/templates/CreateNewWiki_Index.php
  includes/wikia/VariablesBase.php
Labels: Don't merge
