Repository Wikia/app, pull requests merged in 2018-04, with the labels that each got.

#15100 SUS-4297 | add video_id index on video_info per-wiki tables
  includes/wikia/WikiaUpdater.php
  maintenance/archives/wikia/patch-index-video_info.sql
Labels: sus

#15108 Revert "SUS-4139: tweak - hide test mode button when needed"
  extensions/wikia/ContentReview/controllers/JSPagesSpecialController.class.php
  extensions/wikia/ContentReview/controllers/templates/ContentReviewModule.mustache
  extensions/wikia/ContentReview/controllers/templates/JSPagesSpecialController_index.php
  skins/oasis/modules/ContentReviewModuleController.class.php
Labels: sus

#15104 SUS-4506 | File page with video not handling t URL param
  extensions/wikia/FilePage/WikiaFilePage.php
  extensions/wikia/VideoHandlers/filerepo/WikiaLocalFile.class.php
Labels: sus

#15105 SUS-4512 | Dockerfile for MediaWiki PHP app container
  Docker.md
  Dockerfile
  extensions/wikia/AdEngine/tests/AdEngine2ContextServiceTest.php
  extensions/wikia/AssetsManager/tests/AssetsManagerSassBuilderTest.php
  extensions/wikia/ImageServing/tests/ImageServingCroppingTest.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  includes/wikia/services/tests/DiffEngineTest.php
  includes/wikia/services/tests/MustacheServiceTest.php
  includes/wikia/tests/core/WikiaDatabaseTest.php
  tests/run-test.php
Labels: sus, sus-kubernetes

#15095 SUS-3030 | Don't disable Forums when creating new wiki
  extensions/wikia/CreateNewWiki/tasks/EnableDiscussionsTask.php
  extensions/wikia/Forum/Forum.setup.php
  extensions/wikia/Wall/Wall.setup.php
Labels: sus

#15126 SUS-4181 | WikiFactoryLoader - read from the database when there was a real cache miss
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
Labels: sus

#15132 SUS-4297 | patch video_info table
  includes/wikia/WikiaUpdater.php
  maintenance/archives/wikia/patch-video_info_id.sql
  maintenance/archives/wikia/patch-video_info_provider.sql
Labels: sus

#15133 SUS-1805 | collect WikiaExternalImageList usage statistics
  extensions/wikia/WikiaWhiteList/WikiaExternalImageList.php
Labels: sus, sus-sunsets-2018

#15135 SUS-4297 | video_info: drop no longer used added_at index
  extensions/wikia/VideoHandlers/sql/video_info.sql
  includes/wikia/WikiaUpdater.php
  maintenance/archives/wikia/patch-video_info-drop-added_at_idx.sql
Labels: sus

#15137 SUS-4514 | Sunset ProfilerTideways and ProfilerSimpleDataCollector profiler classes
  StartProfiler.php
  includes/profiler/Profiler.php
  includes/profiler/ProfilerData.php
  includes/profiler/ProfilerSimpleDataCollector.php
  includes/profiler/ProfilerTideways.php
  includes/profiler/sinks/ProfilerDataSink.php
  includes/wikia/DefaultSettings.php
Labels: sus, sus-kubernetes, sus-sunsets-2018

#14805 PLATFORM-3369: send beacon errors to event-logger
  extensions/wikia/DesignSystem/DesignSystem.setup.php
  extensions/wikia/Discussions/Discussions.setup.php
  extensions/wikia/Track/Track.php
  extensions/wikia/Track/templates/track.mustache
  includes/wikia/Wikia.php
  lib/Wikia/src/Service/Gateway/KubernetesExternalUrlProvider.php
  lib/Wikia/tests/Service/Gateway/KubernetesExternalUrlProviderTest.php
Labels: Don't merge

#15139 SUS-4547 | introduce LogEventsList::NO_EDIT_COUNT_CHECK flag that will make edit count to not be checked
  includes/logging/LogEventsList.php
  includes/logging/LogFormatter.php
  includes/specials/SpecialLog.php
Labels: sus

#15141 SUS-4547 | do you really want to call UserStatsService and do nothing? :)
  extensions/wikia/Wall/WallBaseController.class.php
  includes/wikia/services/UserStatsService.class.php
Labels: sus

#15147 SUS-4547 | UserStatsService - properly handle cases when local edit count is zero
  includes/wikia/services/UserStatsService.class.php
Labels: sus

#15120 SUS-4512 | split base and dev Docker image
  Docker.md
  docker/README.md
  docker/base/Dockerfile
  docker/dev/Dockerfile
Labels: sus, sus-kubernetes

#15156 SUS-4525 | remove ImageMagick-related code from BitmapHandler class
  includes/DefaultSettings.php
  includes/media/Bitmap.php
Labels: sus, sus-sunsets-2018

#15161 SUS-4580 | add ploticus binary to base Docker image
  docker/base/Dockerfile
Labels: sus, sus-kubernetes

#15163 SUS-4536 | CloseWikiMaintenance - use list_objects_recursively and delete objects one by one
  extensions/SwiftCloudFiles/php-cloudfiles-1.7.10/cloudfiles.php
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus, sus-kubernetes

#15167 SUS-4538 | remove no longer used S3Command class
  includes/wikia/S3Command.class.php
Labels: sus, sus-sunsets-2018

#15168 SUS-4537 | Use SwiftStorage / CF_Container to fetch all images from a given bucket
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus, sus-kubernetes

#15166 SUS-4549: Generate article snippets inside MW
  extensions/wikia/ArticleSnippets/ArticleSnippets.php
  extensions/wikia/ArticleSnippets/SnippetParser.php
  extensions/wikia/ArticleSnippets/tests/SnippetParserTest.php
  extensions/wikia/ArticleSnippets/tests/resources/ArticleWithPortableInfobox.html
  extensions/wikia/ArticleSnippets/tests/resources/BracketsFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/CorrectFontFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/DDFirstFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/DisplayNoneFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/EmptyListAfterPTagFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/FigureFirstFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/FontTagFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/ImageFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/InfoboxOnlyFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/ListsOnlyFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/MainPageArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/ManyPortableInfoboxesOnly.html
  extensions/wikia/ArticleSnippets/tests/resources/NonObjectFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/NotSupportedMarkupOnlyFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/OnlyPortableInfoboxStackedLayout.html
  extensions/wikia/ArticleSnippets/tests/resources/PortableInfoboxOnly.html
  extensions/wikia/ArticleSnippets/tests/resources/PortableInfoboxWithSmartGroups.html
  extensions/wikia/ArticleSnippets/tests/resources/PortableInfoboxWithoutTitleOnly.html
  extensions/wikia/ArticleSnippets/tests/resources/RedlinkToTemplateArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/RegularFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/TablesOnlyFullArticle.html
  extensions/wikia/ArticleSnippets/tests/resources/TextInFontTagsFullArticle.html
  includes/wikia/DefaultSettings.php
  includes/wikia/Extensions.php
  includes/wikia/services/ArticleService.class.php
  includes/wikia/services/tests/ArticleServiceTest.php
Labels: sus

#15172 SUS-4538 | DumpsOnDemand::putToAmazonS3 now uses S3 PHP client instead of s3cmd binary
  composer.json
  composer.lock
  extensions/wikia/WikiFactory/Close/maintenance.php
  extensions/wikia/WikiFactory/Dumps/DumpsOnDemand.php
  extensions/wikia/WikiFactory/Dumps/runBackups.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/installed.json
  lib/composer/tpyo/amazon-s3-php-class/.gitignore
  lib/composer/tpyo/amazon-s3-php-class/README.md
  lib/composer/tpyo/amazon-s3-php-class/S3.php
  lib/composer/tpyo/amazon-s3-php-class/composer.json
  lib/composer/tpyo/amazon-s3-php-class/example-cloudfront.php
  lib/composer/tpyo/amazon-s3-php-class/example-form.php
  lib/composer/tpyo/amazon-s3-php-class/example-wrapper.php
  lib/composer/tpyo/amazon-s3-php-class/example.php
Labels: sus, sus-kubernetes

#15190 in Special:Version remove useless data
  extensions/wikia/SpecialVersion/WikiaSpecialVersion.class.php
Labels: sus, sus-sunsets-2018

#15200 SUS-4606 | catch exceptions instead of stopping the CloseWiki script
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus

#15201 maintenance/rebuildLocalisationCache.orig.php is no longer needed
  maintenance/rebuildLocalisationCache.orig.php
Labels: sus, sus-sunsets-2018

#15164 SUS-4573 | Run MediaWiki in Docker locally
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/dev/README.md
  docker/dev/docker-compose.yml
  docker/dev/k8s/Dockerfile-nginx
  docker/dev/k8s/Dockerfile-php
  docker/dev/k8s/README.md
  docker/dev/k8s/poz-dev.yaml
  docker/dev/k8s/site.conf
  docker/dev/k8s/sjc-dev.yaml
  docker/dev/site.conf
  docker/dev/xdebug.ini
  extensions/wikia/UserLogin/UserLogin.setup.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  includes/LocalisationCache.php
  lib/Wikia/src/Localisation/CachedLCStoreDB.php
  lib/Wikia/src/Localisation/LCStoreDB.php
  lib/Wikia/tests/Localisation/CachedLCStoreDBTest.php
  lib/Wikia/tests/Localisation/LCStoreDBIntegrationTest.php
  lib/Wikia/tests/Localisation/fixtures/lc_store.yaml
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  tests/fixtures/wikicities.sql
Labels: sus, sus-kubernetes

#15174 XW-4819 | ABTest of Right Rail recirculation source
  extensions/wikia/Recirculation/Recirculation.setup.php
  extensions/wikia/Recirculation/RecirculationApiController.class.php
  extensions/wikia/Recirculation/js/recirculation.js
  extensions/wikia/Recirculation/services/CurationCMSService.class.php
Labels: Don't merge

#15215 SUS-4604 | make in repo static assets work in docker
  docker/dev/docker-compose.yml
  docker/dev/k8s/site.conf
  docker/dev/site.conf
Labels: sus, sus-kubernetes

#15229 SUS | validate parser cache content type
  includes/parser/ParserCache.php
Labels: sus, sus-kubernetes

#15230 SUS-4611 | install memcached PHP extension from PECL
  docker/base/Dockerfile
Labels: sus, sus-kubernetes

#15231 fix __cb urls on k8s
  docker/dev/docker-compose.yml
  docker/dev/k8s/Dockerfile-nginx
  docker/dev/k8s/poz-dev.yaml
  docker/dev/k8s/site.conf
  docker/dev/k8s/sjc-dev.yaml
Labels: sus, sus-kubernetes

#15232 SUS-4608 | direct nginx access logs to stdout as JSON
  docker/dev/k8s/nginx.conf
Labels: sus, sus-kubernetes

#15223 SUS-4614 | get rid of wgEnableMemcachedBulkMode (disabled in June 2013)
  extensions/wikia/WallNotifications/WallNotifications.class.php
  extensions/wikia/WikiFactory/WikiFactory.php
  includes/objectcache/BagOStuff.php
  includes/objectcache/MemcachedPhpBagOStuff.php
  includes/wikia/DefaultSettings.php
Labels: sus, sus-sunsets-2018

#15233 fix log format
  docker/dev/k8s/nginx.conf
Labels: sus, sus-kubernetes

#15238 SUS-4734 | make closeWiki.php script generic
  maintenance/wikia/closeWiki.php
Labels: sus

#15241 SUS-4508 | address PHP 7.2 deprecations in core code
  includes/GlobalFunctions.php
  includes/MagicWord.php
  includes/Pager.php
  includes/api/ApiQueryBase.php
  includes/db/Database.php
  includes/media/Exif.php
  includes/specials/SpecialUserrights.php
Labels: sus, sus-php7.2

#15243 SUS-4493 | populateEventsLocalUsers - process members of local groups as well
  extensions/wikia/Listusers/SpecialListusers_helper.php
Labels: sus

#15226 SUS-4611 | backport MemcachedPeclBagOStuff from MW 1.20
  extensions/wikia/VideoEmbedTool/VideoEmbedTool_body.php
  extensions/wikia/VideoEmbedTool/VideoEmbedTool_setup.php
  extensions/wikia/VideoHandlers/VideoFileUploader.class.php
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/DailymotionApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/VimeoApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/YoukuApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/YoutubeApiWrapper.class.php
  includes/AutoLoader.php
  includes/DefaultSettings.php
  includes/cache/wikia/LibmemcachedBagOStuff.php
  includes/objectcache/MemcachedBagOStuff.php
  includes/objectcache/MemcachedClient.php
  includes/objectcache/MemcachedPeclBagOStuff.php
  includes/objectcache/MemcachedPhpBagOStuff.php
  includes/objectcache/ObjectCache.php
  includes/wikia/DefaultSettings.php
  includes/wikia/GlobalFunctions.php
  includes/wikia/libmemcached-client.php
  includes/wikia/memcached/MemcachedStats.class.php
  includes/wikia/tests/MemcachedStatsTest.php
Labels: sus, sus-kubernetes, sus-sunsets-2018

#15169 PLATFORM-3430: remove wgServer from WikiFactory
  LocalSettings.php
  extensions/wikia/CuratedContent/CuratedContentModel.class.php
  extensions/wikia/CuratedContent/tests/CuratedContentHooksTest.php
  extensions/wikia/EditPreview/js/editpage.event.preview.js
  extensions/wikia/FilePage/FilePageHooks.class.php
  extensions/wikia/GameGuides/GameGuidesModel.class.php
  extensions/wikia/InterwikiDispatcher/SpecialInterwikiDispatcher_body.php
  extensions/wikia/InterwikiDispatcher/tests/InterwikiDispatcherTest.php
  extensions/wikia/PhalanxII/PhalanxStatsSpecialController.class.php
  extensions/wikia/Recirculation/services/DiscussionsDataService.class.php
  extensions/wikia/SharedHelp/SharedHelp.php
  extensions/wikia/SpecialInterwikiEdit/SpecialInterwikiEdit.php
  extensions/wikia/WikiFactory/Close/SpecialCloseWiki_body.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_ajax.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/templates/form-domains.tmpl.php
  extensions/wikia/WikiFactory/tests/WikiFactoryTest.php
  includes/wikia/DefaultSettings.php
  includes/wikia/GlobalTitle.php
  includes/wikia/Wikia.php
  includes/wikia/models/DesignSystemGlobalNavigationModel.class.php
  includes/wikia/services/ApiService.class.php
  includes/wikia/services/DataMartService.class.php
  includes/wikia/services/WikiService.class.php
  includes/wikia/services/tests/ApiServiceTest.php
  lib/Wikia/src/Tasks/Tasks/ImageReviewTask.php
  lib/Wikia/src/Tasks/Tasks/MultiTask.php
Labels: Don't merge

#15248 SUS-4735 test sandbox configuration
  docker/sandbox/Dockerfile-nginx
  docker/sandbox/Dockerfile-php
  docker/sandbox/nginx.conf
  docker/sandbox/site.conf
  docker/sandbox/sjc.yaml
Labels: sus, sus-kubernetes
