Repository Wikia/app, pull requests merged in 2018-12, with the labels that each got.

#16430 SRE-109 | Update site stats via a background task
  includes/WikiPage.php
  includes/filerepo/file/LocalFile.php
  lib/Wikia/src/Factory/ProducerFactory.php
  lib/Wikia/src/Factory/ServiceFactory.php
  lib/Wikia/src/Tasks/Producer/SiteStatsUpdateTaskProducer.php
  lib/Wikia/src/Tasks/Tasks/SiteStatsUpdateTask.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: SRE, active-active

#16421 SRE-109 | Increment users' edit counts via a background task
  includes/User.php
  lib/Wikia/src/Factory/ProducerFactory.php
  lib/Wikia/src/Tasks/Producer/EditCountTaskProducer.php
  lib/Wikia/src/Tasks/Tasks/IncrementEditCountTask.php
  lib/Wikia/tests/Tasks/Producer/EditCountTaskProducerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: SRE, active-active

#15710 MAIN-13170 & MAIN-16870 | Fix links in S:Nonportableinfoboxes and S:Insights
  extensions/wikia/InsightsV2/models/InsightsQueryPageModel.php
  extensions/wikia/InsightsV2/models/InsightsUnconvertedInfoboxesModel.php
  extensions/wikia/InsightsV2/specials/UnconvertedInfoboxesPage.class.php
Labels: core-team

#16470 CORE-20 | Create an API that exposes templates parameters and articles categories
  includes/parser/Preprocessor_DOM.php
  includes/wikia/DefaultSettings.php
  includes/wikia/api/TemplatesApiController.class.php
Labels: core-team

#16359 Add deploy pipeline documentation
  docker/README.md
Labels: stale, sus, sus-kubernetes

#16483 (PLATFORM-3874) Add support for creating lang path wikis on fandom.com
  extensions/wikia/CreateNewWiki/CreateNewWiki.i18n.php
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/CreateNewWikiHooks.php
  extensions/wikia/CreateNewWiki/CreateWikiChecks.php
  extensions/wikia/CreateNewWiki/js/WikiBuilder.js
  extensions/wikia/CreateNewWiki/tasks/PrepareDomain.php
  extensions/wikia/CreateNewWiki/tasks/TaskContext.php
  extensions/wikia/CreateNewWiki/templates/CreateNewWiki_Index.php
  extensions/wikia/CreateNewWiki/tests/CreateWikiChecksTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/PrepareDomainTest.php
  includes/wikia/VariablesBase.php
Labels: Don't merge

#16501 Prometheus alerting: s/sus/core/g
  docker/prod/alerting.yaml
Labels: core-team

#16493 CORE-6 | Not all pages using Portable Infoboxes have right page props
  extensions/wikia/PortableInfobox/PortableInfoboxHooks.class.php
  extensions/wikia/PortableInfobox/services/PortableInfoboxDataService.class.php
  extensions/wikia/PortableInfobox/tests/PortableInfoboxDataServiceTest.php
Labels: Work in progress, core-team
