Repository Wikia/app, pull requests merged in 2018-08, with the labels that each got.

#15840 SUS-5694 | Use the target namespace instead of the source namespace
  extensions/wikia/Search/classes/IndexService/Evaluation.php
Labels: sus, sus-search-evaluation

#15842 SUS-4531 | Allow to set empty array value in WikiFactory
  extensions/wikia/WikiFactory/WikiFactoryVariableParser.php
  extensions/wikia/WikiFactory/tests/WikiFactoryVariableParserTest.php
Labels: sus

#15796 SRE-97 | Save user's attributes in bulk
  lib/Swagger/src/ApiClient.php
  lib/Swagger/src/ApiException.php
  lib/Swagger/src/Configuration.php
  lib/Swagger/src/ObjectSerializer.php
  lib/Swagger/src/User/Attributes/Api/AttributesApi.php
  lib/Swagger/src/User/Attributes/Api/UsersAttributesApi.php
  lib/Swagger/src/User/Attributes/Api/UsersAttributesInternalApiApi.php
  lib/Swagger/src/User/Attributes/Models/AllAttributesHalResponse.php
  lib/Swagger/src/User/Attributes/Models/AllUserAttributesHalResponse.php
  lib/Swagger/src/User/Attributes/Models/AttributeHalResponse.php
  lib/Swagger/src/User/Attributes/Models/Attributes.php
  lib/Swagger/src/User/Attributes/Models/HalLink.php
  lib/Swagger/src/User/Attributes/Models/Link.php
  lib/Swagger/src/User/Attributes/Models/UserAttributeHalResponse.php
  lib/Swagger/src/User/Attributes/Models/UserAttributes.php
  lib/Swagger/src/User/Attributes/Models/UsersWithAttributes.php
  lib/Wikia/src/Persistence/User/Attributes/AttributePersistence.php
  lib/Wikia/src/Service/User/Attributes/AttributeService.php
  lib/Wikia/src/Service/User/Attributes/UserAttributes.php
  lib/Wikia/tests/Persistence/User/AttributePersistenceTest.php
  lib/Wikia/tests/Service/User/AttributeKeyValueTest.php
  lib/Wikia/tests/Service/User/UserAttributesIntegrationTest.php
  lib/Wikia/tests/Service/User/UserAttributesTest.php
  lib/Wikia/tests/Service/User/fixtures/sample_attributes.json
Labels: active-active

#15844 SUS-5666 | Add a field with a list of redirects to the given page
  extensions/wikia/Search/classes/IndexService/Evaluation.php
Labels: sus, sus-search-evaluation

#15848 SUS-223 | Only save Forum topics relations if edit succeeded
  extensions/wikia/Wall/WallMessage.class.php
Labels: sus

#15834 SRE-62 | Remove dev env specific timeout from TemplateClassificationService
  includes/wikia/services/TemplateClassificationService.class.php
Labels: active-active

#15884 SUS-5723 + SUS-5668
  extensions/wikia/Search/classes/IndexService/AbstractService.php
  extensions/wikia/Search/classes/IndexService/Evaluation.php
  extensions/wikia/Search/classes/MediaWikiService.php
Labels: sus, sus-search

#15893 SUS-5668 - use html field for parser output
  extensions/wikia/Search/classes/IndexService/Evaluation.php
Labels: sus, sus-search

#15897 PLATFORM-3615: Make the sitemap available at the previous domain
  extensions/wikia/SitemapXml/SitemapHooks.class.php
  extensions/wikia/SitemapXml/SitemapXml.setup.php
  extensions/wikia/SitemapXml/tests/SitemapHooksTest.php
  includes/OutputPage.php
Labels: Don't merge, Work in progress

#15945 PLATFORM-3647: don't execute finishcreate on a wiki
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/CreateNewWiki_setup.php
  extensions/wikia/CreateNewWiki/CreateWikiTask.php
  extensions/wikia/CreateNewWiki/FinishCreateMigrateToFandom_setup.php
  extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php
  extensions/wikia/CreateNewWiki/FinishCreateWiki_setup.php
  extensions/wikia/CreateNewWiki/SpecialFinishCreate.class.php
  extensions/wikia/CreateNewWiki/js/WikiBuilder.js
  extensions/wikia/CreateNewWiki/maintenance/setMainPageContent.php
  extensions/wikia/CreateNewWiki/tasks/ConfigureWikiFactory.php
  extensions/wikia/CreateNewWiki/tasks/SetMainPageContent.php
  extensions/wikia/CreateNewWiki/tasks/SetupWikiCities.php
  extensions/wikia/CreateNewWiki/tasks/TaskContext.php
  extensions/wikia/CreateNewWiki/tasks/TaskRunner.php
  extensions/wikia/CreateNewWiki/tests/tasks/ConfigureWikiFactoryTest.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
Labels: Work in progress

#15954 SUS-5475 | add some logs and code cleanup in extensions/wikia/WallNotifications/maintenance.php
  extensions/wikia/WallNotifications/WallNotificationsEveryone.class.php
  extensions/wikia/WallNotifications/maintenance.php
Labels: sus, sus-kubernetes

#15958 SUS-5475 | add YAML descriptor for extensions/wikia/WallNotifications/maintenance/cleanupNotificationsQueue.php script
  docker/maintenance/README.md
  docker/maintenance/cleanup-notifications-queue.yaml
  extensions/wikia/WallNotifications/WallNotificationsEveryone.class.php
  extensions/wikia/WallNotifications/maintenance/cleanupNotificationsQueue.php
Labels: sus, sus-kubernetes

#15960 SUS-5510 | mark test wikis to be closed once a day
  docker/maintenance/remove-qa-wikis.yaml
Labels: sus, sus-kubernetes

#15961 SUS-5505 | cleanupWikiaSharedTalk.php - use WikiaLogger instead of echo
  extensions/wikia/WikiaNewtalk/maintenance/cleanupWikiaSharedTalk.php
Labels: sus, sus-kubernetes

#15962 SUS-5504 | simplify CleanUpWallNotifications logs
  docker/maintenance/cleanup-wall-notifications.yaml
  extensions/wikia/WallNotifications/maintenance/cleanupWallNotifications.php
  maintenance/Maintenance.php
Labels: sus, sus-kubernetes

#15963 SUS-5502 | MigratePhalanxUserBlocks - prevent an exception by checking whether the list of IDs is empty
  docker/maintenance/phalanx-migrate-user-blocks.yaml
  extensions/wikia/PhalanxII/maintenance/MigratePhalanxUserBlocks.php
Labels: sus, sus-kubernetes

#15968 SUS-5777 | improve logging in ContentReviewStatus and add YAML cronjob definition
  docker/maintenance/README.md
  docker/maintenance/publish-content-review-status.yaml
  extensions/wikia/ContentReview/maintenance/publishContentReviewStatus.php
Labels: sus, sus-kubernetes

#15969 SUS-5778 | add send-weekly-digest.yaml
  docker/maintenance/README.md
  docker/maintenance/send-weekly-digest.yaml
Labels: sus, sus-kubernetes
