Repository Wikia/app, pull requests merged in 2018-10, with the labels that each got.

#16129 SRE | fix rabbit hole in tests
  tests/bootstrap.php
  tests/phpunit.xml
  tests/run-test.php
Labels: SRE

#16127 SUS-5862 | set a flag to put MediaWiki database access layer in auto-commit mode
  extensions/wikia/Tasks/proxy/proxy.php
Labels: sus

#16133 SUS-5862 | set a flag to put MediaWiki database access layer in auto-commit mode [preview]
  extensions/wikia/Tasks/proxy/proxy.php
Labels: sus

#16140 SUS-5847: catch all Exceptions and Errors in proxy.php
  extensions/wikia/Tasks/proxy/proxy.php
Labels: sus

#16141 Disable opcache on dev
  docker/dev/Dockerfile
Labels: sus, sus-kubernetes

#16145 SRE | Log which PoolCounter keys fail
  includes/PoolCounter.php
Labels: SRE

#16155 SUS-5889 | proxy.php - clean all output before we emit a JSON response
  extensions/wikia/Tasks/proxy/proxy.php
Labels: sus

#16081 SRE-91 | Eliminate temporary files from avatar upload process
  extensions/wikia/UserProfilePageV3/ImageOperationsHelper.class.php
  extensions/wikia/UserProfilePageV3/Masthead.class.php
  extensions/wikia/UserProfilePageV3/UserProfilePage.setup.php
  extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php
  extensions/wikia/UserProfilePageV3/UserProfilePageHooks.class.php
  extensions/wikia/UserProfilePageV3/api/UserAvatarsService.class.php
  extensions/wikia/UserProfilePageV3/css/UserProfilePage_modal.scss
  extensions/wikia/UserProfilePageV3/js/UserProfilePage.js
  extensions/wikia/UserProfilePageV3/js/ext.wikia.userProfile.avatarManager.js
  extensions/wikia/UserProfilePageV3/templates/UserProfilePage_renderLightbox.php
  includes/User.php
  skins/oasis/modules/BodyController.class.php
Labels: SRE, active-active

#16156 SUS-5880 | more resources for mediawiki-tasks
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16158 SUS-5855 | install redis PHP extension in Dockerfile
  composer.json
  docker/README.md
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php.template
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#16130 SRE-107 | Refactor CreateNewWiki flow for performance
  docker/dev/site.conf
  docker/prod/site.conf.template
  docker/sandbox/site.conf
  extensions/wikia/CreateNewWiki/CreateNewWiki_setup.php
  extensions/wikia/CreateNewWiki/CreateWikiTask.php
  extensions/wikia/CreateNewWiki/classes/BulkRevisionImporter.php
  extensions/wikia/CreateNewWiki/classes/Starters.class.php
  extensions/wikia/CreateNewWiki/maintenance/importStarter.php
  extensions/wikia/CreateNewWiki/maintenance/setMainPageContent.php
  extensions/wikia/CreateNewWiki/tasks/ConfigureUsers.php
  extensions/wikia/CreateNewWiki/tasks/ConfigureWikiFactory.php
  extensions/wikia/CreateNewWiki/tasks/CreateDatabase.php
  extensions/wikia/CreateNewWiki/tasks/CreateTables.php
  extensions/wikia/CreateNewWiki/tasks/EnableDiscussionsTask.php
  extensions/wikia/CreateNewWiki/tasks/ImportStarterData.php
  extensions/wikia/CreateNewWiki/tasks/LinkFandomCreatorCommunity.php
  extensions/wikia/CreateNewWiki/tasks/ReplicationWaitHelper.php
  extensions/wikia/CreateNewWiki/tasks/SetCustomSettings.php
  extensions/wikia/CreateNewWiki/tasks/SetMainPageContent.php
  extensions/wikia/CreateNewWiki/tasks/SetupWikiCities.php
  extensions/wikia/CreateNewWiki/tasks/TaskContext.php
  extensions/wikia/CreateNewWiki/tasks/TaskHelper.php
  extensions/wikia/CreateNewWiki/tasks/TaskRunner.php
  extensions/wikia/CreateNewWiki/tests/tasks/ConfigureUsersIntegrationTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/ConfigureUsersTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/ConfigureWikiFactoryTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/CreateDatabaseTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/ImportStarterDataTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/SetupWikiCitiesIntegrationTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/SetupWikiCitiesTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/fixtures/configure_users.yaml
  extensions/wikia/CreateNewWiki/tests/tasks/fixtures/setup_wikicities.yaml
  extensions/wikia/Discussions/api/DiscussionsActivator.class.php
  includes/Import.php
  includes/Setup.php
  includes/TitleArray.php
  includes/db/Database.php
  includes/db/DatabaseMysqli.php
  includes/wikia/VariablesBase.php
  includes/wikia/VariablesExpansions.php
  includes/wikia/WikiaUpdater.php
  lib/Wikia/src/Tasks/Tasks/CreateNewWikiTask.php
  maintenance/update.php
  tests/php-tests.sh
Labels: SRE, active-active

#16170 slower scaling for mediawiki-tasks
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16157 SUS-5855 | use Redis as a temporary metrics storage for Prometheus
  LocalSettings.php
  docker/dev/site.conf
  docker/prod/prod.template.yaml
  docker/prod/site.conf.template
  docker/sandbox/README.md
  docker/sandbox/sandbox.template.yaml
  docker/sandbox/site.conf
  includes/wikia/VariablesExpansions.php
  lib/Wikia/src/Metrics/Collector.php
  lib/Wikia/src/Tasks/TaskRunner.php
  metrics.php
Labels: sus, sus-kubernetes

#16153 Remove rewrites for magic DS API
  docker/dev/site.conf
  docker/prod/site.conf.template
  docker/sandbox/site.conf
Labels: Don't merge, sus, sus-kubernetes

#16179 SRE-111: Don't try to acquire an exclusive lock in PoolCounterWork
  extensions/PoolCounter/PoolCounterClient_body.php
  includes/PoolCounter.php
Labels: SRE, active-active

#16175 SUS-6026 | WikiFactoryLoader - make sure /proxy.php requests are handled like command line scripts
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
Labels: sus

#16178 SUS-6028 | WikiFactoryLoader - do not redirect to the main domain when handling requests with X-Mw-Wiki-Id header set
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
Labels: sus

#16197 SRE-111 | another take at slow exclusive locks
  includes/PoolCounter.php
Labels: SRE, active-active

#16203 SUS-6046 | fix path to yaml files with job-specific parameters
  docker/maintenance/create-cronjob-yaml.sh
Labels: sus, sus-kubernetes

#16192 SUS | extract base conf to base.inc
  docker/base/base.inc
  docker/dev/docker-compose.yml
  docker/dev/site.conf
  docker/prod/Dockerfile-nginx
  docker/prod/site.conf.template
  docker/sandbox/Dockerfile-nginx
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#16209 SUS-6049 | point CreateNewWiki links to community.wikia.com
  includes/wikia/models/DesignSystemSharedLinks.class.php
Labels: sus, sus-wikia-com-migration

#16212 Docker | add shell helper scripts
  docker/prod/README.md
  docker/prod/prod_shell.sh
  docker/sandbox/README.md
  docker/sandbox/sandbox_shell.sh
Labels: sus, sus-kubernetes

#16216 SUS-6048 | migrate www.wikia.com/WAM to community.wikia.com/wiki/WAM
  includes/wikia/models/DesignSystemSharedLinks.class.php
  includes/wikia/services/WAMService.class.php
Labels: sus, sus-wikia-com-migration

#16206 SUS-5873 use array_replace to preserve proper curl options
  lib/Wikia/src/Tasks/Tasks/ParsoidCacheUpdateTask.php
Labels: sus, sus-kubernetes

#16219 SUS-6051 | because of The Complex Way wiki domain is passed down to nginx we need to use /redirect-canonical.php to handle these redirects
  docker/base/base.inc
  docker/prod/site.conf.template
  docker/sandbox/site.conf
  redirect-canonical.php
Labels: sus, sus-kubernetes

#16071 IW-778 Adds google connect button
  extensions/wikia/AuthPreferences/AuthPreferences.i18n.php
  extensions/wikia/AuthPreferences/AuthPreferences.setup.php
  extensions/wikia/AuthPreferences/AuthPreferencesController.php
  extensions/wikia/AuthPreferences/AuthPreferencesHooks.php
  extensions/wikia/AuthPreferences/AuthPreferencesModuleService.php
  extensions/wikia/AuthPreferences/crowdin.conf
  extensions/wikia/AuthPreferences/modules/ext.wikia.authPreferences.css
  extensions/wikia/AuthPreferences/modules/ext.wikia.authPreferences.js
  extensions/wikia/AuthPreferences/templates/AuthPreferencesModuleService_renderAuthPreferences.php
  extensions/wikia/AuthPreferences/tests/AuthPreferencesControllerTest.php
  extensions/wikia/AuthPreferences/tests/AuthPreferencesModuleServiceTest.php
  extensions/wikia/FacebookPreferences/FacebookPreferences.setup.php
  extensions/wikia/FacebookPreferences/modules/ext.wikia.facebookPreferences.js
  includes/wikia/DefaultSettings.php
Labels: Don't merge, Work in progress

#16237 SRE-111 | Fix false negative issue in PoolWorkArticleView
  includes/WikiPage.php
  includes/parser/ParserCache.php
Labels: SRE, active-active

#16240 SUS-5237 | sunset MapLib extension, maplib.net is gone and it does not support HTTPS
  extensions/3rdparty/MapLib/MapLib.php
  extensions/wikia/HideTags/HideTags.php
  includes/wikia/Extensions.php
Labels: sus, sus-sunsets-2018

#16239 SUS-4938 | redirect Special:PopularPages to Special:Insights/popularpages
  extensions/wikia/InsightsV2/specials/PopularPages.class.php
Labels: sus, sus-sunsets-2018

#16243 SUS-6068: change rollout strategy to Recreate for sandbox/preview deployment
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#16245 SRE-111 | Clear in-memory cache for the parser output as well
  includes/parser/ParserCache.php
Labels: SRE, active-active

#16242 SRE-117 | Add process cache to MercuryApi templates processing
  includes/wikia/parser/templatetypes/TemplateTypesParser.class.php
  includes/wikia/parser/templatetypes/handlers/InfoIconTemplate.class.php
  includes/wikia/parser/templatetypes/tests/TemplateTypesParserTest.php
Labels: SRE, active-active

#16251 SUS-6077 | CloseWikiMaintenance - move to a next wiki instead of failing the entire process
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus

#16252 SUS-6081 | htmlescape serchFormId in Search_Index.php template
  skins/oasis/modules/templates/Search_Index.php
Labels: sus

#16254 SUS-5674 | increase maxReplicas and minReplicas from production Kubernetes
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16226 SRE-116 | Redo ProtectSite with a database backend
  extensions/wikia/ProtectSiteII/ProtectSite.i18n.php
  extensions/wikia/ProtectSiteII/ProtectSite.php
  extensions/wikia/ProtectSiteII/ProtectSiteHooks.php
  extensions/wikia/ProtectSiteII/ProtectSiteModel.php
  extensions/wikia/ProtectSiteII/ProtectSiteSpecialController.php
  extensions/wikia/ProtectSiteII/maintenance/purgeExpiredSiteProtections.php
  extensions/wikia/ProtectSiteII/tests/ProtectSiteHooksIntegrationTest.php
  extensions/wikia/ProtectSiteII/tests/ProtectSiteModelIntegrationTest.php
  extensions/wikia/ProtectSiteII/tests/ProtectSiteSpecialControllerIntegrationTest.php
  extensions/wikia/ProtectSiteII/tests/fixtures/protect_site_model.yaml
  extensions/wikia/ProtectSiteII/tests/fixtures/protect_site_shared.yaml
  extensions/wikia/WikiaStyleGuide/WikiaStyleGuideFormHelper.class.php
  extensions/wikia/WikiaStyleGuide/templates/WikiaStyleGuideForm_index.php
  includes/WebRequest.php
  includes/wikia/Extensions.php
  includes/wikia/nirvana/WikiaSpecialPageController.class.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesBeforeWikiFactory.php
  maintenance/wikia/sql/wikicities-schema.sql
Labels: SRE, active-active

#16269 SRE-116 | Fix handling of ProtectSite expiry suppression
  extensions/wikia/ProtectSiteII/ProtectSiteSpecialController.php
Labels: SRE, active-active

#16268 SUS-6084 | increase PHP container memory limit
  docker/README.md
  docker/base/Dockerfile
  docker/base/php-fpm.conf
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/prod/prod.template.yaml
  docker/sandbox/Dockerfile-php.template
  docker/sandbox/Jenkinsfile
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#16275 SUS-6087 fix image upload problems
  docker/prod/nginx.conf
  docker/sandbox/nginx.conf
Labels: sus, sus-kubernetes

#16278 SRE | Move tasks publishing to RestInPeace hooks
  extensions/wikia/SwiftSync/tests/ImageSyncTest.php
  includes/wikia/Extensions.php
  lib/Wikia/src/Factory/ServiceFactory.php
  lib/Wikia/src/Factory/SwiftSyncFactory.php
  lib/Wikia/src/Rabbit/ConnectionManager.php
  lib/Wikia/src/Rabbit/DefaultTaskPublisher.php
  lib/Wikia/src/Rabbit/NullTaskPublisher.php
  lib/Wikia/src/Rabbit/TaskPublisher.php
  lib/Wikia/src/SwiftSync/Hooks.php
  lib/Wikia/src/SwiftSync/SwiftSync.setup.php
  lib/Wikia/src/SwiftSync/SwiftSyncTaskProducer.php
  lib/Wikia/src/Tasks/Tasks/ImageSyncTask.php
  lib/Wikia/tests/SwiftSync/HooksTest.php
  lib/Wikia/tests/SwiftSync/SwiftSyncTaskProducerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: SRE

#16281 SUS-6160 | Explicitly set timeouts for nginx - fpm communication
  docker/base/nginx.conf
  docker/dev/docker-compose.yml
  docker/prod/Dockerfile-nginx
  docker/sandbox/Dockerfile-nginx
  docker/sandbox/nginx.conf
Labels: sus, sus-kubernetes

#16273 PLATFORM-3762: render language wikis index page
  extensions/wikia/LanguageWikisIndex/LanguageWikisIndex.setup.php
  extensions/wikia/LanguageWikisIndex/LanguageWikisIndexController.class.php
  extensions/wikia/LanguageWikisIndex/LanguageWikisIndexHooks.class.php
  extensions/wikia/LanguageWikisIndex/templates/LanguageWikisIndexController_index.mustache
  extensions/wikia/RobotsTxt/RobotsTxt.setup.php
  extensions/wikia/RobotsTxt/WikiaRobotsHooks.class.php
  extensions/wikia/RobotsTxt/classes/WikiaRobots.class.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/Loader/closedWikiHandler.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: Don't merge, Work in progress

#16286 More pods for mediawiki-tasks
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16285 SUS-6157 | /extensions and /skins requests for wikis with language code in a path are redirected by nginx
  docker/base/base.inc
  docker/base/nginx.conf
  docker/prod/Dockerfile-nginx
  docker/sandbox/Dockerfile-nginx
Labels: sus, sus-kubernetes

#16284 support other environments in sandbox/Jenkinsfile
  docker/sandbox/Jenkinsfile
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#16293 SUS-6164 | move wfLogProfilingData before fastcgi_finish_request is called
  includes/Wiki.php
  includes/profiler/ProfilerXhprof.php
Labels: sus, sus-kubernetes

#16294 Simple probes for mediawiki-tasks nginx
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16300 migrate to irc-s2 - take two
  includes/wikia/VariablesBase.php
Labels: sus
