Repository Wikia/app, pull requests merged in 2018-07, with the labels that each got.

#15618 Document extensions/wikia/WikiFactory/DeadWikis
  extensions/wikia/WikiFactory/DeadWikis/README.md
Labels: sus

#15592 SUS-5293 Add maintenance tasks to queue
  extensions/wikia/WikiFactory/WikiFactory.php
  lib/Wikia/src/Tasks/Tasks/MaintenanceTask.php
  maintenance/maintenanceTaskScheduler.php
Labels: sus, sus-kubernetes

#15620 SUS-5459 | install exif PHP extension
  composer.json
  docker/README.md
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15614 SUS-5405 | Use k8s internal ingress for calling services on Kubernetes
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Factory/ProviderFactory.php
  lib/Wikia/src/Service/Gateway/InternalIngressUrlProvider.php
  lib/Wikia/tests/Service/Gateway/InternalIngressUrlProviderTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: sus, sus-kubernetes

#15631 SUS-5452 | remove UpdateSpecialPagesTask, we use good old updateSpecialPages.php maintenance script
  lib/Wikia/src/Tasks/Tasks/UpdateSpecialPagesTask.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  maintenance/updateSpecialPages.php
Labels: sus, sus-sunsets-2018

#15632 remove apache configuration from docker
  docker/apache/Dockerfile
  docker/apache/apache.conf
  docker/apache/docker-compose.yml
Labels: sus, sus-kubernetes

#15633 move docker ignore to docker directory
  docker/.dockerignore
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15635 SUS-5396 | MaintenanceTask - validate the path
  includes/wikia/VariablesBase.php
  includes/wikia/VariablesExpansions.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
  lib/Wikia/src/Tasks/Queues/ParsoidPurgePriorityQueue.php
  lib/Wikia/src/Tasks/Queues/ParsoidPurgeQueue.php
  lib/Wikia/src/Tasks/Queues/PriorityQueue.php
  lib/Wikia/src/Tasks/Queues/PurgeQueue.php
  lib/Wikia/src/Tasks/Queues/Queue.php
  lib/Wikia/src/Tasks/Queues/SMWQueue.php
  lib/Wikia/src/Tasks/Queues/ScheduledMaintenanceQueue.php
  lib/Wikia/src/Tasks/Tasks/BaseTask.php
  lib/Wikia/src/Tasks/Tasks/MaintenanceTask.php
  lib/Wikia/tests/Tasks/MaintenanceTaskTest.php
  maintenance/maintenanceTaskScheduler.php
Labels: sus, sus-kubernetes

#15624 PLATFORM-3548: remove unnecessary path manipulations when doing HTTPS…
  extensions/wikia/HTTPSSupport/HTTPSSupport.setup.php
  extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
  extensions/wikia/SitemapXml/SpecialSitemap_body.php
Labels: Don't merge

#15630 SUS-5465 | per-sandbox k8s ingress
  docker/sandbox/sandbox-sus2.yaml
  docker/sandbox/sandbox.template.yaml
  docker/sandbox/site.conf
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-kubernetes

#15643 Fix update schemas.sh
  maintenance/wikia/sql/archive-schema.sql
  maintenance/wikia/sql/dataware-schema.sql
  maintenance/wikia/sql/portability_db-schema.sql
  maintenance/wikia/sql/specials-schema.sql
  maintenance/wikia/sql/statsdb-schema.sql
  maintenance/wikia/sql/update-schemas.sh
  maintenance/wikia/sql/wikicities-schema.sql
Labels: sus

#15645 SUS-4571 & SUS-5472 | video-related maintenance scripts cleanup
  extensions/wikia/VideoHandlers/videoInfo/VideoInfoHelper.class.php
  maintenance/wikia/VideoHandlers/fsckVideos.php
  maintenance/wikia/VideoHandlers/updateThumbnail.php
  maintenance/wikia/VideoHandlers/videoTagCount.php
Labels: sus, sus-sunsets-2018

#15647 SUS-4571 | UpdateThumbnailTask is rarely used, remove it
  extensions/wikia/VideoHandlers/UpdateThumbnailTask.class.php
  extensions/wikia/VideoHandlers/VideoFileUploader.class.php
  extensions/wikia/VideoHandlers/VideoHandlerHelper.class.php
  extensions/wikia/VideoHandlers/VideoHandlers.setup.php
Labels: sus, sus-sunsets-2018

#15649 SUS-5464 - mw to k8s - deploy to both dc at once
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15646 SUS-5396 | Migrate cron tab from cron-s1 to k8s cron jobs
  docker/maintenance/README.md
  docker/maintenance/maintenance-cronjob-example.yaml
  docker/maintenance/one-time-job-example.yaml
Labels: sus, sus-kubernetes

#15615 PLATFORM-3543: surrogate keys for purging the whole wiki
  extensions/wikia/MercuryApi/MercuryApiController.class.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  includes/OutputHandler.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Wikia.php
Labels: Don't merge

#15652 SUS-5514 - gather parser cache usage
  includes/Article.php
Labels: sus

#15655 SUS-5453 | sunset updateDatawarePages.php maintenance script
  maintenance/wikia/updateDatawarePages.php
Labels: sus, sus-kubernetes, sus-sunsets-2018

#15653 SUS-5313 | fix mediawiki-sql logger and make it have more details on request context
  includes/db/Database.php
Labels: sus

#15667 SUS-5479 | sendConfirmationReminder - provide some output
  extensions/wikia/AuthPages/maintenance/sendConfirmationReminder.php
Labels: sus, sus-kubernetes

#15665 SUS-5473 | Special:Statistics - add a button to run updateSpecialPages.php script
  extensions/wikia/UpdateSpecialPagesScheduler/UpdateSpecialPagesScheduler.class.php
  extensions/wikia/UpdateSpecialPagesScheduler/UpdateSpecialPagesScheduler.i18n.php
  extensions/wikia/UpdateSpecialPagesScheduler/UpdateSpecialPagesScheduler.setup.php
  extensions/wikia/UpdateSpecialPagesScheduler/crowdin.conf
  extensions/wikia/UpdateSpecialPagesScheduler/templates/scheduler.tmpl.php
  extensions/wikia/WikiFactory/Dumps/DumpsOnDemand.php
  extensions/wikia/WikiFactory/Dumps/templates/dod.tmpl.php
  includes/wikia/Extensions.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
Labels: sus

#15654 SUS-5470 | yaml for phrase-alerts
  docker/maintenance/phrase-alerts.yaml
  maintenance/wikia/phrase-alerts.php
Labels: sus, sus-kubernetes

#15651 SUS-5478 | remove optimizely vars
  includes/wikia/VariablesBase.php
Labels: sus, sus-kubernetes

#15650 SUS--1 | Small linter fixes
  extensions/wikia/ArticleVideo/templates/ArticleVideo_featured.php
  extensions/wikia/Forum/templates/Forum_threadMessageButtons.php
  extensions/wikia/PageHeader/templates/PageHeaderController_buttons.php
  extensions/wikia/Search/templates/WikiaSearch_mediadata.php
  extensions/wikia/Search/templates/WikiaSearch_toparticles.php
  extensions/wikia/UserTools/templates/UserTools_Menu.php
  extensions/wikia/Wall/templates/WallHistory_index.php
Labels: sus

#15675 SUS-5516 | TaskManager sunset
  CODEOWNERS
  extensions/wikia/CoppaTool/RenameIPProcess.class.php
  extensions/wikia/MultiTasks/MultiTasks.i18n.php
  extensions/wikia/MultiTasks/SpecialMultiDelete.php
  extensions/wikia/MultiTasks/SpecialMultiWikiEdit.php
  extensions/wikia/SiteWideMessages/SpecialSiteWideMessages.i18n.php
  extensions/wikia/TaskManager/BatchTask.php
  extensions/wikia/TaskManager/SpecialTaskManager.aliases.php
  extensions/wikia/TaskManager/SpecialTaskManager.i18n.php
  extensions/wikia/TaskManager/SpecialTaskManager.php
  extensions/wikia/TaskManager/SpecialTaskManager_body.php
  extensions/wikia/TaskManager/TaskManagerExecutor.php
  extensions/wikia/TaskManager/Tasks/ImageImporterTask/form.tmpl.php
  extensions/wikia/TaskManager/Tasks/LocalMaintenanceTask/central.tmpl.php
  extensions/wikia/TaskManager/Tasks/PageImporterTask.php
  extensions/wikia/TaskManager/Tasks/PageImporterTask/form.tmpl.php
  extensions/wikia/TaskManager/Tasks/UpdateSpecialPagesTask.php
  extensions/wikia/TaskManager/hooks/TaskManagerHooks.class.php
  extensions/wikia/TaskManager/maintenance/archive.php
  extensions/wikia/TaskManager/templates/alarm.tmpl.php
  extensions/wikia/TaskManager/templates/form.tmpl.php
  extensions/wikia/TaskManager/templates/log.tmpl.php
  extensions/wikia/TaskManager/templates/pager.tmpl.php
  extensions/wikia/TaskManager/templates/taskform.tmpl.php
  extensions/wikia/UserRenameTool/SpecialRenameuser.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
  maintenance/wikia/RenameIP_local.php
  maintenance/wikia/TaskManagerMaintenance.php
Labels: sus, sus-sunsets-2018

#15680 in k8s jenkins pipeline add missing space :(
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15682 Travis | cache compiled version of pecl packages
  .travis.yml
Labels: sus, travis

#15684 SUS-5455 | founder-emails jobs + cronjob-generator.sh
  docker/maintenance/create-cronjob-yaml.sh
  docker/maintenance/cronjob-generator.sh
  docker/maintenance/cronjob-template.yaml
  docker/maintenance/example-maintenance-cronjob.yaml
  docker/maintenance/example-one-time-job.yaml
  docker/maintenance/founder-emails-complete-digest.yaml
  docker/maintenance/founder-emails-days-passed.yaml
  docker/maintenance/founder-emails-views-digest.yaml
  docker/maintenance/phrase-alerts.yaml
Labels: sus, sus-kubernetes

#15694 SUS-5457 | LyricWiki - get rid of SOAP failures database tables
  extensions/3rdparty/LyricWiki/Special_LinksToRedirects.php
  extensions/3rdparty/LyricWiki/Special_MobileSearches.i18n.php
  extensions/3rdparty/LyricWiki/Special_MobileSearches.php
  extensions/3rdparty/LyricWiki/Special_Soapfailures.i18n.php
  extensions/3rdparty/LyricWiki/Special_Soapfailures.php
  extensions/3rdparty/LyricWiki/server.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
  maintenance/wikia/truncateSoapFailures.php
Labels: sus, sus-sunsets-2018

#15671 SUS-5510 | remove-qa-wikis job
  docker/maintenance/remove-qa-wikis.yaml
Labels: sus, sus-kubernetes

#15699 SUS-5474 | add SiteWideMessagesMaintenance job
  docker/maintenance/site-wide-messages-maintenance.yaml
Labels: sus, sus-kubernetes

#15661 SUS-5454 | SMW-conceptCache job
  docker/maintenance/SMW-conceptCache.yaml
Labels: sus, sus-kubernetes

#15686 SUS-5521 | support nested subdomains in k8s
  docker/prod/nginx.conf
  docker/prod/prod.template.yaml
  docker/prod/site.conf
  docker/sandbox/nginx.conf
  docker/sandbox/sandbox-sus2.yaml
  docker/sandbox/sandbox.template.yaml
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#15689 SUS-5468 | add close-my-account cronjob
  docker/maintenance/close-my-account.yaml
  extensions/wikia/CloseMyAccount/maintenance/CloseMyAccountMaintenance.php
Labels: sus, sus-kubernetes

#15681 SUS-5477 | add docker/maintenance/cleanup-upload-stash.yaml
  docker/maintenance/cleanup-upload-stash.yaml
Labels: sus, sus-kubernetes

#15678 SUS-5501 | cleanupPhalanxStats k8s template
  docker/maintenance/cleanup-phalanx-stats.yaml
  extensions/wikia/PhalanxII/maintenance/cleanupPhalanxStats.php
Labels: sus, sus-kubernetes

#15677 SUS-5550 | docker/maintenance/dump-starters.yaml added
  docker/maintenance/dump-starters.yaml
Labels: sus, sus-kubernetes, 🐷​

#15676 SUS-5508 | add dumps-on-demand cronjob
  docker/maintenance/dumps-on-demand.yaml
Labels: sus, sus-kubernetes

#15670 SUS-5467 | add lyricwiki-crawler
  docker/maintenance/lyricwiki-crawler.yaml
Labels: sus, sus-kubernetes

#15668 SUS-5452 | maintenance/updateSpecialPages.php cronjob YAML definition
  docker/maintenance/update-special-pages.yaml
Labels: sus, sus-kubernetes

#15663 config for initStat task
  docker/maintenance/initStat.yaml
Labels: sus, sus-kubernetes

#15705 SUS | add documentation about testing MW on Kubernetes
  docker/prod/README.md
Labels: sus, sus-kubernetes

#15707 SUS-5526 | validate NGINX configuration for syntax errors
  docker/prod/Dockerfile-nginx
  docker/sandbox/Dockerfile-nginx
Labels: sus, sus-kubernetes

#15708 SUS | remove sandbox-sus2 static descriptor
  docker/sandbox/sandbox-sus2.yaml
Labels: sus, sus-kubernetes

#15709 SUS | run NGINX validation as nginx user
  docker/prod/Dockerfile-nginx
  docker/sandbox/Dockerfile-nginx
Labels: sus, sus-kubernetes

#15622 SUS-5392 | refactor maintenance/wikia/updateCentralInterwiki scripts
  maintenance/wikia/city_interwiki_links.sql
  maintenance/wikia/updateCentralInterwiki.inc
  maintenance/wikia/updateCentralInterwiki.php
Labels: sus, sus-kubernetes

#15711 SUS-5479 | fix sendConfirmationReminder script
  extensions/wikia/AuthPages/maintenance/sendConfirmationReminder.php
Labels: sus

#15712 SUS-5527 | Configure rolling update for MediaWiki on Kubernetes
  docker/prod/Jenkinsfile
  docker/prod/prod.template.yaml
  docker/prod/site.conf
  docker/sandbox/Jenkinsfile
  docker/sandbox/sandbox.template.yaml
  docker/sandbox/site.conf
  health.php
Labels: sus, sus-kubernetes

#15716 SUS-5523 | Kill PHP notice on Special:Community
  extensions/wikia/CommunityPage/models/CommunityPageSpecialInsightsModel.class.php
  extensions/wikia/InsightsV2/helpers/InsightsSorting.php
  extensions/wikia/InsightsV2/services/InsightsService.class.php
Labels: sus

#15719 SUS | bump docker images version
  docker/base/Dockerfile
  docker/base/Dockerfile-logger
  docker/prod/Jenkinsfile
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15723 SUS-5540 | install luasandbox extension
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
  includes/wikia/Extensions.php
Labels: sus, sus-kubernetes

#15722 SUS-5533 | Use fixed worker count for PHP FPM
  docker/base/Dockerfile
  docker/base/php-fpm.conf
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15728 SUS-5561 | format PHP FPM access logs as JSON
  docker/base/Dockerfile
  docker/base/php-fpm.conf
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15733 SUS | add documentation about logging in maintenance scripts
  docker/K8S_LOGGING.md
Labels: sus, sus-kubernetes

#15732 SUS | cut down k8s pod resources requests
  docker/prod/prod.template.yaml
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#15735 Use latest image
  docker/maintenance/cronjob-template.yaml
  docker/sandbox/README.md
Labels: sus, sus-kubernetes

#15737 SUS-5565 | Configure Prometheus metrics collection for PHP FPM
  docker/base/Dockerfile
  docker/base/php-fpm.conf
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/prod/prod.template.yaml
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
  docker/sandbox/sandbox.template.yaml
Labels: Work in progress

#15743 SUS-5566 | Fix PHP FPM configuration loading order
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15744 SUS-5567 | use non-privileged user in logger container
  docker/base/Dockerfile-logger
Labels: sus, sus-kubernetes

#15745 SUS-5568 | disable PHP FPM access logs
  docker/base/Dockerfile
  docker/base/php-fpm.conf
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15748 SUS-5569 | Reduce amount of PHP FPM workers
  docker/base/Dockerfile
  docker/base/php-fpm.conf
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15749 SUS-5570 | Remove dependency on calendar extension
  extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php
Labels: sus, sus-kubernetes

#15752 SUS-5571 | Add resource limits configuration and autoscaling
  docker/prod/prod.template.yaml
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#15758 SUS-5572 | port production opcache and keepalive settings
  docker/base/Dockerfile
  docker/base/php.ini
  docker/dev/Dockerfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/prod/nginx.conf
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
  docker/sandbox/nginx.conf
Labels: sus, sus-kubernetes

#15761 SUS-5658 | use redirect-canonical.php as missing path error handler
  docker/dev/site.conf
  docker/prod/site.conf
  docker/sandbox/site.conf
  redirect-canonical.php
Labels: sus, sus-kubernetes

#15765 SUS-5662 | Add missing NGINX rewrites
  docker/dev/site.conf
  docker/prod/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#15762 SUS-5659 | MySQLKeyValueModel can go away as Optimizely has been sunset
  includes/wikia/DefaultSettings.php
  includes/wikia/models/MySQLKeyValueModel.class.php
  maintenance/wikia/sql/specials-schema.sql
Labels: sus, sus-sunsets-2018

#15760 SUS-5531 | Apply CronJobs along with MW release - so they run on latest code deployed
  docker/maintenance/create-cronjob-yaml.sh
  docker/maintenance/cronjob-template.yaml
  docker/maintenance/cronjobs-generator.sh
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15771 SUS-5531 | to avoid execute permission problems just execute the script via bash binary
  docker/README.md
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15770 SUS-5508 | Remove dumps-on-demand.yaml as it should be an async task
  docker/maintenance/dumps-on-demand.yaml
Labels: sus, sus-kubernetes

#15772 SUS-5531 | the inner script as well, doh!
  docker/maintenance/cronjobs-generator.sh
Labels: sus, sus-kubernetes

#15730 SUS-5669 | don't add rel="canonical" link on the closed wiki page
  extensions/wikia/CanonicalHref/CanonicalHref.php
Labels: sus

#15734 SUS-5562 | create prod deployment and service for background tasks
  docker/prod/prod.template.yaml
  docker/prod/site.conf
Labels: sus, sus-kubernetes

#15776 k8s | do NOT apply crons during deployment, we need to clean up cron-s1 crontab first
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15738 ADEN-7303 Disables CMP when the new one is defined
  extensions/wikia/AdEngine/js/lookup/a9.js
  extensions/wikia/AdEngine/js/spec/lookup/a9.spec.js
  extensions/wikia/TrackingOptIn/dist/tracking-opt-in.min.js
  extensions/wikia/TrackingOptIn/js/cmp.js
Labels: Don't merge

#15775 SUS-5672 | publish Slack notifications on production deployments
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#15750 SUS-5506 | improve Close/maintenance script
  docker/maintenance/README.md
  docker/maintenance/wiki-factory-close-marked-wikis.yaml
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus, sus-kubernetes

#15648 SUS-5499 | Use internal host name for MW->MW requests on Kubernetes
  LocalSettings.php
  docker/maintenance/cronjob-template.yaml
  docker/prod/prod.template.yaml
  docker/sandbox/sandbox.template.yaml
  includes/HttpFunctions.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-kubernetes

#15790 SUS-5500 | add mysqldump, required by dumpStarters.php script
  docker/README.md
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/maintenance/dump-starters.yaml
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15794 Use the latest k8s-deployer
  docker/maintenance/README.md
  docker/prod/Jenkinsfile
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15778 SUS-5508 | Convert DumpsOnDemand from a cron job to a task
  extensions/wikia/WikiFactory/Dumps/DumpsOnDemand.php
  extensions/wikia/WikiFactory/Dumps/README.md
  extensions/wikia/WikiFactory/Dumps/maintenance/DumpsOnDemandCron.php
  extensions/wikia/WikiFactory/Dumps/runBackups.php
  lib/Wikia/README.md
  lib/Wikia/src/Tasks/AsyncTaskList.php
  lib/Wikia/src/Tasks/Queues/DumpsOnDemandQueue.php
  lib/Wikia/src/Tasks/Tasks/DumpsOnDemandTask.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: sus, sus-kubernetes

#15798 SUS-5476 | TorBlock - add logs for the maintenance script
  extensions/TorBlock/TorBlock.class.php
  extensions/TorBlock/TorBlock.php
Labels: sus, sus-kubernetes

#15805 release-703 | SUS-5470 | Use UserMailer in phraseAlerts cron job
  docker/maintenance/phrase-alerts.yaml
  maintenance/wikia/cronjobs/phraseAlerts.php
  maintenance/wikia/phrase-alerts.php
Labels: sus, sus-kubernetes

#15800 SUS-5681 | force the wiki to be included in wikis search results despite having less than 50 articles
  extensions/wikia/Search/WikiaSearchIndexerController.class.php
  extensions/wikia/Search/classes/IndexService/AbstractWikiService.php
  extensions/wikia/Search/classes/IndexService/CrossWikiCore.php
  extensions/wikia/Search/classes/QueryService/Select/Dismax/InterWiki.php
  extensions/wikia/Search/tests/IndexService/CrossWikiCoreTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/InterWikiTest.php
Labels: sus, sus-search

#15806 release-703 | SUS-5454 | Use WikiaLogger in SMW's RebuildConceptCache
  extensions/SemanticMediaWiki/maintenance/rebuildConceptCache.php
Labels: sus, sus-kubernetes

#15809 release-703 | Add context to maintenance script assertion logs
  lib/Wikia/src/Tasks/Tasks/MaintenanceTask.php
Labels: sus

#15802 Log maintenance output to logstash
  extensions/SemanticMediaWiki/maintenance/rebuildConceptCache.php
  maintenance/Maintenance.php
Labels: sus, sus-kubernetes

#15810 SUS-5454 | Remove smw-concept-cache cron job
  docker/maintenance/smw-concept-cache.yaml
Labels: sus, sus-kubernetes

#15808 SUS-5500 | DumpStarters - remove --set-gtid-purged=OFF from mysqldump
  extensions/wikia/CreateNewWiki/maintenance/dumpStarters.php
Labels: sus, sus-kubernetes

#15817 SUS-5525 | sunset TorBlock extension
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
Labels: sus, sus-sunsets-2018

#15818 SUS-5466 | Fix the active parameter in init-stat cron job
  docker/maintenance/init-stat.yaml
Labels: sus, sus-kubernetes

#15819 SUS-5476 | final cleanup after TorBlock extension sunset
  docker/maintenance/README.md
  docker/maintenance/load-exit-nodes.yaml
  extensions/TorBlock/ASN1Parser.php
  extensions/TorBlock/TorBlock.class.php
  extensions/TorBlock/TorBlock.i18n.php
  extensions/TorBlock/TorBlock.php
  extensions/TorBlock/loadExitNodes.php
  extensions/wikia/Chat2/Chat.class.php
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
Labels: sus, sus-sunsets-2018

#15820 SUS-5467 | Run lyric wiki maintenance script on lyric wiki
  docker/maintenance/lyricwiki-crawler.yaml
Labels: sus, sus-kubernetes

#15815 Increase successful cron job history limit
  docker/maintenance/cronjob-template.yaml
Labels: sus, sus-kubernetes

#15822 SUS-5474 | Improve logs from SiteWideMessagesMaintenance
  extensions/wikia/SiteWideMessages/SiteWideMessagesMaintenance.php
Labels: sus, sus-kubernetes

#15826 SRE-92 | Disable read-only HTML error page for wikia.php POSTs
  includes/WebStart.php
Labels: active-active

#15829 SUS-5665 | Add language suffix when sending title and content to solr
  extensions/wikia/Search/classes/IndexService/Evaluation.php
Labels: sus, sus-search-evaluation
