Repository Wikia/app, pull requests merged in 2018-03, with the labels that each got.

#14904 SUS-4080 | video_info - drop premium, hdfile and featured columns
  extensions/wikia/VideoHandlers/sql/video_info.sql
  extensions/wikia/VideoHandlers/videoInfo/VideoInfo.class.php
Labels: sus, sus-sunsets-2018

#14892 SUS-4269 | Remove Video Wiki references from Search
  extensions/wikia/Search/WikiaSearch.i18n.php
  extensions/wikia/Search/WikiaSearchController.class.php
  extensions/wikia/Search/classes/Config.php
  extensions/wikia/Search/classes/QueryService/Select/Dismax/CombinedMedia.php
  extensions/wikia/Search/classes/QueryService/Select/Dismax/Video.php
  extensions/wikia/Search/classes/QueryService/Select/Dismax/VideoContent.php
  extensions/wikia/Search/classes/QueryService/Select/Dismax/VideoEmbedTool.php
  extensions/wikia/Search/classes/QueryService/Select/Dismax/VideoTitle.php
  extensions/wikia/Search/js/WikiaSearch.js
  extensions/wikia/Search/templates/WikiaSearch_tabs.php
  extensions/wikia/Search/tests/ConfigTest.php
  extensions/wikia/Search/tests/Controller/SearchControllerTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/CombinedMediaTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/VideoTitleTest.php
  extensions/wikia/VideoEmbedTool/VideoEmbedToolSearchService.class.php
  extensions/wikia/VideoEmbedTool/tests/VideoEmbedToolSearchServiceTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  skins/oasis/modules/SearchController.class.php
Labels: sus, sus-sunsets-2018

#14915 SUS-3996 | GameGuideToCuratedContentHelper is not used anywhere
  extensions/wikia/CuratedContent/maintenance/GameGuideToCuratedContentHelper.php
  extensions/wikia/CuratedContent/tests/GameGuideToCuratedContentMigrationTest.php
Labels: sus, sus-sunsets-2018

#14911 SUS-3851 | Support for loading different wikis from the same domain based on the language code in the path
  LocalSettings.php
  extensions/wikia/CityList/tests/UpdateCityListTaskIntegrationTest.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  extensions/wikia/WikiFactory/tests/fixtures/wiki_factory_loader.yaml
  includes/Setup.php
  includes/wikia/GlobalFunctions.php
  includes/wikia/tests/core/MockGlobalVariableTrait.php
  includes/wikia/tests/core/WikiaDatabaseTest.php
  skins/oasis/modules/BlogListingController.class.php
  tests/Makefile
  tests/bootstrap.php
  tests/fixtures/wikicities.sql
  tests/run-test.php
Labels: sus, sus-https

#14880 SUS-4194 in Answers extension use getLocalUrl instead manual creation
  extensions/wikia/Answers/Answers.php
  extensions/wikia/Answers/HomePageList.php
  extensions/wikia/Answers/SpecialGetQuestionWidget.php
Labels: sus-https

#14924 SUS-4291 | video_info - avoid SELECT * query
  extensions/wikia/VideoHandlers/videoInfo/VideoInfo.class.php
Labels: sus

#14921 SUS-4115 | wall_history - do not set post_ns and deleted_or_removed columns
  extensions/wikia/Wall/WallHistory.class.php
  extensions/wikia/Wall/sql/wall_history_local.sql
Labels: sus, sus-sunsets-2018

#14928 SUS-4294 | video_info - do not perform INSERT IGNORE
  extensions/wikia/VideoHandlers/videoInfo/VideoInfo.class.php
Labels: sus

#14923 SUS-4282 | TTF fonts cleanup in CuratedContent and GameGuides
  extensions/wikia/CuratedContent/assets/CuratedContentAssets.json
  extensions/wikia/CuratedContent/css/CuratedContent.scss
  extensions/wikia/CuratedContent/fonts/DroidSerif.ttf
  extensions/wikia/CuratedContent/fonts/RobotoThin.ttf
  extensions/wikia/GameGuides/assets/GameGuidesAssets.json
  extensions/wikia/GameGuides/css/GameGuides.scss
  extensions/wikia/GameGuides/fonts/DroidSerif.ttf
  extensions/wikia/GameGuides/fonts/RobotoThin.ttf
  extensions/wikia/GameGuides/maintenance/buildGameGuidesAssets.php
Labels: sus, sus-sunsets-2018

#14936 SUS-3741 | introduce fixBrokenVideoReuploads maintenance script
  extensions/wikia/VideoHandlers/maintenance/fixBrokenVideoReuploads.php
Labels: sus

#14926 SUS-4279 | Refactor WikiFactory variable manager to not use eval()
  extensions/wikia/WikiFactory/SpecialWikiFactory.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_ajax.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/WikiFactoryVariableParseException.php
  extensions/wikia/WikiFactory/WikiFactoryVariableParser.php
  extensions/wikia/WikiFactory/api/ApiWikiFactoryRemoveVariable.php
  extensions/wikia/WikiFactory/api/ApiWikiFactorySaveVariable.php
  extensions/wikia/WikiFactory/js/ext.wikia.wikiFactory.requestManager.js
  extensions/wikia/WikiFactory/js/ext.wikia.wikiFactory.variableManager.js
  extensions/wikia/WikiFactory/js/ext.wikia.wikiFactory.variableService.js
  extensions/wikia/WikiFactory/templates/form.tmpl.php
  extensions/wikia/WikiFactory/templates/variable.tmpl.php
  extensions/wikia/WikiFactory/tests/ApiWikiFactoryRemoveVariableIntegrationTest.php
  extensions/wikia/WikiFactory/tests/ApiWikiFactorySaveVariableIntegrationTest.php
  extensions/wikia/WikiFactory/tests/WikiFactoryTest.php
  extensions/wikia/WikiFactory/tests/WikiFactoryVariableParserTest.php
  extensions/wikia/WikiFactory/tests/fixtures/api_variable.yaml
  includes/wikia/DefaultSettings.php
  includes/wikia/tests/core/ApiIntegrationTestTrait.php
  tests/bootstrap.php
  tests/fixtures/wikicities.sql
Labels: sus

#14927 SUS-3685 | add basic deduplication to BatchRefreshLinksForTemplateTask
  includes/BacklinkCache.php
  includes/LinksUpdate.php
  lib/Wikia/src/Tasks/Tasks/BatchRefreshLinksForTemplate.php
Labels: sus

#14942 MOB-12051 - Revert "SUS-4282 | TTF fonts cleanup in CuratedContent and GameGuides"
  extensions/wikia/CuratedContent/assets/CuratedContentAssets.json
  extensions/wikia/CuratedContent/css/CuratedContent.scss
  extensions/wikia/CuratedContent/fonts/DroidSerif.ttf
  extensions/wikia/CuratedContent/fonts/RobotoThin.ttf
  extensions/wikia/GameGuides/assets/GameGuidesAssets.json
  extensions/wikia/GameGuides/css/GameGuides.scss
  extensions/wikia/GameGuides/fonts/DroidSerif.ttf
  extensions/wikia/GameGuides/fonts/RobotoThin.ttf
  maintenance/wikia/buildGameGuidesAssets.php
Labels: sus

#14947 SUS-3723 | API sometimes states anon pages were created by "A FANDOM user"
  includes/api/ApiQueryRevisions.php
Labels: sus, user-rename-tool

#14949 SUS-4302 | Remove trailing slash from domain cache query
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
Labels: sus

#14952 SUS-3754 | Parser::fetchScaryTemplateMaybeFromCache - use a memcache instead of in-database cache
  includes/installer/DatabaseUpdater.php
  includes/installer/MysqlUpdater.php
  includes/parser/Parser.php
  includes/wikia/WikiaUpdater.php
  maintenance/archives/patch-tc-timestamp.sql
  maintenance/archives/patch-transcache.sql
  maintenance/tables.sql
Labels: sus, sus-sunsets-2018

#14951 SUS-3754 | make long SQL queries fit the error message sent via UDP to Logstash
  includes/db/Database.php
Labels: sus

#14959 SUS-4301 | Rename tool should validate new username against anti-spoofing rules
  extensions/wikia/UserRenameTool/RenameUserProcess.class.php
  extensions/wikia/UserRenameTool/tests/RenameUserSetupChecksTest.php
Labels: sus, user-rename-tool

#14964 SUS-4301 | Rename tool should validate new username against anti-spoofing rules [prod]
  extensions/wikia/UserRenameTool/RenameUserProcess.class.php
  extensions/wikia/UserRenameTool/tests/RenameUserSetupChecksTest.php
Labels: sus, user-rename-tool

#14961 SUS-4282 | TTF fonts cleanup in CuratedContent and GameGuides - take two
  extensions/wikia/CuratedContent/assets/CuratedContentAssets.json
  extensions/wikia/CuratedContent/css/CuratedContent.scss
  extensions/wikia/CuratedContent/fonts/DroidSerif.ttf
  extensions/wikia/CuratedContent/fonts/RobotoThin.ttf
  extensions/wikia/GameGuides/assets/GameGuidesAssets.json
  extensions/wikia/GameGuides/assets/README.md
  extensions/wikia/GameGuides/css/GameGuides.scss
  extensions/wikia/GameGuides/fonts/DroidSerif.ttf
  extensions/wikia/GameGuides/fonts/RobotoThin.ttf
  maintenance/wikia/buildGameGuidesAssets.php
Labels: sus, sus-sunsets-2018

#14968 SUS-2902 | Force categorytree to use content language for error messages
  extensions/CategoryTree/CategoryTreeFunctions.php
  extensions/CategoryTree/CategoryTreePage.php
Labels: sus

#14971 SUS-4301 | check for emojis in user name - invert the check logic
  extensions/wikia/UserRenameTool/RenameUserProcess.class.php
Labels: sus, user-rename-tool

#14946 SUS-3181 | revert XW-2315 - Add new starter for English TV wikis
  extensions/wikia/CreateNewWiki/classes/Starters.class.php
  extensions/wikia/CreateNewWiki/maintenance/importStarter.php
  extensions/wikia/CreateNewWiki/tasks/ConfigureWikiFactory.php
  extensions/wikia/CreateNewWiki/tasks/ImportStarterData.php
  extensions/wikia/CreateNewWiki/tests/tasks/ImportStarterDataTest.php
Labels: sus, sus-sunsets-2018

#14969 SUS-3873 | create API endpoint for easy turning ON/OFF read only mode
  extensions/wikia/WikiFactory/SpecialWikiFactory_ajax.php
Labels: sus

#14974 SUS-4310: Rollback edit transaction when external store insert fails
  includes/WikiPage.php
Labels: sus

#14903 SUS-4272 | Remove rotten code from VideoHandlers
  extensions/wikia/FilePage/FilePageController.class.php
  extensions/wikia/FilePage/FilePageHooks.class.php
  extensions/wikia/FilePage/WikiaFilePage.php
  extensions/wikia/FilePage/css/FilePageTabbed.scss
  extensions/wikia/FilePage/scripts/WikiaFilePage.js
  extensions/wikia/FilePage/templates/FilePage_videoCaption.php
  extensions/wikia/Lightbox/LightboxController.class.php
  extensions/wikia/Lightbox/tests/LightboxControllerTest.php
  extensions/wikia/Search/classes/Config.php
  extensions/wikia/Search/classes/IndexService/MediaData.php
  extensions/wikia/SpecialVideos/SpecialVideosHelper.class.php
  extensions/wikia/SpecialVideos/SpecialVideosSpecialController.class.php
  extensions/wikia/VideoHandlers/README.md
  extensions/wikia/VideoHandlers/VideoFileUploader.class.php
  extensions/wikia/VideoHandlers/VideoHandlerController.class.php
  extensions/wikia/VideoHandlers/VideoHandlerHelper.class.php
  extensions/wikia/VideoHandlers/VideoHandlerSpecialController.class.php
  extensions/wikia/VideoHandlers/VideoHandlers.i18n.php
  extensions/wikia/VideoHandlers/VideoHandlers.setup.php
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapperFactory.class.php
  extensions/wikia/VideoHandlers/apiwrappers/FakeApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/PrototypeApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/VimeoApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/YoukuApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/YoutubeApiWrapper.class.php
  extensions/wikia/VideoHandlers/filerepo/WikiaLocalFileShared.class.php
  extensions/wikia/VideoHandlers/filerepo/WikiaNoArticleLocalFile.class.php
  extensions/wikia/VideoHandlers/handlers/VideoHandler.class.php
  extensions/wikia/VideoHandlers/handlers/VimeoVideoHandler.class.php
  extensions/wikia/VideoHandlers/templates/VideoHandlerSpecial_index.php
  extensions/wikia/VideoHandlers/videoInfo/VideoInfoHelper.class.php
  includes/wikia/services/WikiaFileHelper.class.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
Labels: sus, sus-sunsets-2018

#14963 SUS-4233 | Remove WikiaMobile search
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/Search/WikiaSearch.i18n.php
  extensions/wikia/Search/WikiaSearch.setup.php
  extensions/wikia/Search/WikiaSearchController.class.php
  extensions/wikia/Search/classes/Hooks.php
  extensions/wikia/Search/css/WikiaSearch.wikiamobile.scss
  extensions/wikia/Search/js/WikiaSearch.wikiamobile.js
  extensions/wikia/Search/templates/WikiaSearch_CrossWiki_WikiaMobileResult.php
  extensions/wikia/Search/templates/WikiaSearch_WikiaMobileIndex.php
  extensions/wikia/Search/templates/WikiaSearch_WikiaMobileResult.php
  extensions/wikia/Search/templates/WikiaSearch_WikiaMobileResultList.php
  extensions/wikia/Search/tests/HooksTest.php
Labels: sus, sus-https, sus-sunsets-2018

#14979 SUS-4308 | Sunset AppPromoLanding extension
  extensions/wikia/AppPromoLanding/AppPromoLanding.i18n.php
  extensions/wikia/AppPromoLanding/AppPromoLandingController.class.php
  extensions/wikia/AppPromoLanding/AppPromoLanding_setup.php
  extensions/wikia/AppPromoLanding/crowdin.conf
  extensions/wikia/AppPromoLanding/images/appleAppStoreButton.png
  extensions/wikia/AppPromoLanding/images/nexus6.png
  extensions/wikia/AppPromoLanding/images/nexus6_large.png
  extensions/wikia/AppPromoLanding/images/playStoreButton.png
  extensions/wikia/AppPromoLanding/images/silverIphone.png
  extensions/wikia/AppPromoLanding/images/silverIphone_large.png
  extensions/wikia/AppPromoLanding/js/appPromoLanding.js
  extensions/wikia/AppPromoLanding/templates/AppPromoLanding_content.php
  extensions/wikia/AppPromoLanding/templates/AppPromoLanding_index.php
  extensions/wikia/AssetsManager/config.php
  includes/wikia/Extensions.php
Labels: sus, sus-sunsets-2018

#14982 SUS-4317 | we do not use LCStore_DB
  includes/AutoLoader.php
  includes/LocalisationCache.php
  includes/installer/MysqlUpdater.php
  maintenance/Maintenance.php
  maintenance/archives/patch-l10n_cache.sql
  maintenance/tables.sql
Labels: sus, sus-sunsets-2018

#14976 SUS | remove unused LogEventsApiController
  includes/logging/LogPage.php
  includes/wikia/DefaultSettings.php
  includes/wikia/api/LogEventsApiController.class.php
  includes/wikia/api/tests/LogEventsApiControllerTest.php
Labels: sus, sus-sunsets-2018

#14984 SUS-1529 | ipb_create_account column is no longer needed on ipblocks table
  maintenance/tables.sql
  tests/fixtures/BlockTest.yaml
Labels: sus, sus-sunsets-2018

#14953 SUS-4293 | Remove template classification data for deleted templates and closed wikis
  .gitignore
  extensions/wikia/TemplateClassification/TemplateClassification.hooks.php
  extensions/wikia/TemplateClassification/maintenance/removeClassificationForClosedWikis.php
  extensions/wikia/TemplateClassification/maintenance/removeClassificationForDeletedTemplates.php
  extensions/wikia/TemplateClassification/tests/TemplateClassificationHooksTest.php
  includes/wikia/services/TemplateClassificationService.class.php
  includes/wikia/tests/TemplateClassificationServiceIntegrationTest.php
  includes/wikia/tests/_fixtures/tcs_details_response.json
  includes/wikia/tests/_fixtures/tcs_templates_response.json
  lib/Swagger/README_content-entity.md
  lib/Swagger/README_template-classification.md
  lib/Swagger/README_user-attribute.md
  lib/Swagger/README_user-avatar.md
  lib/Swagger/README_user-preference.md
  lib/Swagger/cleanup.sh
  lib/Swagger/src/ApiClient.php
  lib/Swagger/src/ApiException.php
  lib/Swagger/src/Configuration.php
  lib/Swagger/src/ObjectSerializer.php
  lib/Swagger/src/TemplateClassification/Storage/Api/TCSApi.php
  lib/Swagger/src/TemplateClassification/Storage/Models/TemplateClassificationData.php
  lib/Swagger/src/TemplateClassification/Storage/Models/TemplateTypeHolder.php
  lib/Swagger/src/TemplateClassification/Storage/Models/TemplateTypeProvider.php
  lib/Swagger/src/TemplateClassification/Storage/Models/TemplateTypeStats.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: sus, sus-sunsets-2018

#14983 Revert "PLATFORM-1727: Add extra logging around (un)deleting articles"
  includes/WikiPage.php
  includes/specials/SpecialUndelete.php
Labels: sus, sus-sunsets-2018

#14987 SUS-4250 | Sunset DevBoxPanel extension
  extensions/wikia/Development/SpecialDevBoxPanel/DevBoxPanel.css
  extensions/wikia/Development/SpecialDevBoxPanel/DevBoxPanel.js
  extensions/wikia/Development/SpecialDevBoxPanel/Special_DevBoxPanel.i18n.php
  extensions/wikia/Development/SpecialDevBoxPanel/Special_DevBoxPanel.php
  extensions/wikia/Development/SpecialDevBoxPanel/templates/special-devboxpanel.tmpl.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
Labels: sus, sus-sunsets-2018

#14990 SUS-3798 | INSERT IGNORE is pure evil, remove IGNORE flag from ChangeTags class
  includes/ChangeTags.php
Labels: sus

#14992 SUS-4313 | Class 'DumpsOnDemand' not found
  extensions/wikia/WikiFactory/Dumps/DumpsOnDemand.php
  extensions/wikia/WikiFactory/Dumps/runBackups.php
Labels: sus

#14970 Handle language in article path
  extensions/wikia/MercuryApi/MercuryApiController.class.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
Labels: Work in progress

#14998 SUS-4325 | CloseWikiMaintenance should remove directories with images after tar file is created
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus

#14993 SUS-3740 - in AbuseFilter use same actionID generation method
  extensions/AbuseFilter/AbuseFilter.class.php
  extensions/AbuseFilter/AbuseFilter.hooks.php
Labels: sus

#14965 ADEN-6797 | Load prebid.js library in the main JS package
  extensions/wikia/AdEngine/AdEngine2ContextService.class.php
  extensions/wikia/AdEngine/js/lookup/prebid/prebid.js
  extensions/wikia/AdEngine/js/spec/lookup/prebid/prebid.spec.js
  extensions/wikia/AssetsManager/config.php
Labels: Don't merge

#14989 SUS-3742 do not check defaults zeros edits and age in AutoPromotion
  extensions/TorBlock/TorBlock.class.php
  includes/Autopromote.php
Labels: sus

#15003 SUS-4323 | SpecialTags - fix a PHP notice
  includes/specials/SpecialTags.php
Labels: sus

#15006 SUS-4330 | UserTemplateClassificationService::getType type hints
  extensions/wikia/TemplateClassification/services/UserTemplateClassificationService.class.php
Labels: sus

#15007 SUS-4322 | remove IGNORE flag from INSERT made by FounderProgressBarHooks::initRecords()
  extensions/wikia/FounderProgressBar/FounderProgressBarHooks.class.php
Labels: sus

#15008 SUS-4333 | do not use SELECT * FROM in WikiFactoryHub:getWikiCategories
  extensions/wikia/Track/Track.php
  extensions/wikia/WikiFactory/Hubs/WikiFactoryHub.php
Labels: sus

#15004 SUS-4181 | Remove wgDBcluster and wgDBname values from WikiFactory and use values from city_list row
  extensions/wikia/WikiFactory/Close/maintenance.php
  extensions/wikia/WikiFactory/Close/simpleclose.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/templates/form.tmpl.php
  includes/wikia/LBFactory_Wikia.php
Labels: sus

#15012 SUS-4181 | WikiFactoryPage - prevent a fatal
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
Labels: sus

#15019 SUS-4324 | document maintenance/DumpsOnDemandCron.php script
  extensions/wikia/WikiFactory/Dumps/README.md
Labels: sus

#15018 SUS-4337 | Remove portability_dashboard table from dataware DB
  maintenance/wikia/sql/dataware-schema.sql
Labels: sus, sus-utf8

#15017 SUS-4274 | WikiMetrics class is gone since #14906
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
  extensions/wikia/WikiFactory/templates/selector.tmpl.php
Labels: sus, sus-sunsets-2018

#15026 SUS-4336 | ReviewModel - do not use SELECT * FROM
  extensions/wikia/ContentReview/models/ReviewModel.php
Labels: sus

#15023 SUS-4339 | dumps - no need to set dump_wiki_dbname and dump_wiki_url columns
  extensions/wikia/WikiFactory/Dumps/DumpsOnDemand.php
Labels: sus, sus-sunsets-2018

#15005 SUS-4329: Extract auth pages related code to a dedicated extension
  extensions/wikia/AuthPages/AuthPages.alias.php
  extensions/wikia/AuthPages/AuthPages.setup.php
  extensions/wikia/AuthPages/AuthPagesHooks.php
  extensions/wikia/AuthPages/EmailConfirmationController.class.php
  extensions/wikia/AuthPages/maintenance/sendConfirmationReminder.php
  extensions/wikia/AuthPages/specials/AbstractAuthPageRedirect.php
  extensions/wikia/AuthPages/specials/SpecialSignupRedirect.php
  extensions/wikia/AuthPages/specials/SpecialUserLoginRedirect.php
  extensions/wikia/AuthPages/specials/SpecialUserSignupRedirect.php
  extensions/wikia/AuthPages/specials/SpecialWikiaConfirmEmailRedirect.php
  extensions/wikia/AuthPages/specials/UserLogoutSpecialController.php
  extensions/wikia/AuthPages/specials/templates/UserLogoutSpecialController_index.php
  extensions/wikia/AuthPages/tests/AbstractAuthPageRedirectTest.php
  extensions/wikia/AuthPages/tests/AuthPagesTest.php
  extensions/wikia/AuthPages/tests/EmailConfirmationControllerIntegrationTest.php
  extensions/wikia/AuthPages/tests/SpecialSignupRedirectTest.php
  extensions/wikia/AuthPages/tests/SpecialUserLoginRedirectTest.php
  extensions/wikia/AuthPages/tests/SpecialUserSignupRedirectTest.php
  extensions/wikia/AuthPages/tests/SpecialWikiaConfirmEmailRedirectTest.php
  extensions/wikia/AuthPages/tests/fixtures/email_confirmation.yaml
  extensions/wikia/UserLogin/UserLogin.setup.php
  extensions/wikia/UserLogin/maintenance.php
  extensions/wikia/UserLogout/UserLogout.setup.php
  includes/OutputPage.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Extensions.php
  tests/fixtures/wikicities.sql
Labels: sus, sus-sunsets-2018

#15037 SUS-4341 | AvatarService - handle "avatar" URLs with scaling parameters stored
  includes/wikia/services/AvatarService.class.php
  includes/wikia/services/tests/AvatarServiceTest.php
Labels: sus

#15043 Revert "SUS-4329: Extract auth pages related code to a dedicated extension"
  extensions/wikia/AuthPages/AuthPages.setup.php
  extensions/wikia/AuthPages/maintenance/sendConfirmationReminder.php
  extensions/wikia/AuthPages/specials/AbstractAuthPageRedirect.php
  extensions/wikia/AuthPages/specials/SpecialSignupRedirect.php
  extensions/wikia/AuthPages/specials/SpecialUserLoginRedirect.php
  extensions/wikia/AuthPages/specials/SpecialUserSignupRedirect.php
  extensions/wikia/AuthPages/specials/SpecialWikiaConfirmEmailRedirect.php
  extensions/wikia/AuthPages/tests/AbstractAuthPageRedirectTest.php
  extensions/wikia/AuthPages/tests/AuthPagesTest.php
  extensions/wikia/AuthPages/tests/EmailConfirmationControllerIntegrationTest.php
  extensions/wikia/AuthPages/tests/SpecialSignupRedirectTest.php
  extensions/wikia/AuthPages/tests/SpecialUserLoginRedirectTest.php
  extensions/wikia/AuthPages/tests/SpecialUserSignupRedirectTest.php
  extensions/wikia/AuthPages/tests/SpecialWikiaConfirmEmailRedirectTest.php
  extensions/wikia/AuthPages/tests/fixtures/email_confirmation.yaml
  extensions/wikia/UserLogin/EmailConfirmationController.class.php
  extensions/wikia/UserLogin/EmailConfirmationHooks.class.php
  extensions/wikia/UserLogin/UserLogin.setup.php
  extensions/wikia/UserLogin/UserSignup.alias.php
  extensions/wikia/UserLogin/maintenance.php
  extensions/wikia/UserLogout/UserLogout.setup.php
  extensions/wikia/UserLogout/UserLogoutSpecialController.php
  extensions/wikia/UserLogout/templates/UserLogoutSpecialController_index.php
  includes/OutputPage.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Extensions.php
  tests/fixtures/wikicities.sql
Labels: sus

#15044 SUS-4345 | WikiFactory: wiki name entry form is forcing selection from dropdown, making wikis hard to access
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
Labels: sus

#15053 SUS-4321 | WatchedItem::addWatch - remove IGNORE flag from INSERT queries
  includes/WatchedItem.php
Labels: sus

#15045 SUS-4344 | WikiPage::insertOn - do not set IGNORE flag when inserting new rows
  includes/WikiPage.php
Labels: sus

#15059 SUS-4352: MWF - don't query dataware.pages for a lower case title
  extensions/wikia/MultiTasks/SpecialMultiWikiFinder_body.php
Labels: sus

#15033 XF-248 | Cleanup after XW-4654
  extensions/wikia/ArticleAsJson/ArticleAsJson.class.php
  extensions/wikia/ArticleAsJson/templates/media-gallery-old.mustache
  extensions/wikia/ArticleAsJson/templates/media-thumbnail-old.mustache
  extensions/wikia/MercuryApi/MercuryApiController.class.php
  extensions/wikia/PortableInfobox/services/Helpers/PortableInfoboxImagesHelper.php
  extensions/wikia/PortableInfobox/services/Helpers/PortableInfoboxMustacheEngine.php
  extensions/wikia/PortableInfobox/services/PortableInfoboxMobileRenderService.class.php
  extensions/wikia/PortableInfobox/services/Sanitizers/SanitizerBuilder.php
  extensions/wikia/PortableInfobox/templates/PortableInfoboxItemHeroMobileOld.mustache
  extensions/wikia/PortableInfobox/templates/PortableInfoboxItemImageCollectionMobileOld.mustache
  extensions/wikia/PortableInfobox/templates/PortableInfoboxItemImageMobileOld.mustache
  extensions/wikia/PortableInfobox/tests/PortableInfoboxImagesHelperTest.php
  extensions/wikia/PortableInfobox/tests/PortableInfoboxMobileRenderServiceTest.php
  includes/wikia/api/ArticlesApiController.class.php
Labels: Don't merge

#15066 SUS-1941 | Fix getDatabase.php maintenance script
  maintenance/wikia/getDatabase.php
Labels: sus

#15058 SUS-4139: tweak - hide test mode button when needed
  extensions/wikia/ContentReview/controllers/JSPagesSpecialController.class.php
  extensions/wikia/ContentReview/controllers/templates/ContentReviewModule.mustache
  extensions/wikia/ContentReview/controllers/templates/JSPagesSpecialController_index.php
  skins/oasis/modules/ContentReviewModuleController.class.php
Labels: sus

#15057 SUS-3693: fix deleting anons' articles via Quick Tools
  extensions/wikia/QuickTools/QuickToolsHelper.class.php
  extensions/wikia/QuickTools/tests/QuickToolsHelperIntegrationTest.php
Labels: sus

#15073 SUS-4495: Feed article-snippet-worker directly from MW
  extensions/wikia/IndexingPipeline/IndexingPipeline.setup.php
  extensions/wikia/IndexingPipeline/PipelineEventProducer.class.php
Labels: sus, sus-sunsets-2018

#15075 SUS-4497 | compressOld.php - set the flag saying that the old_text is a pseudo-URL to blobs entry
  maintenance/storage/compressOld.php
Labels: sus, sus-utf8

#15086 SUS-4497 | CompressOld - use Revision::getRevisionText to get the raw text
  maintenance/storage/compressOld.php
Labels: sus, sus-utf8

#15089 SUS-4354 | PhalanxStatsPager - get rid of SELECT * FROM
  extensions/wikia/PhalanxII/classes/PhalanxStatsPager.class.php
Labels: sus

#15096 SUS-4503 | remove CreateNewWikiTask::sendRevisionToScribe
  lib/Wikia/src/Tasks/Tasks/CreateNewWikiTask.php
Labels: sus, sus-sunsets-2018

#15097 SUS-4504 | WikiaUpdater - no need to remove videos marked as premium
  includes/wikia/WikiaUpdater.php
Labels: sus

#15090 SUS-4033 | Fix unbingind keydown events in Lightbox
  extensions/wikia/Lightbox/scripts/LightboxLoader.js
Labels: sus

#15094 SUS-4329 | LocalFile::recordUpload2 - use ON DUPLICATE KEY UPDATE instead of IGNORE flag in INSERT query
  includes/filerepo/file/LocalFile.php
Labels: sus

#15088 SUS-3165 | CreateNewWiki - legal checkbox always visible
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/js/WikiBuilder.js
Labels: sus

#15069 SUS-4463: Fix some block notices not rendering blocker name
  extensions/wikia/ArticleComments/classes/ArticleCommentList.class.php
  includes/Title.php
  includes/User.php
  includes/wikia/tests/WikiaControllerTest.php
  includes/wikia/tests/core/WikiaDatabaseTest.php
  tests/unit/includes/BlockIntegrationTest.php
Labels: sus
