Repository Wikia/app, pull requests merged in 2018-06, with the labels that each got.

#15428 SUS-4784 | Allow to create wikis with the language code in the path via CNW
  extensions/wikia/CreateNewWiki/CreateNewWikiHooks.php
  extensions/wikia/CreateNewWiki/CreateNewWiki_setup.php
  extensions/wikia/CreateNewWiki/CreateWikiChecks.php
  extensions/wikia/CreateNewWiki/SpecialCreateNewWiki.class.php
  extensions/wikia/CreateNewWiki/SpecialFinishCreate.class.php
  extensions/wikia/CreateNewWiki/js/WikiBuilder.js
  extensions/wikia/CreateNewWiki/tasks/ConfigureWikiFactory.php
  extensions/wikia/CreateNewWiki/tasks/PrepareDomain.php
  extensions/wikia/CreateNewWiki/tasks/TaskContext.php
  extensions/wikia/CreateNewWiki/templates/CreateNewWiki_Index.php
  extensions/wikia/CreateNewWiki/tests/CreateWikiChecksTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/ConfigureWikiFactoryTest.php
  extensions/wikia/CreateNewWiki/tests/tasks/PrepareDomainTest.php
  includes/wikia/VariablesBase.php
Labels: sus

#15392 SUS-4814 | Remove Monobook specific code from Wall
  extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js
  extensions/wikia/DesignSystem/services/DesignSystemGlobalNavigationWallNotificationsService.class.php
  extensions/wikia/DesignSystem/services/templates/DesignSystemGlobalNavigationWallNotifications_Notification.php
  extensions/wikia/DesignSystem/services/templates/DesignSystemGlobalNavigationWallNotifications_NotificationAdmin.php
  extensions/wikia/DesignSystem/services/templates/DesignSystemGlobalNavigationWallNotifications_NotifyEveryone.php
  extensions/wikia/DesignSystem/services/templates/DesignSystemGlobalNavigationWallNotifications_Update.php
  extensions/wikia/DesignSystem/services/templates/DesignSystemGlobalNavigationWallNotifications_empty.php
  extensions/wikia/DesignSystem/services/templates/DesignSystemGlobalNavigation_index.php
  extensions/wikia/Forum/ForumNotificationPlugin.class.php
  extensions/wikia/Wall/Wall.i18n.php
  extensions/wikia/Wall/Wall.setup.php
  extensions/wikia/Wall/WallBaseController.class.php
  extensions/wikia/Wall/WallHistoryController.class.php
  extensions/wikia/Wall/WallHooksHelper.class.php
  extensions/wikia/Wall/WallTabsRenderer.php
  extensions/wikia/Wall/css/Wall.scss
  extensions/wikia/Wall/css/monobook/WallHistoryMonobook.scss
  extensions/wikia/Wall/css/monobook/WallMonobook.scss
  extensions/wikia/Wall/js/Wall.js
  extensions/wikia/Wall/js/WallEditMessageForm.js
  extensions/wikia/Wall/js/WallMessageForm.js
  extensions/wikia/Wall/js/WallNewMessageForm.js
  extensions/wikia/Wall/js/WallReplyMessageForm.js
  extensions/wikia/Wall/templates/Wall_messageButtons.php
  extensions/wikia/Wall/tests/WallTabsRendererTest.php
  extensions/wikia/WallNotifications/GlobalNavigationWallNotificationsController.class.php
  extensions/wikia/WallNotifications/WallNotificationControllerBase.class.php
  extensions/wikia/WallNotifications/WallNotifications.setup.php
  extensions/wikia/WallNotifications/WallNotificationsController.class.php
  extensions/wikia/WallNotifications/WallNotificationsExternalController.class.php
  extensions/wikia/WallNotifications/WallNotificationsHooksHelper.class.php
  extensions/wikia/WallNotifications/scripts/WallNotifications.js
  extensions/wikia/WallNotifications/styles/WallNotifications.scss
  extensions/wikia/WallNotifications/styles/monobook/WallNotificationsMonobook.scss
  extensions/wikia/WallNotifications/templates/GlobalNavigationWallNotifications_Index.php
  extensions/wikia/WallNotifications/templates/WallNotifications_Index.php
  extensions/wikia/WallNotifications/templates/WallNotifications_Notification.php
  extensions/wikia/WallNotifications/templates/WallNotifications_NotificationAdmin.php
  extensions/wikia/WallNotifications/templates/WallNotifications_NotifyEveryone.php
  extensions/wikia/WallNotifications/templates/WallNotifications_Update.php
  extensions/wikia/WallNotifications/templates/WallNotifications_empty.php
  extensions/wikia/WallNotifications/tests/WallNotificationsControllerTest.php
Labels: sus, sus-monobook, sus-sunsets-2018

#15456 🐖 | Address more PHP 7.2 incompatibilities
  extensions/3rdparty/LyricWiki/nusoap.php
  extensions/wikia/Blogs/BlogTemplate.php
  includes/AutoLoader.php
  includes/Xml.php
  includes/wikia/api/tests/WikisApiControllerTest.php
  includes/wikia/models/NavigationModel.class.php
Labels: sus, sus-php7.2

#15459 maintenance/wikia/dartKeyValueImport.php - treat comma as a columns separator
  maintenance/wikia/dartKeyValueImport.php
Labels: sus

#15458 SUS-5122 | DatabaseBase::isWriteQuery - treat "USE" query as a read
  includes/db/Database.php
  includes/db/DatabaseSqlite.php
  includes/wikia/tests/DatabaseTest.php
Labels: sus

#15457 🐖 | Address another set of PHP 7.2 incompatibilities
  extensions/SemanticForms/includes/forminputs/SF_DatePickerInput.php
  extensions/SyntaxHighlight_GeSHi/geshi/geshi.php
  extensions/wikia/ImageServing/imageServingHelper.class.php
  extensions/wikia/MultiTasks/MultiTasksCore.php
  extensions/wikia/WikiaWhiteList/WikiaExternalImageList.php
  extensions/wikia/WikiaWhiteList/WikiaWhiteList.php
  includes/wikia/services/tests/ArticleServiceTest.php
  lib/Wikia/src/Tasks/Tasks/BaseTask.php
  maintenance/dumpBackup.php
Labels: sus, sus-php7.2

#15453 SUS-3433 | add article_comments mapping table
  extensions/wikia/ArticleComments/ArticleCommentsHooks.class.php
  extensions/wikia/ArticleComments/ArticleComments_setup.php
  extensions/wikia/ArticleComments/maintenance/populateArticleCommentsIndex.php
  extensions/wikia/ArticleComments/sql/article_comments.sql
Labels: sus

#15475 SUS-3285 | render <youtube> tag to an empty string
  extensions/wikia/HideTags/HideTags.php
  extensions/wikia/YouTube/YouTube.i18n.php
  extensions/wikia/YouTube/YouTube.php
Labels: sus, sus-sunsets-2018

#15476 Wikia::setProps-save is simply polluting stdout
  extensions/wikia/MyHome/MyHome.class.php
  includes/wikia/Wikia.php
Labels: sus, sus-sunsets-2018

#15480 mock helios and user-preferences in rtbf tests
  extensions/wikia/Privacy/tests/UserDataRemoverTest.php
Labels: sus, sus-gdpr

#15478 SUS-4805 | keep the list of datacenters per environment in $wgConsulDataCenters global
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Consul/Client.php
Labels: active-active, sus

#15488 SUS-5128 | use GoogleMaps API key in Places extension
  extensions/Maps/Maps.php
  extensions/wikia/Places/PlacesController.class.php
  extensions/wikia/Places/PlacesParserHookHandler.class.php
  extensions/wikia/Places/templates/Places_renderMarkers.php
  resources/wikia/libraries/jquery/loadLibrary/jquery.wikia.loadLibrary.js
Labels: sus, sus-google-maps-api-key

#15449 ADEN-7169 Connects A9 to IAB GDPR framework
  extensions/wikia/AdEngine/AdEngine2Hooks.class.php
  extensions/wikia/AdEngine/js/context/adContext.js
  extensions/wikia/AdEngine/js/lookup/a9.js
  extensions/wikia/AdEngine/js/lookup/prebid/prebid.js
  extensions/wikia/AdEngine/js/spec/lookup/a9.spec.js
  extensions/wikia/AdEngine/js/wrappers/prebid.js
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/TrackingOptIn/TrackingOptIn.class.php
  extensions/wikia/TrackingOptIn/js/cmp.js
  includes/wikia/DefaultSettings.php
Labels: Don't merge

#15496 SUS-3285 | sunset YouTube extension
  extensions/wikia/YouTube/README.md
  extensions/wikia/YouTube/YouTube.php
  includes/wikia/Extensions.php
Labels: sus, sus-sunsets-2018

#15494 SUS-5128 | Google Maps views tracking
  extensions/Maps/includes/services/GoogleMaps3/ext.maps.googlemaps3.js
  extensions/SemanticForms/includes/forminputs/SF_GoogleMapsInput.php
  extensions/wikia/Places/js/Places.js
  includes/wikia/Extensions.php
Labels: sus

#15499 SUS-5128 | <place> - use API key when rendering static maps
  extensions/wikia/Places/models/PlaceModel.class.php
  extensions/wikia/Places/tests/PlacesTest.php
Labels: sus

#15501 New YouTube API key
  extensions/wikia/VideoHandlers/apiwrappers/YoutubeApiWrapper.class.php
Labels: sus

#15470 SUS-4383 | create a new wiki via an offline Celery task
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/CreateNewWiki_setup.php
  extensions/wikia/CreateNewWiki/CreateWiki.php
  extensions/wikia/CreateNewWiki/CreateWikiTask.php
  extensions/wikia/CreateNewWiki/js/WikiBuilder.js
  extensions/wikia/CreateNewWiki/tasks/ConfigureWikiFactory.php
  extensions/wikia/CreateNewWiki/tasks/TaskContext.php
  extensions/wikia/CreateNewWiki/tests/CreateNewWikiControllerTest.php
  includes/wikia/Extensions.php
  maintenance/wikia/sql/wikicities-schema.sql
Labels: active-active, sus

#15504 SUS-4281 | kill off revive spotlights 🔪
  includes/wikia/DefaultSettings.php
Labels: sus, sus-sunsets-2018

#15508 SUS-5226 | CloseWikiMaintenance - a proper DatabaseMysqli constructor call
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus

#15509 SUS-5135 | Disable devbox import script
  maintenance/wikia/getDatabase.php
Labels: sus, sus-gdpr

#15512 SUS-4281 | Remove Revive code from app
  extensions/wikia/Oasis/Oasis.i18n.php
  extensions/wikia/Spotlights/Spotlights.setup.php
  extensions/wikia/Spotlights/SpotlightsController.class.php
  extensions/wikia/Spotlights/SpotlightsHelper.php
  extensions/wikia/Spotlights/SpotlightsHooks.class.php
  extensions/wikia/Spotlights/js/AdProviderOpenX.js
  extensions/wikia/Spotlights/js/LazyLoadAds.js
  extensions/wikia/Spotlights/templates/Spotlights_Index.php
  extensions/wikia/WDACReview/WDACReviewSpecialController.class.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-sunsets-2018

#15516 SUS-4611 | Disable MemcachedPeclBagOStuff on devboxes
  extensions/wikia/WikiFactory/WikiFactory.php
  includes/wikia/DefaultSettings.php
Labels: sus, sus-kubernetes

#15517 SUS-5236 | Memoize anon user's default preferences
  lib/Wikia/src/Service/User/Preferences/PreferenceService.php
Labels: sus, sus-performance-improvement

#15491 SUS-4895 | Don't let tracking calls hang forever if opt-in modal cannot load
  resources/wikia/modules/tracker.js
Labels: sus

#15519 Revert "cake 2908 - save FC community id on wiki creation, don't send founder emails"
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/CreateNewWiki_setup.php
  extensions/wikia/CreateNewWiki/CreateWikiTask.php
  extensions/wikia/CreateNewWiki/tasks/LinkFandomCreatorCommunity.php
  extensions/wikia/CreateNewWiki/tasks/StartPostCreationTasks.php
  extensions/wikia/CreateNewWiki/tasks/TaskContext.php
  extensions/wikia/CreateNewWiki/tasks/TaskRunner.php
  extensions/wikia/FandomCreator/Api/CommunitySetupController.php
  extensions/wikia/FandomCreator/CommunitySetup.php
  extensions/wikia/FounderEmails/events/FounderEmailsDaysPassedEvent.class.php
  lib/Wikia/src/Tasks/Tasks/CreateNewWikiTask.php
Labels: sus

#15469 PLATFORM-3525: enable HTTPS on single domain wikis for all logged in users
  extensions/wikia/HTTPSOptIn/HTTPSOptIn.i18n.php
  extensions/wikia/HTTPSOptIn/HTTPSOptIn.setup.php
  extensions/wikia/HTTPSOptIn/crowdin.conf
  extensions/wikia/HTTPSSupport/HTTPSSupport.setup.php
  extensions/wikia/HTTPSSupport/HTTPSSupportHooks.class.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: Don't merge

#15473 SUS-5124 | sane cache invalidation for Wall/Forum
  extensions/wikia/ArticleComments/classes/ArticleComment.class.php
  extensions/wikia/ArticleComments/classes/ArticleCommentsAjax.class.php
  extensions/wikia/Forum/Forum.setup.php
  extensions/wikia/Forum/ForumHooksHelper.class.php
  extensions/wikia/Wall/Wall.class.php
  extensions/wikia/Wall/Wall.setup.php
  extensions/wikia/Wall/WallHooksHelper.class.php
  extensions/wikia/Wall/WallMessage.class.php
  extensions/wikia/Wall/builders/WallEditBuilder.class.php
  extensions/wikia/Wall/builders/WallMessageBuilder.class.php
  extensions/wikia/Wall/index/CommentsIndexHooks.class.php
  includes/wikia/services/UserStatsService.class.php
Labels: sus

#15173 SUS-4591: Allow to send MediaWiki logs to stdout as JSON
  LocalSettings.php
  docker/K8S_LOGGING.md
  docker/README.md
  docker/base/Dockerfile-logger
  docker/dev/README.md
  docker/dev/docker-compose.yml
  docker/dev/k8s/Dockerfile-php
  docker/dev/k8s/README.md
  docker/dev/k8s/nginx.conf
  docker/dev/k8s/poz-dev.yaml
  docker/dev/k8s/site.conf
  docker/dev/k8s/sjc-dev.yaml
  docker/dev/site.conf
  docker/sandbox/site.conf
  docker/sandbox/sjc.yaml
  includes/db/Database.php
  lib/Wikia/src/Logger/LoggerFactory.php
  lib/Wikia/src/Logger/WikiaLogger.php
  lib/Wikia/tests/Logger/LoggerFactoryTest.php
  lib/Wikia/tests/Logger/StatusProcessorTest.php
  lib/Wikia/tests/Logger/WikiaLoggerTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  tests/unit/includes/db/DatabaseBaseTest.php
Labels: sus, sus-kubernetes

#15523 SUS-5244 | Special:NewWiki shows 127.0.0.1 as founder's IP address
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/CreateWikiTask.php
  extensions/wikia/CreateNewWiki/tasks/SetupWikiCities.php
  extensions/wikia/CreateNewWiki/tasks/TaskContext.php
  extensions/wikia/CreateNewWiki/tests/CreateNewWikiControllerTest.php
Labels: sus

#15532 Update Docker README files
  docker/dev/README.md
  docker/dev/k8s/Dockerfile-nginx
  docker/dev/k8s/README.md
  docker/sandbox/Dockerfile-nginx
  docker/sandbox/README.md
Labels: sus, sus-kubernetes

#15536 SUS | fix wall notifications issue
  extensions/wikia/Wall/WallHelper.class.php
  extensions/wikia/Wall/builders/WallEditBuilder.class.php
  extensions/wikia/Wall/builders/WallMessageBuilder.class.php
  extensions/wikia/WallNotifications/WallNotificationEntity.class.php
Labels: sus

#15535 SUS-4742 | ChatConfig: use per-DC Consul agent instead of assuming a local one running on 127.0.0.1:8500
  extensions/wikia/Chat2/ChatConfig.class.php
  lib/Wikia/src/Consul/Client.php
Labels: sus, sus-kubernetes

#15538 Sus 5255 tideways sus 5252 igbinary
  docker/base/Dockerfile
  docker/base/README.md
Labels: sus, sus-kubernetes

#15528 SUS-5249 Add tidy extension
  composer.json
  docker/README.md
  docker/base/Dockerfile
  docker/dev/README.md
Labels: sus, sus-kubernetes

#15541 SUS-5252 | we no longer require igbinary and memcached PHP extensions
  docker/base/Dockerfile
Labels: sus, sus-kubernetes

#15545 ProfilerXhprof: fix a notice when 'mu' entry is not set
  includes/profiler/ProfilerXhprof.php
Labels: sus

#15549 SUS-5253 MW in K8s - in nginx - add rewrite from main path to index.php
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#15548 SUS-5263 | add PHP sockets extension
  composer.json
  docker/base/Dockerfile
Labels: sus, sus-kubernetes

#15550 SUS-5266 | explicitly add "severity" field to MediaWiki logs
  lib/Wikia/src/Logger/LogstashFormatter.php
Labels: sus, sus-kubernetes

#15554 SUS-5269 | Prevent FounderEmails from throwing error
  lib/Wikia/src/Service/User/Preferences/PreferenceService.php
  lib/Wikia/tests/Service/User/PreferenceServiceTest.php
Labels: sus

#15553 SUS-5267 | define wgConsulDataCenters entries for all environments
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Consul/Client.php
Labels: sus, sus-kubernetes

#15193 SUS-4533 | Moving php.ini setup to dockerfile
  docker/base/Dockerfile
  docker/base/php.ini
  docker/dev/Dockerfile
  docker/dev/phpdev.ini
Labels: sus, sus-kubernetes

#15555 SUS-5269 | Don't return ID of founder user if it's not set
  includes/wikia/services/WikiService.class.php
Labels: sus

#15552 SUS-2785 Fix messages cache
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#15556 SUS-5271 | handle short URLs - "/Foo" instead of "/wiki/Foo" but do not break known entry points
  docker/dev/k8s/site.conf
  docker/dev/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#15563 Docker | tag base PHP image with Dockerfile md5sum to avoid cache problems with "latest" tag
  docker/dev/Dockerfile
  docker/dev/k8s/Dockerfile-php
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15559 SUS-5272 Install pcntl extension
  composer.json
  docker/base/Dockerfile
  docker/sandbox/README.md
Labels: sus, sus-kubernetes

#15564 SUS-5274 | install dba PHP extension
  composer.json
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/dev/k8s/Dockerfile-php
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15565 Remove docker/dev/k8s
  docker/dev/k8s/Dockerfile-nginx
  docker/dev/k8s/Dockerfile-php
  docker/dev/k8s/README.md
  docker/dev/k8s/nginx.conf
  docker/dev/k8s/poz-dev.yaml
  docker/dev/k8s/site.conf
  docker/dev/k8s/sjc-dev.yaml
Labels: sus, sus-kubernetes

#15567 SUS-5277 Fix rewrites to extensions/resources/skins
  docker/dev/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#15570 🐖 | Remove JSMessages debug calls
  extensions/wikia/JSMessages/JSMessages.class.php
Labels: sus, sus-kubernetes

#15572 SUS-5282 | PHP binary location differ between distros, assume it's available in PATH
  docs/hooks.txt
  extensions/wikia/CreateNewWiki/tasks/ImportStarterData.php
  includes/GlobalFunctions.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-kubernetes

#15577 Remove not used /cache directory
  cache/.htaccess
Labels: sus

#15579 SUS-5284 | ignore hidden directories and files + node_modules
  docker/sandbox/.dockerignore
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15580 SUS-5287 | MWHttpRequest::proxySetup - do not use a localhost as a proxy for "local" URLs + use $wgHTTPProxy value only
  includes/HttpFunctions.php
Labels: sus, sus-kubernetes

#15584 SUS-5289 | Fix autofollowing threads when reply is posted
  extensions/wikia/Wall/builders/WallMessageBuilder.class.php
Labels: sus

#15583 SUS-5288 | Support language code in URL path
  docker/dev/site.conf
  docker/sandbox/site.conf
Labels: sus, sus-kubernetes

#15587 ER-19421 et al | Account for nulls in WikiaMobileHooks::onParserBeforeStrip
  extensions/wikia/WikiaMobile/WikiaMobileHooks.class.php
Labels: sus

#15591 SUS-5294 | docker/sandbox/.dockerignore - remove app/node_modules directory only, keep it in the subdirectories
  docker/sandbox/.dockerignore
Labels: sus, sus-kubernetes

#15590 Document console access to Kubernetes container
  docker/sandbox/README.md
Labels: sus, sus-kubernetes

#15593 SUS-5281 - MW in K8s add some domains to handle goreplay traffic
  docker/sandbox/sandbox-sus2.yaml
Labels: sus, sus-kubernetes

#15595 SUS-5384 | Handle PHP network errors during RabbitMQ publish
  includes/wikia/rabbitmq/ConnectionBase.class.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
Labels: sus, sus-kubernetes

#15598 SUS-5386 | WikiFactory::getLocalEnvURL does it now, no need to check a custom HTTP header
  extensions/wikia/PortableInfoboxBuilder/PortableInfoboxBuilderSpecialController.class.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
Labels: sus, sus-kubernetes

#15600 MAIN-16608 | avoid PHP Notice in SemanticDrilldown
  extensions/SemanticDrilldown/specials/SD_BrowseData.php
Labels: sus

#15603 SUS-5388 | install PHP intl extension
  composer.json
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/dev/docker-compose.yml
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15606 SUS-5391 | make Docker PHP base image a bit smaller
  docker/base/Dockerfile
  docker/dev/Dockerfile
  docker/sandbox/Dockerfile-php
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#15607 SUS-5184 - wgEnableHAWelcomeExt - fix logic
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: sus

#15610 SUS-5397 - mw in k8s - nginx logs should send numbers instead of strings
  docker/sandbox/nginx.conf
Labels: sus, sus-kubernetes

#15611 MW in k8s - add *.wikia.com to ingress sandbox template
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#15609 SUS-5393 | wVertical parameter is expected to be a numeric value
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/js/WikiBuilder.js
Labels: sus, sus-kubernetes
