Repository Wikia/app, pull requests merged in 2018-02, with the labels that each got.

#14726 SUS-3969 Remove unused cleanupNewWikis.php script
  maintenance/wikia/cleanupNewWikis.php
Labels: sus, sus-sunsets-2018

#14707 SUS-3942 Remove unused syncSwiftImagesBetweenDC.php script
  maintenance/wikia/syncSwiftImagesBetweenDC.php
Labels: sus, sus-sunsets-2018

#14708 SUS-3945 Remove unused removeRedundantUserNames.php script
  maintenance/wikia/removeRedundantUserNames.php
Labels: sus, sus-sunsets-2018

#14716 SUS-3954 Remove unused clearWikifactoryCache.php script
  maintenance/wikia/clearWikifactoryCache.php
Labels: sus, sus-sunsets-2018

#14725 SUS-3967 Remove unused ConfigureSmartBanner.php script
  extensions/wikia/WikiaMobile/maintenance/ConfigureSmartBanner.php
Labels: sus, sus-sunsets-2018

#14763 SUS-3268 | sunset PowerUser feature
  extensions/wikia/AnalyticsEngine/js/universal_analytics.js
  extensions/wikia/InsightsV2/InsightsHooks.class.php
  extensions/wikia/InsightsV2/InsightsV2.setup.php
  extensions/wikia/Listusers/SpecialListusers_helper.php
  extensions/wikia/Listusers/tests/ListUsersIntegrationTest.php
  extensions/wikia/MercuryApi/MercuryApiController.class.php
  extensions/wikia/PowerUser/PowerUser.class.php
  extensions/wikia/PowerUser/PowerUser.hooks.php
  extensions/wikia/PowerUser/PowerUser.i18n.php
  extensions/wikia/PowerUser/PowerUser.setup.php
  extensions/wikia/PowerUser/maintenance/PowerUserAddFrequentMaintenance.php
  extensions/wikia/PowerUser/maintenance/PowerUserPopulatePropertiesMaintenance.php
  extensions/wikia/Qualaroo/scripts/Qualaroo.js
  extensions/wikia/SiteWideMessages/SpecialSiteWideMessages.i18n.php
  extensions/wikia/SiteWideMessages/SpecialSiteWideMessages_body.php
  extensions/wikia/SiteWideMessages/templates/editor.tmpl.php
  extensions/wikia/Track/Track.php
  includes/User.php
  includes/wikia/DefaultSettings.php
  includes/wikia/api/UserApiController.class.php
  includes/wikia/services/UserService.class.php
  includes/wikia/tasks/Tasks/SiteWideMessagesTask.class.php
  includes/wikia/traits/PowerUserTrait.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php
Labels: sus, sus-sunsets-2018

#14767 SUS-4005 | Wikia's external user is gone, no need to keep the core support for it
  includes/AutoLoader.php
  includes/DefaultSettings.php
  includes/ExternalUser.php
  includes/extauth/Hardcoded.php
  includes/extauth/vB.php
  includes/installer/MysqlUpdater.php
  maintenance/archives/patch-eu_local_id.sql
  maintenance/archives/patch-external_user.sql
  maintenance/tables.sql
Labels: ExternalUser farewell party, sus, sus-sunsets-2018

#14757 SUS-3982 Remove unused purgeImages.php script
  maintenance/wikia/purgeImages.php
Labels: sus, sus-sunsets-2018

#14720 SUS-3957 Remove unused email.php script
  maintenance/wikia/email.php
Labels: sus, sus-sunsets-2018

#14777 SUS-4165 | remove wgUseVideoVerticalFilters handling
  extensions/wikia/VideoHandlers/VideoHandlers.setup.php
  extensions/wikia/VideoHandlers/videoInfo/VideoInfoHooksHelper.class.php
  includes/wikia/services/MediaQueryService.class.php
Labels: sus, sus-sunsets-2018

#14770 SUS-4084: Optimize Forum Activity module query
  extensions/wikia/Forum/CachedForumActivityService.php
  extensions/wikia/Forum/DatabaseForumActivityService.php
  extensions/wikia/Forum/Forum.setup.php
  extensions/wikia/Forum/ForumActivityService.php
  extensions/wikia/Forum/ForumController.class.php
  extensions/wikia/Forum/ForumHooksHelper.class.php
  extensions/wikia/Forum/templates/Forum_forumActivityModule.php
  extensions/wikia/Forum/tests/CachedForumActivityServiceTest.php
  extensions/wikia/Forum/tests/DatabaseForumActivityServiceIntegrationTest.php
  extensions/wikia/Forum/tests/fixtures/comments_index.sql
  extensions/wikia/Forum/tests/fixtures/recently_updated_threads.yaml
  extensions/wikia/Wall/WallHistory.class.php
  includes/wikia/tests/core/WikiaDatabaseTest.php
Labels: sus

#14782 SUS-3279 | SunsetProvider - fallback to image table, video_info is out of sync on mediawiki119.wikia.com
  maintenance/wikia/VideoHandlers/SunsetProvider.php
Labels: sus

#14759 SUS-3920 Remove unused reindex-wiki.php script
  extensions/wikia/Search/maintenance/reindex-wiki.php
Labels: sus, sus-sunsets-2018

#14755 SUS-3985 Remove unused checktbl.php script
  maintenance/wikia/utf8/checktbl.php
Labels: sus, sus-sunsets-2018

#14715 SUS-3953 Remove unused utf8/check.php script
  maintenance/wikia/utf8/check.php
Labels: sus, sus-sunsets-2018

#14756 SUS-3974 Remove unused utils.php script
  maintenance/wikia/utf8/utils.php
Labels: sus, sus-sunsets-2018

#14754 SUS-3987 Remove unused createUser.php script
  maintenance/wikia/createUser.php
Labels: sus, sus-sunsets-2018

#14753 SUS-3984 Remove unused AutoFollow.php script
  maintenance/wikia/cronjobs/AutoFollow.php
Labels: sus, sus-sunsets-2018

#14752 SUS-3983 Remove unused createNewWiki.php script
  maintenance/wikia/createNewWiki.php
Labels: sus, sus-sunsets-2018

#14751 SUS-3981 Remove unused moveMain.php script
  maintenance/wikia/moveMain.php
Labels: sus, sus-sunsets-2018

#14750 SUS-3922 Remove unused migrateAvatarsViaService.php script
  extensions/wikia/UserProfilePageV3/maintenance/migrateAvatarsViaService.php
Labels: sus, sus-sunsets-2018

#14749 SUS-3915 Remove unused setRevisionsBeforeDateAsReviewed.php script
  extensions/wikia/ContentReview/maintenance/setRevisionsBeforeDateAsReviewed.php
Labels: sus, sus-sunsets-2018

#14748 SUS-3914 Remove unused test-solrdocumentservice-performance.php script
  extensions/wikia/Search/maintenance/test-solrdocumentservice-performance.php
Labels: sus, sus-sunsets-2018

#14747 SUS-3913 Remove unused FixImageLinks.php script
  extensions/wikia/PortableInfobox/maintenance/FixImageLinks.php
Labels: sus, sus-sunsets-2018

#14745 SUS-3912 Remove unused setLastRevisionsAsReviewed.php script
  extensions/wikia/ContentReview/maintenance/setLastRevisionsAsReviewed.php
Labels: sus, sus-sunsets-2018

#14744 SUS-3911 Remove unused CleanupCommentsIndex.php script
  extensions/wikia/Wall/maintenance/CleanupCommentsIndex.php
Labels: sus, sus-sunsets-2018

#14743 SUS-3908 Remove unused moveScriptsToNamespace.php script
  extensions/wikia/ContentReview/maintenance/moveScriptsToNamespace.php
Labels: sus, sus-sunsets-2018

#14742 SUS-3906 Remove unused MigrateReqCloseDateToPermService.php script
  extensions/wikia/CloseMyAccount/maintenance/MigrateReqCloseDateToPermService.php
Labels: sus, sus-sunsets-2018

#14739 SUS-3980 Remove unused resendConfirmationEmail.php script
  maintenance/wikia/resendConfirmationEmail.php
Labels: sus, sus-sunsets-2018

#14737 SUS-3978 Remove unused RenameUserTaskManagerMaintenance.php script
  maintenance/wikia/RenameUserTaskManagerMaintenance.php
Labels: sus, sus-sunsets-2018

#14735 SUS-3977 Remove unused renameUser.php script
  maintenance/wikia/renameUser.php
Labels: sus, sus-sunsets-2018

#14730 SUS-3975 Remove unused updateIpblocksSchema.php script
  maintenance/wikia/updateIpblocksSchema.php
Labels: sus, sus-sunsets-2018

#14729 SUS-3972 Remove unused cleanPageWikiaProps.php script
  maintenance/wikia/cleanPageWikiaProps.php
Labels: sus, sus-sunsets-2018

#14727 SUS-3971 Remove unused purgeArticlePages.php script
  maintenance/wikia/purgeArticlePages.php
Labels: sus, sus-sunsets-2018

#14723 SUS-3961 Remove unused synchronizeBlobs.php script
  maintenance/wikia/synchronizeBlobs.php
Labels: sus, sus-sunsets-2018

#14722 SUS-3959 Remove unused asyncCache.php script
  maintenance/wikia/asyncCache.php
Labels: sus, sus-sunsets-2018

#14721 SUS-3958 Remove unused fixRedirects.php script
  maintenance/wikia/fixRedirects.php
Labels: sus, sus-sunsets-2018

#14719 SUS-3956 Remove unused utf8/blobtest.php script
  maintenance/wikia/utf8/blobtest.php
Labels: sus, sus-sunsets-2018

#14718 SUS-3955 Remove unused deleteArticlesByTitle.php script
  maintenance/wikia/deleteArticlesByTitle.php
Labels: sus, sus-sunsets-2018

#14714 SUS-3951 Remove unused imageServing.php script
  maintenance/wikia/imageServing.php
Labels: sus, sus-sunsets-2018

#14706 SUS-3940 Remove unused clear_tag_stats.php script
  maintenance/wikia/clear_tag_stats.php
Labels: sus, sus-sunsets-2018

#14704 SUS-3937 Remove unused move_blobs.php script
  maintenance/wikia/utf8/move_blobs.php
Labels: sus, sus-sunsets-2018

#14784 SUS-4074 | sunset extensions/wikia/VideosModule …
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/Chat2/ChatHooks.class.php
  extensions/wikia/VideosModule/Modules/VideosModuleBase.class.php
  extensions/wikia/VideosModule/Modules/VideosModuleCategory.class.php
  extensions/wikia/VideosModule/Modules/VideosModuleLocal.class.php
  extensions/wikia/VideosModule/Modules/VideosModuleRelated.class.php
  extensions/wikia/VideosModule/Modules/VideosModuleStaff.class.php
  extensions/wikia/VideosModule/Modules/VideosModuleVertical.class.php
  extensions/wikia/VideosModule/README.md
  extensions/wikia/VideosModule/VideosModule.i18n.php
  extensions/wikia/VideosModule/VideosModule.setup.php
  extensions/wikia/VideosModule/VideosModuleController.class.php
  extensions/wikia/VideosModule/VideosModuleHooks.class.php
  extensions/wikia/VideosModule/scripts/.gitignore
  extensions/wikia/VideosModule/scripts/Gruntfile.js
  extensions/wikia/VideosModule/scripts/README.md
  extensions/wikia/VideosModule/scripts/controllers/inContent.js
  extensions/wikia/VideosModule/scripts/controllers/rail.js
  extensions/wikia/VideosModule/scripts/models/videos.js
  extensions/wikia/VideosModule/scripts/package.json
  extensions/wikia/VideosModule/scripts/spec/models/videos.spec.js
  extensions/wikia/VideosModule/scripts/templates.mustache.js
  extensions/wikia/VideosModule/scripts/views/bottomModule.js
  extensions/wikia/VideosModule/scripts/views/index.js
  extensions/wikia/VideosModule/scripts/views/titleThumbnail.js
  extensions/wikia/VideosModule/styles/VideosModule.scss
  extensions/wikia/VideosModule/templates/VideosModule_index.mustache
  extensions/wikia/VideosModule/templates/bottomModule.mustache
  extensions/wikia/VideosModule/templates/inContent.mustache
  extensions/wikia/VideosModule/tests/VideosModuleTest.php
  skins/oasis/css/oasis.scss
  tests/karma/js-unit.conf.js
Labels: sus, sus-sunsets-2018

#14795 SUS-2152 | fix page URL parameter handling in Special:Vidoes and MediaQueryService
  extensions/wikia/SpecialVideos/SpecialVideosSpecialController.class.php
  includes/wikia/services/MediaQueryService.class.php
Labels: sus

#14800 Delete CommunityQuiz.php
  maintenance/wikia/CommunityQuiz.php
Labels: sus, sus-sunsets-2018

#14793 SUS-4170 | remove AsyncCache from MediaQueryService
  includes/wikia/AsyncCache.php
  includes/wikia/AsyncCacheTask.php
  includes/wikia/DefaultSettings.php
  includes/wikia/services/MediaQueryService.class.php
Labels: sus, sus-sunsets-2018

#14799 SUS-2370 | remove <wikiadoption-pref-label> from Special:Preferences
  extensions/wikia/FounderEmails/FounderEmails.class.php
Labels: sus, sus-sunsets-2018

#14801 SUS-4174 | Remove AntiBot framework
  CODEOWNERS
  extensions/AntiBot/AntiBot.i18n.php
  extensions/AntiBot/AntiBot.php
  extensions/AntiBot/available/GenericFormEncoding.php
Labels: sus, sus-sunsets-2018

#14778 SUS-3896 | Remove ranking snapshot code from Achievements
  extensions/wikia/AchievementsII/AchRankedUser.class.php
  extensions/wikia/AchievementsII/Ach_setup.php
  extensions/wikia/AchievementsII/services/AchRankingService.class.php
  extensions/wikia/AchievementsII/specials/templates/SpecialLeaderboard.tmpl.php
  maintenance/wikia/achievements_takeRankingSnapshot.php
Labels: sus, sus-sunsets-2018

#14776 SUS-4114 | sunset IGN video provider
  extensions/wikia/VideoEmbedTool/VideoEmbedTool_body.php
  extensions/wikia/VideoHandlers/VideoHandlerHelper.class.php
  extensions/wikia/VideoHandlers/VideoHandlers.setup.php
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapperFactory.class.php
  extensions/wikia/VideoHandlers/apiwrappers/IgnApiWrapper.class.php
  extensions/wikia/VideoHandlers/handlers/IgnVideoHandler.class.php
  extensions/wikia/VideoHandlers/tests/ApiWrapperFactoryTest.php
Labels: sus, sus-sunsets-2018

#14802 SUS-4112 | do not call VideoEmbedToolController::getSuggestedVideos
  extensions/wikia/VideoEmbedTool/VideoEmbedToolController.class.php
  extensions/wikia/VideoEmbedTool/VideoEmbedToolSearchService.class.php
  extensions/wikia/VideoEmbedTool/js/VET.js
  extensions/wikia/VideoEmbedTool/tests/VideoEmbedToolSearchServiceTest.php
Labels: sus, sus-sunsets-2018

#14670 SUS-4004 | Remove unused skin assets
  skins/Uncyclopedia.php
  skins/common/fbconnect/blogpost.png
  skins/common/fbconnect/comment.png
  skins/common/fbconnect/edits.png
  skins/common/fbconnect/fbiconbig.png
  skins/common/fbconnect/following.png
  skins/common/fbconnect/image.png
  skins/common/fbconnect/rating.png
  skins/common/fbconnect/video.png
  skins/common/images/Wikia_black_large_rgb.png
  skins/common/wikia_ui/buttons.css
  skins/monobook/google_adsense_script.html
  skins/monobook/required.gif
  skins/monobook/trac.png
  skins/monobook/wiki-indexed.png
  skins/uncyclopedia/chronarionbutton.png
  skins/uncyclopedia/google_adsense_script.html
  skins/uncyclopedia/stillwaters-button.png
  skins/wikia/img/Hosted_by_wikicities.png
Labels: sus, sus-sunsets-2018

#14809 SUS-4177 | remove maintenance/wikia/imageServingIndexer.php
  extensions/wikia/ImageServing/imageServingHelper.class.php
  maintenance/wikia/imageServingIndexer.php
Labels: sus, sus-sunsets-2018

#14788 SUS-4171 | Drop per-wiki objectcache tables
  extensions/3rdparty/emailtag/clear_objectcache.php
  includes/AutoLoader.php
  includes/DefaultSettings.php
  includes/objectcache/SqlBagOStuff.php
  includes/wikia/WikiaUpdater.php
  maintenance/tables.sql
Labels: sus, sus-sunsets-2018

#14789 SUS-4172 | Delete Phalanx Stats entries when filter is deleted
  extensions/wikia/PhalanxII/PhalanxSpecial_setup.php
  extensions/wikia/PhalanxII/classes/Phalanx.class.php
  extensions/wikia/PhalanxII/tests/PhalanxIntegrationTest.php
  extensions/wikia/PhalanxII/tests/fixtures/phalanx.yaml
  extensions/wikia/PhalanxII/tests/fixtures/phalanx_tables.sql
Labels: sus, sus-sunsets-2018

#14813 SUS | Bump Rabbit client 🐰
  composer.lock
  lib/composer/composer/installed.json
  lib/composer/php-amqplib/php-amqplib/.gitmodules
  lib/composer/php-amqplib/php-amqplib/CHANGELOG.md
  lib/composer/php-amqplib/php-amqplib/CONTRIBUTING.md
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPLazyConnection.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPLazySocketConnection.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php
  lib/composer/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php
  lib/composer/php-amqplib/php-amqplib/README.md
  lib/composer/php-amqplib/php-amqplib/composer.json
Labels: sus

#14814 SUS-4183 | make environments great again
  extensions/wikia/AnalyticsEngine/AnalyticsProviderGoogleUA.php
  extensions/wikia/Recirculation/RecirculationHooks.class.php
  extensions/wikia/Track/Track.php
  includes/wikia/Wikia.php
  includes/wikia/resourceloader/ResourceLoaderHooks.class.php
  includes/wikia/tests/WikiaTest.php
  includes/wikia/tests/core/WikiaBaseTest.class.php
  lib/Wikia/src/Factory/ProviderFactory.php
  lib/Wikia/src/Service/Gateway/KubernetesUrlProvider.php
  lib/Wikia/tests/Service/Gateway/KubernetesUrlProviderTest.php
Labels: sus, sus-sunsets-2018

#14817 SUS-4185 | remove old Perl scripts from MediaWiki core
  maintenance/fetchInterwiki.pl
  maintenance/postgres/compare_schemas.pl
  maintenance/postgres/mediawiki_mysql2postgres.pl
Labels: sus, sus-sunsets-2018

#14780 SUS-3867 | Cleanup after old spotlights stuff
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/Oasis/Oasis.i18n.php
  extensions/wikia/Spotlights/Spotlights.setup.php
  extensions/wikia/Spotlights/SpotlightsController.class.php
  extensions/wikia/Spotlights/SpotlightsHelper.php
  extensions/wikia/Spotlights/SpotlightsHooks.class.php
  extensions/wikia/Spotlights/js/AdProviderOpenX.js
  extensions/wikia/Spotlights/js/LazyLoadAds.js
  extensions/wikia/Spotlights/templates/Spotlights_Index.php
  extensions/wikia/WDACReview/WDACReviewSpecialController.class.php
  extensions/wikia/WidgetFramework/Widgets/WidgetLeftNav/WidgetLeftNav.php
  includes/wikia/DefaultSettings.php
  skins/uncyclopedia/main.css
  skins/wikia/css/Monobook.css
Labels: sus, sus-sunsets-2018

#14803 SUS-3285 remove handling of custom video embed tags, except youtube
  extensions/wikia/YouTube/YouTube.php
Labels: sus-sunsets-2018

#14785 SUS-4169 | Cleanup the database after not used user groups
  includes/wikia/WikiaUpdater.php
  includes/wikia/tests/HideBlockerNameTest.php
  includes/wikia/tests/_fixtures/hide_blocker_name.yaml
  maintenance/wikia/removeUnusedGroups.php
Labels: sus, sus-sunsets-2018

#14822 SUS-4175 | OutputPage::redirect - make the source of the redirect more obvious
  includes/OutputPage.php
Labels: sus

#14824 SUS-3390 | VoteHelper - do not insert unique_id column and use an empty string for IP address
  extensions/wikia/Wall/VoteHelper.class.php
  includes/wikia/WikiaUpdater.php
  maintenance/archives/wikia/patch-create-page_vote.sql
  maintenance/archives/wikia/patch-index-page_vote.sql
  maintenance/archives/wikia/patch-page_vote_unique_vote.sql
Labels: sus

#14827 SUS-4251 | remove objectcache handling from update.php
  includes/installer/DatabaseUpdater.php
  includes/installer/MysqlUpdater.php
  maintenance/archives/patch-objectcache.sql
  maintenance/update.php
Labels: sus, sus-sunsets-2018

#14835 SUS-4252 | remove page_vote rows for no longer existing pages
  includes/wikia/WikiaUpdater.php
Labels: sus

#14836 SUS-4255 | use city_url to build URL in ApiService
  includes/wikia/services/ApiService.class.php
  includes/wikia/services/tests/ApiServiceTest.php
Labels: sus, sus-https

#14829 SUS-4253 | Stop rewriting per-wiki ResourceLoader URLs
  extensions/wikia/AdEngine/tests/AdEngine2ContextServiceTest.php
  includes/resourceloader/ResourceLoader.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Wikia.php
  includes/wikia/resourceloader/ResourceLoaderHooks.class.php
  includes/wikia/resourceloader/tests/ResourceLoaderHooksTest.php
  includes/wikia/tests/core/MockGlobalVariableTrait.php
  resources/mediawiki/mediawiki.js
Labels: sus, sus-https

#14769 SUS-3872 Remove 3rdparty/emailtag extension
  extensions/3rdparty/emailtag/CHANGES
  extensions/3rdparty/emailtag/COPYING
  extensions/3rdparty/emailtag/README
  extensions/3rdparty/emailtag/TODO
  extensions/3rdparty/emailtag/emailtag.php
  includes/wikia/Extensions.php
Labels: sus, sus-sunsets-2018

#14762 SUS-3884: Remove JavascriptAPI client
  extensions/wikia/JavascriptAPI/Mediawiki.js
  extensions/wikia/JavascriptAPI/style.css
  extensions/wikia/JavascriptAPI/test.html
  extensions/wikia/WikiAnswers/WikiAnswers.php
  extensions/wikia/WikiAnswers/modules/ext.wikiAnswers.css
  extensions/wikia/WikiAnswers/modules/ext.wikiAnswers.js
  extensions/wikia/WikiAnswers/templates/WikiAnswers_AnswerBox.php
  includes/wikia/Extensions.php
  skins/oasis/modules/templates/Body_Index.php
Labels: sus, sus-sunsets-2018

#14766 SUS-3868 Remove SpecialListIncludedFiles extension
  extensions/wikia/Development/SpecialListIncludedFiles/Special_ListIncludedFiles.i18n.php
  extensions/wikia/Development/SpecialListIncludedFiles/Special_ListIncludedFiles.php
  includes/wikia/Extensions.php
Labels: sus, sus-sunsets-2018

#14844 SUS-4198 | Respect wgScriptPath in CategoryExhibition JS
  extensions/wikia/CategoryExhibition/js/CategoryExhibition.js
Labels: sus, sus-https

#14845 SUS-4225 | Respect wgScriptPath in Polls JS
  extensions/wikia/AjaxPoll/js/AjaxPoll.js
Labels: sus, sus-https

#14846 SUS-4217 | Respect wgScriptPath in Wall JS
  extensions/wikia/Wall/js/MessageTopic.js
Labels: sus, sus-https

#14816 SUS | Optimize Search autoloader
  composer.json
  extensions/wikia/Search/WikiaSearch.setup.php
  extensions/wikia/Search/tests/BaseTest.php
  extensions/wikia/Search/tests/ConfigTest.php
  extensions/wikia/Search/tests/Controller/SearchApiControllerTest.php
  extensions/wikia/Search/tests/Controller/SearchControllerTest.php
  extensions/wikia/Search/tests/Field/FieldTest.php
  extensions/wikia/Search/tests/HooksTest.php
  extensions/wikia/Search/tests/IndexService/AbstractServiceTest.php
  extensions/wikia/Search/tests/IndexService/AbstractWikiServiceTest.php
  extensions/wikia/Search/tests/IndexService/CrossWikiCoreTest.php
  extensions/wikia/Search/tests/IndexService/DefaultContentTest.php
  extensions/wikia/Search/tests/IndexService/IndexServicesTest.php
  extensions/wikia/Search/tests/IndexerTest.php
  extensions/wikia/Search/tests/Language/LanguageServiceTest.php
  extensions/wikia/Search/tests/Match/MatchTest.php
  extensions/wikia/Search/tests/MediaWikiServiceTest.php
  extensions/wikia/Search/tests/Query/SelectTest.php
  extensions/wikia/Search/tests/QueryService/QueryServiceTest.php
  extensions/wikia/Search/tests/QueryService/Select/AbstractSelectTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/AbstractDismaxTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/CombinedMediaTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/InterWikiTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/OnWikiTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/VideoEmbedToolTest.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/VideoTitleTest.php
  extensions/wikia/Search/tests/QueryService/Select/Lucene/LuceneTest.php
  extensions/wikia/Search/tests/ResultSet/AbstractResultSetTest.php
  extensions/wikia/Search/tests/ResultSet/BaseTest.php
  extensions/wikia/Search/tests/ResultSet/DependenciesTest.php
  extensions/wikia/Search/tests/ResultSet/EmptySetTest.php
  extensions/wikia/Search/tests/ResultTest.php
  extensions/wikia/Search/tests/Services/BlacklistFilterTest.php
  extensions/wikia/Search/tests/Services/MovieEntitySearchServiceTest.php
  extensions/wikia/Search/tests/TestProfile/BaseTest.php
  extensions/wikia/Search/tests/UtilitiesTest.php
  extensions/wikia/Search/tests/WikiaSearchHelper.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Extensions.php
  includes/wikia/helpers/tests/CrossOriginResourceSharingHeaderHelperTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_namespaces.php
  lib/composer/composer/autoload_psr4.php
  lib/composer/composer/autoload_static.php
  tests/phpunit.xml
Labels: sus

#14849 Silence all notices & warnings from tests
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/MercuryApi/models/MercuryApi.class.php
  extensions/wikia/MercuryApi/tests/MercuryApiModelTest.php
  extensions/wikia/Search/tests/Services/MovieEntitySearchServiceTest.php
  extensions/wikia/ThemeDesigner/ThemeDesignerHelper.class.php
  extensions/wikia/ThemeDesigner/tests/ThemeSettingsTest.php
  extensions/wikia/VideoHandlers/apiwrappers/YoutubeApiWrapper.class.php
  extensions/wikia/WallNotifications/tests/WallNotificationsTest.php
  includes/wikia/nirvana/WikiaDispatcher.class.php
  includes/wikia/tests/GlobalFileTest.php
  includes/wikia/tests/WikiaDispatcherTest.php
  includes/wikia/tests/WikiaTest.php
  lib/Swagger/src/ApiClient.php
  lib/Swagger/src/ApiException.php
  lib/Swagger/src/Configuration.php
  lib/Swagger/src/ObjectSerializer.php
  lib/Swagger/src/User/Avatars/Api/UserAvatarsApi.php
  lib/Swagger/src/User/Avatars/Models/UserAvatarCreatedResult.php
  lib/Wikia/src/Service/User/Attributes/UserAttributes.php
  lib/Wikia/tests/Service/User/UserAttributesTest.php
  maintenance/wikia/tests/SunsetProviderTest.php
  tests/phpunit.xml
  tests/unit/includes/RecentChangeTest.php
Labels: sus

#14815 SUS | Optimize tasks autoloader
  includes/wikia/DefaultSettings.php
  includes/wikia/tasks/autoload.php
  lib/Wikia/src/Tasks/AsyncCeleryTask.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
  lib/Wikia/src/Tasks/Queues/ParsoidPurgePriorityQueue.php
  lib/Wikia/src/Tasks/Queues/ParsoidPurgeQueue.php
  lib/Wikia/src/Tasks/Queues/PriorityQueue.php
  lib/Wikia/src/Tasks/Queues/PurgeQueue.php
  lib/Wikia/src/Tasks/Queues/Queue.php
  lib/Wikia/src/Tasks/Queues/SMWQueue.php
  lib/Wikia/src/Tasks/TaskRunner.php
  lib/Wikia/src/Tasks/Tasks/BaseTask.php
  lib/Wikia/src/Tasks/Tasks/BatchRefreshLinksForTemplate.php
  lib/Wikia/src/Tasks/Tasks/BlockPurgeExpiredTask.php
  lib/Wikia/src/Tasks/Tasks/CreateNewWikiTask.php
  lib/Wikia/src/Tasks/Tasks/DismissCommunityMessageTask.php
  lib/Wikia/src/Tasks/Tasks/EdgeCachePurger.php
  lib/Wikia/src/Tasks/Tasks/GalleryCachePurgeTask.php
  lib/Wikia/src/Tasks/Tasks/HTMLCacheUpdateTask.php
  lib/Wikia/src/Tasks/Tasks/ImageReviewTask.php
  lib/Wikia/src/Tasks/Tasks/JobWrapperTask.php
  lib/Wikia/src/Tasks/Tasks/MathTask.php
  lib/Wikia/src/Tasks/Tasks/MultiLookupTask.php
  lib/Wikia/src/Tasks/Tasks/MultiTask.php
  lib/Wikia/src/Tasks/Tasks/ParsoidCacheUpdateTask.php
  lib/Wikia/src/Tasks/Tasks/RecentChangesUpdateTask.php
  lib/Wikia/src/Tasks/Tasks/RefreshCategoryCountsTask.php
  lib/Wikia/src/Tasks/Tasks/RefreshLinksForTitleTask.php
  lib/Wikia/src/Tasks/Tasks/RenameUserPagesTask.php
  lib/Wikia/src/Tasks/Tasks/SiteWideMessagesTask.php
  lib/Wikia/src/Tasks/Tasks/UpdateSpecialPagesTask.php
  lib/Wikia/src/Tasks/Tasks/UserRegistrationTask.php
  lib/Wikia/src/Tasks/Tasks/WatchlistUpdateTask.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  maintenance/wikia/task_runner.php
Labels: sus

#14811 SUS-4176 | remove wgAllowNonPremiumVideos handling
  extensions/VisualEditor/wikia/ApiAddMediaTemporary.php
  extensions/VisualEditor/wikia/VisualEditor.i18n.php
  extensions/VisualEditor/wikia/VisualEditor.php
  extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaMediaQueryWidget.js
  extensions/wikia/VideoEmbedTool/VideoEmbedTool_body.php
  extensions/wikia/VideoEmbedTool/WikiaVideoAdd_body.php
  extensions/wikia/VideoHandlers/VideoHandlers.i18n.php
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapper.class.php
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapperFactory.class.php
  extensions/wikia/YouTube/YouTube.php
  includes/wikia/services/VideoService.class.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
Labels: sus, sus-sunsets-2018

#14851 SUS-3850: introduce 'Content Volunteer' group
  extensions/GlobalMessages/GlobalMessagesG.i18n.php
  extensions/wikia/UserProfilePageV3/UserProfilePage.i18n.php
  extensions/wikia/UserProfilePageV3/UserTagsStrategy.class.php
  extensions/wikia/UserProfilePageV3/tests/UserTagsStrategyTest.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
Labels: sus

#14856 SUS-3390 | no need to explicitily insert an empty `ip` column value into page_vote table
  extensions/wikia/Wall/VoteHelper.class.php
  maintenance/archives/wikia/patch-create-page_vote.sql
Labels: sus

#14859 SUS | remove syntaxhighlight experiment
  extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.class.php
  extensions/wikia/SyntaxHighlight/SyntaxHighlight.setup.php
  extensions/wikia/SyntaxHighlight/SyntaxHighlightHooks.php
  extensions/wikia/SyntaxHighlight/modules/ext.syntaxHighlight.js
  extensions/wikia/SyntaxHighlight/modules/highlight/CHANGES.md
  extensions/wikia/SyntaxHighlight/modules/highlight/LICENSE
  extensions/wikia/SyntaxHighlight/modules/highlight/README.md
  extensions/wikia/SyntaxHighlight/modules/highlight/README.ru.md
  extensions/wikia/SyntaxHighlight/modules/highlight/highlight.pack.js
  extensions/wikia/SyntaxHighlight/modules/highlight/styles/solarized-dark.css
  extensions/wikia/SyntaxHighlight/modules/highlight/styles/solarized-light.css
  extensions/wikia/SyntaxHighlight/tests/SyntaxHighlightTest.php
  includes/wikia/Extensions.php
Labels: sus, sus-sunsets-2018

#14858 Revert "SUS-1514: Log parsing time for GeSHi syntax highlight"
  extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.class.php
Labels: sus, sus-sunsets-2018

#14862 WidgetTagCount - let's gather some statistics on <widget> tags used before we make sunset / support decision
  extensions/wikia/WidgetFramework/maintenance/widgetTagCount.php
Labels: sus

#14861 SUS-3561 | Fix some query pages not updating properly
  extensions/wikia/Blogs/Blogs.php
  extensions/wikia/Blogs/BlogsHelper.class.php
  extensions/wikia/Discussions/Discussions.setup.php
  extensions/wikia/Discussions/DiscussionsHooksHelper.php
  extensions/wikia/SharedHelp/SharedHelp.php
  includes/QueryPage.php
  includes/specials/SpecialFewestrevisions.php
  includes/specials/SpecialMostlinked.php
  includes/specials/SpecialUncategorizedimages.php
  includes/specials/SpecialUnusedcategories.php
  includes/specials/SpecialUnusedtemplates.php
  includes/specials/SpecialWantedpages.php
  tests/fixtures/wanted_pages.yaml
  tests/unit/includes/specials/WantedPagesIntegrationTest.php
Labels: sus

#14864 SUS | Remove ProfiledClassFactory from Search
  extensions/wikia/Search/classes/Config.php
  extensions/wikia/Search/classes/Field/Field.php
  extensions/wikia/Search/classes/ProfiledClassFactory.php
  extensions/wikia/Search/classes/QueryService/DependencyContainer.php
  extensions/wikia/Search/classes/QueryService/Factory.php
  extensions/wikia/Search/classes/Result.php
  extensions/wikia/Search/classes/ResultSet/DependencyContainer.php
  extensions/wikia/Search/classes/ResultSet/Factory.php
  extensions/wikia/Search/tests/ResultSet/DependenciesTest.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: sus, sus-sunsets-2018

#14866 Help page linked
  extensions/wikia/UserRenameTool/SpecialRenameuser.i18n.php
Labels: sus, user-rename-tool

#14771 SUS-4116 | Remove ghost rail from Wall/Forum diff and history pages
  extensions/wikia/Wall/Wall.i18n.php
  extensions/wikia/Wall/Wall.setup.php
  extensions/wikia/Wall/WallHistoryController.class.php
  extensions/wikia/Wall/WallRailController.class.php
  extensions/wikia/Wall/WallRailHelper.class.php
  extensions/wikia/Wall/css/WallHistoryRail.scss
  extensions/wikia/Wall/templates/WallRail_Index.php
  skins/oasis/modules/BodyController.class.php
Labels: sus, sus-sunsets-2018

#14867 SUS-4263 | fix a fatal on ProtectSite page
  extensions/wikia/SpecialProtectSite/SpecialProtectSite_body.php
Labels: sus

#14848 SUS-4238 | Respect wgScriptPath in staff tools' JS
  extensions/wikia/Listusers/js/table.js
  extensions/wikia/LookupContribs/templates/main-form.tmpl.php
  extensions/wikia/LookupContribs/templates/mode-form.tmpl.php
  extensions/wikia/LookupContribs/templates/user-activity.tmpl.php
  extensions/wikia/LookupUser/templates/contribution.table.tmpl.php
  extensions/wikia/SiteWideMessages/SpecialSiteWideMessages.js
  extensions/wikia/WhereIsExtension/templates/list.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/metrics-daily-form.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/metrics-main-form.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/metrics-monthly-form.tmpl.php
  extensions/wikia/WikiFactory/templates/form-tags-find.tmpl.php
  extensions/wikia/WikiFactory/templates/form-tags-mass.tmpl.php
  extensions/wikia/WikiFactory/templates/form.tmpl.php
  extensions/wikia/WikiFactory/templates/selector.tmpl.php
Labels: sus, sus-https

#14871 SUS-3390 | page_vote - allow NULL values in vote column
  maintenance/archives/wikia/patch-create-page_vote.sql
Labels: sus

#14873 SUS | Make Nirvana local URLs respect wgScriptPath
  includes/wikia/nirvana/WikiaDispatchableObject.class.php
Labels: sus, sus-https

#14882 SUS-4267 | we do need $wgUser global here
  extensions/wikia/WikiAnswers/templates/WikiAnswers_AnswerBox.php
Labels: sus

#14885 SUS-3390 | page_vote - article and user ID + timestamp is all we need now
  extensions/wikia/Wall/VoteHelper.class.php
Labels: sus

#14887 Bump PHPUnit 6.5.6 → 6.5.7
  composer.lock
  lib/composer/composer/installed.json
  lib/composer/phpunit/phpunit/.stickler.yml
  lib/composer/phpunit/phpunit/ChangeLog-6.5.md
  lib/composer/phpunit/phpunit/build.xml
  lib/composer/phpunit/phpunit/src/Runner/Version.php
  lib/composer/phpunit/phpunit/src/Util/Log/JUnit.php
Labels: sus

#14888 SUS-4233 | check if mobile search is still used
  extensions/wikia/Search/WikiaSearchController.class.php
Labels: sus, sus-https

#14900 SUS-4244 | ApiWrapper - all remaining video providers use JSON response format
  extensions/wikia/VideoHandlers/apiwrappers/ApiWrapper.class.php
Labels: sus, sus-sunsets-2018

#14901 SUS-4271 | remove simplepie/simplepie
  composer.json
  composer.lock
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_files.php
  lib/composer/composer/autoload_namespaces.php
  lib/composer/composer/autoload_psr4.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/include_paths.php
  lib/composer/composer/installed.json
  lib/composer/simplepie/simplepie/.travis.yml
  lib/composer/simplepie/simplepie/LICENSE.txt
  lib/composer/simplepie/simplepie/README.markdown
  lib/composer/simplepie/simplepie/autoloader.php
  lib/composer/simplepie/simplepie/composer.json
  lib/composer/simplepie/simplepie/db.sql
  lib/composer/simplepie/simplepie/idn/LICENCE
  lib/composer/simplepie/simplepie/idn/ReadMe.txt
  lib/composer/simplepie/simplepie/idn/idna_convert.class.php
  lib/composer/simplepie/simplepie/idn/npdata.ser
  lib/composer/simplepie/simplepie/library/SimplePie.php
  lib/composer/simplepie/simplepie/library/SimplePie/Author.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache/Base.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache/DB.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache/File.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache/Memcache.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache/Memcached.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache/MySQL.php
  lib/composer/simplepie/simplepie/library/SimplePie/Cache/Redis.php
  lib/composer/simplepie/simplepie/library/SimplePie/Caption.php
  lib/composer/simplepie/simplepie/library/SimplePie/Category.php
  lib/composer/simplepie/simplepie/library/SimplePie/Content/Type/Sniffer.php
  lib/composer/simplepie/simplepie/library/SimplePie/Copyright.php
  lib/composer/simplepie/simplepie/library/SimplePie/Core.php
  lib/composer/simplepie/simplepie/library/SimplePie/Credit.php
  lib/composer/simplepie/simplepie/library/SimplePie/Decode/HTML/Entities.php
  lib/composer/simplepie/simplepie/library/SimplePie/Enclosure.php
  lib/composer/simplepie/simplepie/library/SimplePie/Exception.php
  lib/composer/simplepie/simplepie/library/SimplePie/File.php
  lib/composer/simplepie/simplepie/library/SimplePie/HTTP/Parser.php
  lib/composer/simplepie/simplepie/library/SimplePie/IRI.php
  lib/composer/simplepie/simplepie/library/SimplePie/Item.php
  lib/composer/simplepie/simplepie/library/SimplePie/Locator.php
  lib/composer/simplepie/simplepie/library/SimplePie/Misc.php
  lib/composer/simplepie/simplepie/library/SimplePie/Net/IPv6.php
  lib/composer/simplepie/simplepie/library/SimplePie/Parse/Date.php
  lib/composer/simplepie/simplepie/library/SimplePie/Parser.php
  lib/composer/simplepie/simplepie/library/SimplePie/Rating.php
  lib/composer/simplepie/simplepie/library/SimplePie/Registry.php
  lib/composer/simplepie/simplepie/library/SimplePie/Restriction.php
  lib/composer/simplepie/simplepie/library/SimplePie/Sanitize.php
  lib/composer/simplepie/simplepie/library/SimplePie/Source.php
  lib/composer/simplepie/simplepie/library/SimplePie/XML/Declaration/Parser.php
  lib/composer/simplepie/simplepie/library/SimplePie/gzdecode.php
Labels: sus, sus-sunsets-2018

#14875 SUS-4254 | improve slave lag handling when changing WikiFactory variable value
  extensions/wikia/CuratedContent/CuratedContentController.class.php
  extensions/wikia/WikiFactory/WikiFactory.php
  includes/wikia/services/CommunityDataService.class.php
Labels: sus

#14897 DE-3343 Added created_at to pages
  extensions/wikia/Pages/UpdatePagesTask.php
  extensions/wikia/Pages/tests/fixtures/state_initial.yaml
  extensions/wikia/Pages/tests/fixtures/state_post_delete_page.yaml
  extensions/wikia/Pages/tests/fixtures/state_post_insert_page.yaml
  extensions/wikia/Pages/tests/fixtures/state_post_update_page.yaml
  includes/wikia/api/DWDimensionApiController.class.php
  includes/wikia/api/DWDimensionApiControllerSQL.class.php
  maintenance/wikia/updateDatawarePages.php
  tests/fixtures/dataware.sql
Labels: Don't merge

#14905 SUS-3390 | page_vote - vote column can go away
  maintenance/archives/wikia/patch-create-page_vote.sql
Labels: sus, sus-sunsets-2018

#14906 SUS-4274 | Remove SponsorshipDashboard
  extensions/wikia/GoogleAnalyticsSampling/GoogleAnalyticsSampling.i18n.php
  extensions/wikia/GoogleAnalyticsSampling/GoogleAnalyticsSampling.setup.php
  extensions/wikia/GoogleAnalyticsSampling/GoogleAnalyticsSamplingController.class.php
  extensions/wikia/SponsorshipDashboard/SDDateProvider.class.php
  extensions/wikia/SponsorshipDashboard/SDReport.class.php
  extensions/wikia/SponsorshipDashboard/SponsorshipDashboard.body.php
  extensions/wikia/SponsorshipDashboard/SponsorshipDashboard.i18n.php
  extensions/wikia/SponsorshipDashboard/SponsorshipDashboard.sql
  extensions/wikia/SponsorshipDashboard/SponsorshipDashboardAjax.class.php
  extensions/wikia/SponsorshipDashboard/SponsorshipDashboardService.class.php
  extensions/wikia/SponsorshipDashboard/SponsorshipDashboard_autoload.php
  extensions/wikia/SponsorshipDashboard/SponsorshipDashboard_setup.php
  extensions/wikia/SponsorshipDashboard/css/SponsorshipDashboard.scss
  extensions/wikia/SponsorshipDashboard/images/throbber.gif
  extensions/wikia/SponsorshipDashboard/js/SponsorshipDashboardChart.js
  extensions/wikia/SponsorshipDashboard/output/SDOutputCSV.class.php
  extensions/wikia/SponsorshipDashboard/output/SDOutputChart.class.php
  extensions/wikia/SponsorshipDashboard/output/SDOutputFormatter.class.php
  extensions/wikia/SponsorshipDashboard/output/SDOutputTable.class.php
  extensions/wikia/SponsorshipDashboard/sources/SDSource.class.php
  extensions/wikia/SponsorshipDashboard/sources/SDSourceDatabase.class.php
  extensions/wikia/SponsorshipDashboard/sources/SDSourceGapi.class.php
  extensions/wikia/SponsorshipDashboard/sources/SDSourceGapiCu.class.php
  extensions/wikia/SponsorshipDashboard/sources/SDSourceMobile.class.php
  extensions/wikia/SponsorshipDashboard/templates/output/chart.tmpl.php
  extensions/wikia/SponsorshipDashboard/templates/output/chart_empty.tmpl.php
  extensions/wikia/SponsorshipDashboard/templates/output/chart_info.tmpl.php
  extensions/wikia/SponsorshipDashboard/templates/output/csv.tmpl.php
  extensions/wikia/SponsorshipDashboard/templates/output/table.tmpl.php
  extensions/wikia/WikiFactory/Metrics/SpecialAWCMetrics.php
  extensions/wikia/WikiFactory/Metrics/SpecialNewWikisGraph.php
  extensions/wikia/WikiFactory/Metrics/SpecialNewWikisGraphSourceDatabase.class.php
  extensions/wikia/WikiFactory/Metrics/css/table.css
  extensions/wikia/WikiFactory/Metrics/images/ajax-loader-s.gif
  extensions/wikia/WikiFactory/Metrics/images/sort_asc.png
  extensions/wikia/WikiFactory/Metrics/images/sort_asc_disabled.png
  extensions/wikia/WikiFactory/Metrics/images/sort_both.png
  extensions/wikia/WikiFactory/Metrics/images/sort_desc.png
  extensions/wikia/WikiFactory/Metrics/images/sort_desc_disabled.png
  extensions/wikia/WikiFactory/Metrics/output/SpecialNewWikisGraphOutput.class.php
  extensions/wikia/WikiFactory/Metrics/templates/metrics-daily-form.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/metrics-main-form.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/metrics-menu.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/metrics-monthly-form.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/output/chart.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/output/chart_empty.tmpl.php
  extensions/wikia/WikiFactory/Metrics/templates/tabs.tmpl.php
  extensions/wikia/WikiFactory/SpecialWikiFactory.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_ajax.php
  includes/wikia/Extensions.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
  lib/vendor/gapi/gapi.class.php
  lib/vendor/gapi/readme.txt
Labels: sus, sus-sunsets-2018

#14830 SUS-3851 | Support for loading different wikis from the same domain based on the language code in the path
  LocalSettings.php
  extensions/wikia/CityList/tests/UpdateCityListTaskIntegrationTest.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  extensions/wikia/WikiFactory/tests/fixtures/wiki_factory_loader.yaml
  includes/Setup.php
  includes/wikia/GlobalFunctions.php
  includes/wikia/tests/core/MockGlobalVariableTrait.php
  includes/wikia/tests/core/WikiaDatabaseTest.php
  skins/oasis/modules/BlogListingController.class.php
  tests/Makefile
  tests/bootstrap.php
  tests/fixtures/wikicities.sql
  tests/run-test.php
Labels: sus, sus-https
