Repository Wikia/app, pull requests merged in 2018-05, with the labels that each got.

#15251 SUS-4746 | MathJax's SVG renderer always outputs black text
  extensions/Math/Math.php
  extensions/Math/modules/MathJax.css
Labels: sus

#15198 SUS-4605: Improve edit count caching
  includes/wikia/services/UserStatsService.class.php
Labels: sus

#15254 SUS-4749 | enable new memcache client on 1% of production requests
  includes/DefaultSettings.php
Labels: sus

#15250 SUS-926 | Pressing enter when choosing a name on Special:CreatePage/CreateBlogPage submits the (empty) page, not the dialog
  extensions/wikia/EditPageLayout/js/plugins/PageControls.js
Labels: sus

#15256 SUS-4752 | RenameUserProcess - allow to skip user notifications
  extensions/wikia/UserRenameTool/RenameUserProcess.class.php
Labels: sus, sus-gdpr

#15265 SUS-4749 | enable new memcache client on 25% of production requests
  includes/DefaultSettings.php
Labels: sus, sus-new-memcache-client

#15266 SUS-4757 - make MathRenderer::getRenderer always return an instance of MathRenderer
  extensions/Math/MathRenderer.php
Labels: sus

#15259 SUS-4734 | render the closed wiki page without a redirect
  extensions/wikia/SASS/SassUtil.php
  extensions/wikia/WikiFactory/Close/SpecialCloseWiki_body.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/Loader/closedWikiHandler.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  extensions/wikia/WikiFactory/tests/fixtures/wiki_factory_loader.yaml
  includes/OutputPage.php
  includes/wikia/DefaultSettings.php
Labels: sus

#15267 SUS-4749 | enable new memcache client on 25% of production requests [prod]
  includes/DefaultSettings.php
Labels: sus

#15269 SUS-4749 | enable new memcache client on 50% of production requests
  includes/DefaultSettings.php
Labels: sus, sus-new-memcache-client

#15270 SUS-4749 | enable new memcache client on 50% of production requests [prod]
  includes/DefaultSettings.php
Labels: sus, sus-new-memcache-client

#15271 SUS-4749 | enable new memcache client for ALL production requests
  includes/DefaultSettings.php
Labels: sus, sus-new-memcache-client

#15272 🐷-4760 | fix typo in 2011 memcached sessions code
  includes/cache/MemcachedSessions.php
Labels: sus, sus-new-memcache-client

#15277 SUS-4761 | cache not set WikiFactory variables in WikiFactory::loadVariableFromDB
  extensions/wikia/WikiFactory/WikiFactory.php
Labels: sus, sus-new-memcache-client

#15279 SUS-4758 | Fix Community Page performance problems
  extensions/wikia/CommunityPage/models/CommunityPageSpecialInsightsModel.class.php
  extensions/wikia/CommunityPage/models/CommunityPageSpecialUsersModel.class.php
  extensions/wikia/InsightsV2/helpers/InsightsConfig.php
  extensions/wikia/InsightsV2/services/InsightsService.class.php
Labels: sus

#15262 SUS-4071 | sunset extensions/wikia/CategoryPagination
  extensions/wikia/CategoryPagination/CategoryPagination.setup.php
  extensions/wikia/CategoryPagination/CategoryPaginationHooks.class.php
  extensions/wikia/CategoryPagination/CategoryPaginationPage.class.php
  extensions/wikia/CategoryPagination/CategoryPaginationViewer.class.php
  extensions/wikia/CategoryPagination/templates/category.tmpl.php
  includes/CategoryViewer.php
  includes/wikia/Extensions.php
Labels: sus-sunsets-2018

#15284 SUS-4763 | CloseWiki maintenance script - improve logging
  extensions/wikia/WikiFactory/Close/README.md
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus

#15285 SUS-4111 | Do not render maps for articleAsJson output
  composer.json
  composer.lock
  extensions/Maps/Maps.hooks.php
  extensions/Maps/includes/Maps_DisplayMapRenderer.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_real.php
  lib/composer/composer/installed.json
Labels: sus

#15281 SUS-4749 | enable a new memcache client consistently on 10% of wikis
  extensions/wikia/WikiFactory/WikiFactory.php
  includes/DefaultSettings.php
  includes/objectcache/MemcachedPeclBagOStuff.php
Labels: sus, sus-new-memcache-client

#15294 SUS-4775: noratelimit permission for global groups only
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesBeforeWikiFactory.php
Labels: sus

#15293 SUS-4773: Don't use REPLACE for updating edit counts
  includes/wikia/WikiaUpdater.php
  includes/wikia/services/UserStatsService.class.php
  includes/wikia/tests/UserStatsServiceIntegrationTest.php
  includes/wikia/tests/_fixtures/user_stats_service.yaml
  includes/wikia/tests/core/WikiaDatabaseTest.php
  maintenance/archives/wikia/patch-wikia-user-properties-pk.sql
  maintenance/wikia/wikia_user_properties.sql
  tests/unit/ServiceTest.php
Labels: sus

#15134 MixConf, Pt. 3
  LocalSettings.php
  extensions/DynamicPageList/DPLSetup.php
  extensions/Maps/Maps_Settings.php
  extensions/OpenGraphMeta/OpenGraphMeta.php
  extensions/wikia/Comteam/Comteam_setup.php
  extensions/wikia/ForumIndexProtector/ForumIndexProtector.php
  extensions/wikia/Search/tests/QueryService/Select/Dismax/OnWikiTest.php
  extensions/wikia/SpecialEmailTest/SpecialEmailTest.php
  includes/DefaultSettings.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Defines.php
  includes/wikia/Emergency.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
  includes/wikia/VariablesExpansions.php
  includes/wikia/tests/GlobalFileTest.php
  includes/wikia/tests/ReplaceImageServerTest.php
  lib/Wikia/src/Factory/HeliosFactory.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
Labels: Work in progress

#15305 SUS-4773 | tweak migration parameters
  includes/wikia/WikiaUpdater.php
  maintenance/archives/wikia/patch-wikia-user-properties-pk.sql
Labels: sus, 🐷​

#15302 SUS-4749 | enable a new memcache client consistently on 25% of wikis
  includes/wikia/DefaultSettings.php
Labels: sus, sus-new-memcache-client

#15306 SUS-4781 | WikiFactory tags tab should no longer be present in WikiFactory UI
  extensions/wikia/WikiFactory/SpecialWikiFactory.i18n.php
  extensions/wikia/WikiFactory/SpecialWikiFactory.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_ajax.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
  extensions/wikia/WikiFactory/Tags/WikiFactoryTagsQuery.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/templates/form-info.tmpl.php
  extensions/wikia/WikiFactory/templates/form-tags-find.tmpl.php
  extensions/wikia/WikiFactory/templates/form-tags-mass.tmpl.php
  extensions/wikia/WikiFactory/templates/form-tags.tmpl.php
  extensions/wikia/WikiFactory/templates/form.tmpl.php
  extensions/wikia/WikiFactory/templates/variable.tmpl.php
Labels: sus, sus-sunsets-2018

#15310 SUS-4283 | remove tags support from WhereIsExtension
  extensions/wikia/WhereIsExtension/SpecialWhereIsExtension_body.php
  extensions/wikia/WhereIsExtension/templates/list.tmpl.php
Labels: sus, sus-sunsets-2018

#15313 ER-19010 | Remove ancient debug
  includes/User.php
Labels: sus, 🐷​

#15315 SUS-4285 | do not set wgWikiFactoryTags global variable
  extensions/wikia/JSVariables/JSVariables.php
  extensions/wikia/Spotlights/js/AdProviderOpenX.js
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  includes/wikia/DefaultSettings.php
Labels: sus, sus-sunsets-2018

#15297 SUS-3203 | fix existing broken logic
  includes/wikia/DefaultSettings.php
  includes/wikia/services/UserCommandsService.class.php
  includes/wikia/services/tests/SpecialPageUserCommandTest.php
  includes/wikia/services/usercommands/SpecialPageUserCommand.php
  includes/wikia/services/usercommands/UserCommand.php
Labels: sus

#15317 remove CACHE_LIBMEMCACHED and duplicate CACHE_MEMCACHED entry
  includes/wikia/DefaultSettings.php
Labels: sus, sus-new-memcache-client

#15319 Merge pull request #15317 from Wikia/fixes-to-memcached-configuration
  includes/wikia/DefaultSettings.php
Labels: sus, sus-new-memcache-client

#15312 SUS-4765: check opt-out status for Qualaroo, GA, Comscore and Quantcast
  extensions/wikia/AnalyticsEngine/AnalyticsProviderComscore.php
  extensions/wikia/AnalyticsEngine/AnalyticsProviderGA_Urchin.php
  extensions/wikia/AnalyticsEngine/AnalyticsProviderQuantServe.php
  extensions/wikia/AnalyticsEngine/js/universal_analytics.js
  extensions/wikia/Qualaroo/scripts/Qualaroo.js
  resources/wikia/modules/spec/trackingOptOut.spec.js
  resources/wikia/modules/trackingOptOut.js
  tests/karma/js-unit.conf.js
Labels: sus, sus-gdpr, 🐷​

#15304 SUS-4479 | we no longer need to set WikiFactory tags for newly created wikis
  extensions/wikia/CreateNewWiki/CreateNewWiki_setup.php
  extensions/wikia/CreateNewWiki/tasks/SetTags.php
  extensions/wikia/CreateNewWiki/tasks/TaskRunner.php
Labels: sus, sus-sunsets-2018

#15321 🐷 | fix dev tasks
  maintenance/wikia/task_runner.php
Labels: 🐷​

#15324 SUS-4284 | HubService::getComscoreCategoryOverride - use wgComScoreTagOverride WikiFactory variable instead of legacy WikiFactory tags
  includes/wikia/services/HubService.class.php
Labels: sus, sus-sunsets-2018

#15325 SUS-4788 | get rid of no longer used WikiFactoryTags class
  extensions/wikia/WikiFactory/SpecialWikiFactory.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
  extensions/wikia/WikiFactory/Tags/WikiFactoryTags.php
  extensions/wikia/WikiFactory/WikiFactory.php
  includes/wikia/DefaultSettings.php
Labels: sus, sus-sunsets-2018

#15253 PLATFORM-3473: Fastly-SSL usage cleanup
  extensions/wikia/HTTPSOptIn/HTTPSOptInHooks.class.php
  extensions/wikia/MercuryApi/MercuryApiController.class.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
Labels: Don't merge

#15332 SUS-4790 / SUS-4791 | respect wgEnableHAWelcomeExt value coming from WikiFactory
  extensions/wikia/HAWelcome/tests/HAWelcomeTaskHookDispatcherTest.php
  extensions/wikia/HAWelcome/tests/HAWelcomeTaskTest.php
  includes/wikia/Extensions.php
Labels: sus

#15333 SUS-4766 | Remove user name component of article comment titles
  extensions/wikia/ArticleComments/classes/ArticleComment.class.php
  extensions/wikia/ArticleComments/tests/ArticleCommentTest.php
Labels: sus, sus-gdpr

#15340 SUS-4794 | disable removed user
  extensions/wikia/Privacy/UserDataRemover.php
  extensions/wikia/Privacy/tests/UserDataRemoverTest.php
Labels: sus, sus-gdpr

#15337 SUS-4766 | migrate comments / wall and forum entries titles to remove user name component
  extensions/wikia/ArticleComments/ArticleComments_setup.php
  extensions/wikia/ArticleComments/classes/ArticleComment.class.php
  extensions/wikia/ArticleComments/classes/ArticleCommentsTitle.class.php
  extensions/wikia/ArticleComments/maintenance/migrateUserNamesInTitles.php
  extensions/wikia/ArticleComments/tests/ArticleCommentTest.php
  extensions/wikia/ArticleComments/tests/ArticleCommentTitleTest.php
  extensions/wikia/ArticleComments/tests/fixtures/article_comment_title.yaml
Labels: sus, sus-gdpr

#15343 SUS-4293 | remove remainings of tags and findtags tab support in WikiFactory UI
  extensions/wikia/WikiFactory/SpecialWikiFactory.i18n.php
  extensions/wikia/WikiFactory/SpecialWikiFactory_body.php
Labels: sus, sus-sunsets-2018

#15346 SUS_4283 | remove city_tag and city_tag_map tables from DB tests fixtures
  tests/fixtures/wikicities.sql
Labels: sus, sus-sunsets-2018

#15352 SUS-4766 | trim page_title when migrating comments / wall and forum etries to fit in the database column
  extensions/wikia/ArticleComments/classes/ArticleCommentsTitle.class.php
  extensions/wikia/ArticleComments/tests/ArticleCommentTitleTest.php
  extensions/wikia/ArticleComments/tests/fixtures/article_comment_title.yaml
Labels: sus, sus-gdpr

#15342 SUS-4793 anonimize spoof record for removed user
  extensions/AntiSpoof/SpoofUser.php
  extensions/wikia/Privacy/README.md
  extensions/wikia/Privacy/UserDataRemover.php
  extensions/wikia/Privacy/tests/UserDataRemoverTest.php
  extensions/wikia/Privacy/tests/fixtures/pii_wikicities_data.yaml
  extensions/wikia/Privacy/tests/fixtures/spoofuser.sql
  maintenance/wikia/sql/wikicities-schema.sql
Labels: sus, sus-gdpr

#15290 SUS-4752 | remove user data process
  extensions/AbuseFilter/abusefilter.tables.sqlite.sql
  extensions/AntiSpoof/SpoofUser.php
  extensions/GlobalMessages/GlobalMessagesG.i18n.php
  extensions/wikia/Privacy/PermanentArticleDelete.php
  extensions/wikia/Privacy/PermanentFileDelete.php
  extensions/wikia/Privacy/Privacy.setup.php
  extensions/wikia/Privacy/README.md
  extensions/wikia/Privacy/RemoveUserDataController.php
  extensions/wikia/Privacy/RemoveUserDataOnWikiTask.php
  extensions/wikia/Privacy/SpecialRequestToBeForgottenInternalController.php
  extensions/wikia/Privacy/UserDataRemover.php
  extensions/wikia/Privacy/templates/SpecialRequestToBeForgottenInternal_index.php
  extensions/wikia/Privacy/tests/RemoveUserDataOnWikiTaskTest.php
  extensions/wikia/Privacy/tests/UserDataRemoverTest.php
  extensions/wikia/Privacy/tests/fixtures/check_user.sql
  extensions/wikia/Privacy/tests/fixtures/drop_test_tables.sql
  extensions/wikia/Privacy/tests/fixtures/page.sql
  extensions/wikia/Privacy/tests/fixtures/pii_data.yaml
  extensions/wikia/Privacy/tests/fixtures/pii_wikicities_data.yaml
  extensions/wikia/Privacy/tests/fixtures/spoofuser.sql
  extensions/wikia/Privacy/tests/fixtures/wikiastaff_log.sql
  includes/User.php
  includes/wikia/Extensions.php
  includes/wikia/WikiaUpdater.php
  lib/Wikia/src/Service/User/Permissions/PermissionsConfiguration.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
  lib/Wikia/src/Tasks/Queues/Queue.php
  lib/Wikia/src/Tasks/Tasks/BaseTask.php
  maintenance/archives/wikia/patch-image-add-user-index.sql
  maintenance/archives/wikia/patch-image-drop-usertext-index.sql
  maintenance/archives/wikia/patch-oldimage-add-user-index.sql
  maintenance/archives/wikia/patch-oldimage-drop-usertext-index.sql
  maintenance/tables.sql
  maintenance/wikia/sql/wikicities-schema.sql
Labels: sus, sus-gdpr

#15311 XW-4943 | Adding forget-account form to Special:Contact
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/SpecialContact2/SecMap.php
  extensions/wikia/SpecialContact2/SpecialContact.body.php
  extensions/wikia/SpecialContact2/SpecialContact.i18n.php
  extensions/wikia/SpecialContact2/SpecialContact.php
  extensions/wikia/SpecialContact2/SpecialContactCountryNames.php
  extensions/wikia/SpecialContact2/SpecialContactForgetAccount.js
  extensions/wikia/SpecialContact2/templates/forget-account.tmpl.php
Labels: Don't merge

#15371 SUS-4766 | make migrateUserNamesInTitles.php update watchlist table entries as well
  extensions/wikia/ArticleComments/maintenance/migrateUserNamesInTitles.php
Labels: sus, sus-gdpr

#15373 SUS-4808 | CookiePolicy extension out 🇪🇺
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/CookiePolicy/CookiePolicy.hooks.php
  extensions/wikia/CookiePolicy/CookiePolicy.i18n.php
  extensions/wikia/CookiePolicy/CookiePolicy.setup.php
  extensions/wikia/CookiePolicy/crowdin.conf
  extensions/wikia/CookiePolicy/scripts/cookiePolicy.js
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-gdpr, sus-sunsets-2018, 🐷​

#15381 SUS-4812 | check opt-in status in the internal tracker 🇪🇺
  extensions/wikia/CloseMyAccount/CloseMyAccountHelper.class.php
  extensions/wikia/FlowTracking/FlowTracking.hooks.php
  extensions/wikia/Track/Track.php
  extensions/wikia/Track/templates/track.mustache
  extensions/wikia/UserLogin/UserSignupSpecialController.class.php
  includes/wikia/ArticlesUsingMediaQuery.class.php
  skins/oasis/modules/OasisController.class.php
  skins/oasis/modules/templates/Oasis_Index.php
Labels: sus, sus-gdpr, 🐷​

#15385 🐷 | Missing column
  extensions/wikia/PhalanxII/classes/PhalanxStatsPager.class.php
Labels: sus

#15380 SUS-4811 | define a dependency of ext.wikia.TimeAgoMessaging
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/MyHome/renderers/FeedRenderer.php
  extensions/wikia/TimeAgoMessaging/TimeAgoMessaging_setup.php
  extensions/wikia/TimeAgoMessaging/js/timeago.init.js
  extensions/wikia/Wall/WallHooksHelper.class.php
  extensions/wikia/Wall/js/Wall.js
  extensions/wikia/Wall/js/WallWikiActivity.js
  resources/wikia/Resources.php
  resources/wikia/jquery.wikia.js
Labels: sus

#15288 PLATFORM-3442: include language wikis in robots.txt
  extensions/wikia/RobotsTxt/RobotsTxt.setup.php
  extensions/wikia/RobotsTxt/WikiaRobotsController.class.php
  extensions/wikia/RobotsTxt/classes/PathBuilder.class.php
  extensions/wikia/RobotsTxt/classes/RobotsTxt.class.php
  extensions/wikia/RobotsTxt/classes/WikiaRobots.class.php
  extensions/wikia/RobotsTxt/tests/PathBuilderTest.php
  extensions/wikia/RobotsTxt/tests/WikiaRobotsTest.php
  extensions/wikia/WikiFactory/WikiFactory.php
  includes/wikia/services/ApiService.class.php
Labels: Don't merge

#15382 SUS-4765 | Tracking settings button on Privacy Policy pages 🇪🇺
  extensions/wikia/TrackingOptIn/TrackingSettingsManager.i18n.php
  extensions/wikia/TrackingOptIn/TrackingSettingsManager.setup.php
  extensions/wikia/TrackingOptIn/TrackingSettingsManagerHooks.php
  extensions/wikia/TrackingOptIn/crowdin.conf
  extensions/wikia/TrackingOptIn/dist/tracking-opt-in.min.js
  extensions/wikia/TrackingOptIn/js/ext.wikia.trackingSettingsManager.js
  extensions/wikia/TrackingOptIn/js/trackingOptIn.js
  extensions/wikia/TrackingOptIn/src/index.js
  extensions/wikia/TrackingOptIn/styles/ext.wikia.trackingSettingsManager.css
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-gdpr

#15393 remove Java annotations from Nirvana 🐘
  extensions/wikia/Email/Controller/BlogPostController.class.php
  extensions/wikia/Email/Controller/CategoryAddController.class.php
  extensions/wikia/Email/Controller/CommentController.class.php
  extensions/wikia/Email/Controller/DiscussionController.class.php
  extensions/wikia/Email/Controller/EmailConfirmationController.class.php
  extensions/wikia/Email/Controller/ForgotPasswordController.class.php
  extensions/wikia/Email/Controller/ForumController.class.php
  extensions/wikia/Email/Controller/FounderController.class.php
  extensions/wikia/Email/Controller/FounderDigestController.class.php
  extensions/wikia/Email/Controller/GenericController.class.php
  extensions/wikia/Email/Controller/PasswordResetLinkController.class.php
  extensions/wikia/Email/Controller/UserNameChangeController.class.php
  extensions/wikia/Email/Controller/UserRightsChangedController.class.php
  extensions/wikia/Email/Controller/WallMessageController.class.php
  extensions/wikia/Email/Controller/WatchedPageController.class.php
  extensions/wikia/Email/Controller/WeeklyDigestController.class.php
  extensions/wikia/Email/Controller/WelcomeController.class.php
  extensions/wikia/Email/EmailController.class.php
  extensions/wikia/Email/README.md
  extensions/wikia/Email/SpecialSendEmailController.class.php
  extensions/wikia/FandomCreatorEmail/Controller/ContentUpdatedController.php
  extensions/wikia/UserActivity/SpecialUserActivityController.class.php
  includes/wikia/nirvana/WikiaView.class.php
Labels: sus, sus-sunsets-2018

#15368 SUS-4796 | disable access to Monobook
  extensions/wikia/SkinChooser/SkinChooser.class.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-gdpr, sus-monobook, sus-sunsets-2018

#15401 requesttobeforgotten: grant this right to request-to-be-forgotten-admin members only
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
Labels: sus, sus-gdpr

#12533 MAIN-9857: Making image placeholders use content language
  extensions/wikia/WikiaMiniUpload/WikiaMiniUpload_body.php
Labels: sus

#15394 SUS-4777 | rtbf audit log
  extensions/AntiSpoof/SpoofUser.php
  extensions/wikia/Privacy/Privacy.setup.php
  extensions/wikia/Privacy/RemovalAuditLog.php
  extensions/wikia/Privacy/RemoveUserDataController.php
  extensions/wikia/Privacy/RemoveUserDataOnWikiTask.php
  extensions/wikia/Privacy/SpecialRequestToBeForgottenInternalController.php
  extensions/wikia/Privacy/UserDataRemover.php
  extensions/wikia/Privacy/tests/RemoveUserDataOnWikiTaskTest.php
  extensions/wikia/Privacy/tests/UserDataRemoverTest.php
  extensions/wikia/Privacy/tests/fixtures/audit_log.sql
  maintenance/wikia/sql/specials-schema.sql
Labels: sus, sus-gdpr

#15413 SUS-4798 | remove old skin-related WikiFactory variables
  LocalSettings.php
  extensions/wikia/Answers/Answers.php
  extensions/wikia/Answers/AnswersClass.php
  extensions/wikia/SkinChooser/SkinChooser.class.php
  extensions/wikia/ThemeDesigner/ThemeSettings.class.php
  extensions/wikia/WikiaApi/WikiaApiQuerySiteinfo.php
  includes/Skin.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-monobook, sus-sunsets-2018

#15416 SUS-4822 | remove user's watchlist
  extensions/wikia/Privacy/RemoveUserDataOnWikiTask.php
  extensions/wikia/Privacy/tests/RemoveUserDataOnWikiTaskTest.php
  extensions/wikia/Privacy/tests/fixtures/pii_data.yaml
Labels: sus, sus-gdpr

#15418 SUS-4421 | Avoid timeouts in background tasks
  extensions/wikia/Tasks/proxy/proxy.php
Labels: sus

#15409 SUS-1886: Address CR/lint issues
  extensions/wikia/WikiaMiniUpload/WikiaMiniUpload_body.php
Labels: sus

#15299 PLATFORM-3431: use syslog integration to push lyric find logs to s3
  extensions/3rdparty/LyricWiki/LyricFind/LyricFindTrackingService.class.php
  lib/Wikia/src/Logger/S3AuditLogger.php
Labels: Don't merge

#15402 SUS-1393 | add error message when uploading images larger than wgMaxImageArea
  includes/wikia/Wikia.php
  skins/oasis/modules/UploadPhotosController.class.php
Labels: sus

#15419 SUS-1886 | Image placeholder edit summaries should use content language, not user language
  extensions/wikia/WikiaMiniUpload/WikiaMiniUpload_body.php
Labels: sus, sus-voldev

#15427 Sus 4625 listusers data
  extensions/wikia/Listusers/SpecialListusers_helper.php
Labels: sus

#15348 PLATFORM-3481: remove wgServer from WF database
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/WikiFactory.php
Labels: Don't merge

#15431 🐖 | don't fail delete when comment is broken 🔥
  extensions/wikia/Forum/ForumHooksHelper.class.php
  extensions/wikia/Wall/WallMessage.class.php
  extensions/wikia/Wall/index/CommentsIndex.class.php
  extensions/wikia/Wall/index/CommentsIndexEntryNotFoundException.php
  extensions/wikia/Wall/index/CommentsIndexHooks.class.php
Labels: sus

#15435 change unique constraint for rtbf antispoof
  maintenance/wikia/sql/wikicities-schema.sql
Labels: sus, sus-gdpr

#15437 throw exception during global data removal
  extensions/wikia/Privacy/UserDataRemover.php
Labels: sus, sus-gdpr

#15405 SUS-4820 | Break dependency between mobile-wiki and old WikiaMobile comments
  extensions/wikia/MercuryApi/MercuryApiController.class.php
  extensions/wikia/MercuryApi/models/MercuryApi.class.php
  extensions/wikia/MercuryApi/tests/MercuryApiControllerIntegrationTest.php
  extensions/wikia/MercuryApi/tests/fixtures/mercury_api_controller_integration.yaml
Labels: sus, sus-monobook, sus-sunsets-2018

#15438 SUS-4805 | Make wfWaitForSlaves aware of slaves in neighbouring datacenters
  includes/GlobalFunctions.php
  includes/db/DatabaseMysqlBase.php
  lib/Wikia/src/Consul/Client.php
  lib/Wikia/tests/Consul/ClientTest.php
Labels: active-active, sus

#15440 🐖 | DART values bulk importer
  maintenance/wikia/dartKeyValueImport.php
Labels: sus

#15399 SUS-4819 | Remove Monobook specific code from miscellaneous extensions
  extensions/wikia/AchievementsII/Ach_setup.php
  extensions/wikia/BannerNotifications/BannerNotifications.setup.php
  extensions/wikia/BannerNotifications/BannerNotificationsController.class.php
  extensions/wikia/BannerNotifications/js/BannerNotifications.js
  extensions/wikia/Chat2/ChatWidget.class.php
  extensions/wikia/Chat2/css/ChatWidget.scss
  extensions/wikia/Chat2/templates/widget.mustache
  extensions/wikia/Chat2/templates/widgetMonobook.mustache
  extensions/wikia/Chat2/tests/ChatWidgetTest.php
  extensions/wikia/CreatePage/CreatePage.php
  extensions/wikia/CreatePage/monobook/README.txt
  extensions/wikia/CreatePage/monobook/SpecialCreatePage.class.php
  extensions/wikia/CreatePage/monobook/SpecialEditPage.class.php
  extensions/wikia/CreatePage/monobook/templates/createFormHeader.tmpl.php
  extensions/wikia/CreatePage/monobook/templates/dialog.tmpl.php
  extensions/wikia/DataProvider/DataProvider.php
  extensions/wikia/DesignSystem/DesignSystemHooks.class.php
  extensions/wikia/EditPageLayout/EditPageLayout.i18n.php
  extensions/wikia/EditPageLayout/EditPageLayoutHooks.class.php
  extensions/wikia/FilePage/css/FilePageTabbed.scss
  extensions/wikia/Follow/Follow.i18n.php
  extensions/wikia/Follow/Follow.php
  extensions/wikia/Follow/FollowHelper.class.php
  extensions/wikia/Follow/templates/followedUserPage.tmpl.php
  extensions/wikia/JSSnippets/js/JSSnippets.js
  extensions/wikia/JWPlayerTag/scripts/jwplayertag.js
  extensions/wikia/PortableInfobox/PortableInfoboxHooks.class.php
  extensions/wikia/PortableInfobox/js/PortableInfoboxMonobook.js
  extensions/wikia/PortableInfobox/styles/PortableInfoboxMonobook.scss
  extensions/wikia/RTE/js/RTE.preferences.js
  extensions/wikia/SEOTweaks/SEOTweaksHooksHelper.class.php
  extensions/wikia/Search/WikiaSearchController.class.php
  extensions/wikia/Search/monobook/monobook.scss
  extensions/wikia/Search/templates/WikiaSearch_CrossWiki_index.php
  extensions/wikia/Search/templates/WikiaSearch_index.php
  extensions/wikia/SharedHelp/css/shared-help.scss
  extensions/wikia/SpecialVideos/SpecialVideosSpecialController.class.php
  extensions/wikia/SpecialVideos/scripts/SpecialVideos.js
  extensions/wikia/SpecialVideos/scripts/mobile/collections/video.js
  extensions/wikia/SpecialVideos/scripts/mobile/controller.js
  extensions/wikia/SpecialVideos/scripts/mobile/views/index.js
  extensions/wikia/SpecialVideos/styles/mobile.scss
  extensions/wikia/TOC/TOC.setup.php
  extensions/wikia/TOC/TOCHooksHelper.class.php
  extensions/wikia/Thumbnails/ThumbnailHelper.class.php
  extensions/wikia/Thumbnails/ThumbnailHooks.class.php
  extensions/wikia/Thumbnails/Thumbnails.setup.php
  extensions/wikia/UserPreferencesV2/UserPreferencesV2.class.php
  extensions/wikia/UserPreferencesV2/UserPreferencesV2.i18n.php
  extensions/wikia/UserProfilePageV3/UserProfilePage.setup.php
  extensions/wikia/UserProfilePageV3/UserProfilePageHooks.class.php
  extensions/wikia/UserProfilePageV3/css/UserprofileMonobook.css
  extensions/wikia/WikiaPhotoGallery/WikiaPhotoGallery.class.php
  extensions/wikia/WikiaPhotoGallery/css/mixins/_slideshow-nav.scss
  extensions/wikia/WikiaStyleGuide/css/Dropdown.scss
Labels: sus, sus-monobook, sus-sunsets-2018

#15398 SUS-4818 | Remove Monobook specific code from Article Comments
  extensions/wikia/ArticleComments/ArticleComments_setup.php
  extensions/wikia/ArticleComments/classes/ArticleComment.class.php
  extensions/wikia/ArticleComments/classes/ArticleCommentInit.class.php
  extensions/wikia/ArticleComments/classes/ArticleCommentList.class.php
  extensions/wikia/ArticleComments/css/ArticleComments.css
  extensions/wikia/ArticleComments/css/ArticleComments.wikiamobile.scss
  extensions/wikia/ArticleComments/js/ArticleComments.js
  extensions/wikia/ArticleComments/js/ArticleComments.wikiamobile.js
  extensions/wikia/ArticleComments/js/ArticleComments_init.wikiamobile.js
  extensions/wikia/ArticleComments/modules/ArticleCommentsController.class.php
  extensions/wikia/ArticleComments/modules/templates/ArticleCommentsController_WikiaMobileCommentsPage.php
  extensions/wikia/ArticleComments/modules/templates/ArticleCommentsController_WikiaMobileIndex.php
  extensions/wikia/ArticleComments/modules/templates/ArticleComments_WikiaMobileComment.php
  extensions/wikia/ArticleComments/modules/templates/ArticleComments_WikiaMobileCommentList.php
  extensions/wikia/ArticleComments/modules/templates/ArticleComments_WikiaMobileReply.php
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/Blogs/BlogListingController.class.php
  extensions/wikia/Blogs/BlogLockdown.php
  extensions/wikia/Blogs/BlogTemplate.php
  extensions/wikia/Blogs/Blogs.i18n.php
  extensions/wikia/Blogs/Blogs.php
  extensions/wikia/Blogs/monobook/README.txt
  extensions/wikia/Blogs/monobook/SpecialCreateBlogPage.php
  extensions/wikia/Blogs/monobook/templates/createBlogFormHeader.tmpl.php
  extensions/wikia/Blogs/templates/BlogListing_Index.php
  extensions/wikia/Blogs/templates/blog-article-page.tmpl.php
  extensions/wikia/Blogs/templates/blog-page-voting.tmpl.php
  extensions/wikia/Blogs/templates/blog-page.tmpl.php
  extensions/wikia/Blogs/templates/blog-post-page.tmpl.php
  extensions/wikia/Blogs/templates/comment-edit.tmpl.php
  extensions/wikia/Blogs/templates/comment-list.tmpl.php
  extensions/wikia/Blogs/templates/comment.tmpl.php
  extensions/wikia/Blogs/templates/rcheaderblock.tmpl.php
  extensions/wikia/Oasis/Oasis_setup.php
  includes/wikia/DefaultSettings.php
  includes/wikia/VariablesBase.php
Labels: sus, sus-monobook, sus-sunsets-2018

#15395 SUS-4816 | Remove Monobook specific code from Forum extension
  extensions/wikia/Forum/ForumController.class.php
  extensions/wikia/Forum/ForumSpecialController.class.php
  extensions/wikia/Forum/RelatedForumDiscussionController.class.php
  extensions/wikia/Forum/css/ForumTag.scss
  extensions/wikia/Forum/css/monobook/ForumBoardMonobook.scss
  extensions/wikia/Forum/css/monobook/ForumMonobook.scss
  extensions/wikia/Forum/css/monobook/ForumSpecialMonobook.scss
  extensions/wikia/Forum/css/monobook/ForumThreadMonobook.scss
  extensions/wikia/Forum/css/monobook/RelatedForumMonobook.scss
  extensions/wikia/Forum/templates/Forum_threadMessageButtons.php
Labels: sus, sus-monobook, sus-sunsets-2018

#15450 SUS-4805 | add a support for pt-heartbeat based slave lag detection
  includes/ExternalStoreDB.php
  includes/Wiki.php
  includes/api/ApiMain.php
  includes/api/ApiQuerySiteinfo.php
  includes/db/Database.php
  includes/db/DatabaseMysqlBase.php
  includes/db/LoadBalancer.php
  includes/db/LoadMonitor.php
  includes/wikia/GlobalFunctions.php
  includes/wikia/services/DataMartService.class.php
  includes/wikia/services/WAMService.class.php
  maintenance/getLagTimes.php
  maintenance/lag.php
  maintenance/storage/recompressTracked.php
Labels: active-active, mediawiki-backports, sus

#15397 SUS-4817 | Remove Monobook specific code from staff tools
  extensions/wikia/ContentReview/ContentReview.hooks.php
  extensions/wikia/ContentReview/ContentReview.i18n.php
  extensions/wikia/ContentReview/scripts/contentReviewModuleMonobook.run.js
  extensions/wikia/ContentReview/styles/ContentReviewMonobookEntrypoint.scss
  extensions/wikia/ProtectSiteJS/ProtectSiteJS.class.php
  extensions/wikia/ProtectSiteJS/tests/ProtectSiteJSTest.php
  extensions/wikia/QuickTools/modules/ext.createUserPage.js
  extensions/wikia/QuickTools/modules/ext.quickAdopt.js
  extensions/wikia/RecentChanges/RecentChangesController.class.php
  extensions/wikia/RecentChanges/css/monobook/RecentChangesMonobook.scss
  extensions/wikia/WikiFeatures/WikiFeatures.setup.php
  extensions/wikia/WikiFeatures/WikiFeaturesSpecialController.class.php
  extensions/wikia/WikiFeatures/WikiaLabsSpecialController.class.php
  extensions/wikia/WikiFeatures/templates/WikiFeaturesSpecial_notOasis.php
Labels: sus, sus-monobook, sus-sunsets-2018
