Repository Wikia/app, pull requests merged in 2018-11, with the labels that each got.

#16241 PLATFORM-3761 & PLATFORM-3762: robots and wikis index page on empty domains
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/LanguageWikisIndex/LanguageWikisIndex.i18n.php
  extensions/wikia/LanguageWikisIndex/LanguageWikisIndex.setup.php
  extensions/wikia/LanguageWikisIndex/LanguageWikisIndexController.class.php
  extensions/wikia/LanguageWikisIndex/LanguageWikisIndexHooks.class.php
  extensions/wikia/LanguageWikisIndex/styles/language-wikis-index.scss
  extensions/wikia/LanguageWikisIndex/templates/LanguageWikisIndexController_index.php
  extensions/wikia/RobotsTxt/RobotsTxt.setup.php
  extensions/wikia/RobotsTxt/WikiaRobotsHooks.class.php
  extensions/wikia/RobotsTxt/classes/WikiaRobots.class.php
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  extensions/wikia/WikiFactory/Loader/closedWikiHandler.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/tests/WikiFactoryLoaderIntegrationTest.php
  includes/WebRequest.php
  includes/wikia/Extensions.php
  includes/wikia/GlobalFunctions.php
  includes/wikia/VariablesBase.php
  includes/wikia/Wikia.php
  includes/wikia/services/ApiService.class.php
  includes/wikia/services/tests/ApiServiceTest.php
Labels: Don't merge, Work in progress

#16303 SUS-6076 | sunset stable environment
  extensions/wikia/RobotsTxt/tests/WikiaRobotsTest.php
  extensions/wikia/WikiFactory/WikiFactory.php
  extensions/wikia/WikiFactory/tests/WikiFactoryTest.php
  includes/wikia/Defines.php
  includes/wikia/Extensions.php
  includes/wikia/tests/core/WikiaBaseTest.class.php
Labels: sus, sus-sunsets-2018

#16205 SRE-112 | Remove unused memcache DELETEs
  extensions/wikia/HAWelcome/HAWelcome.i18n.php
  extensions/wikia/HAWelcome/HAWelcomeEdit.body.php
  extensions/wikia/WikiaApi/WikiaApiQuery.php
  includes/wikia/services/PageStatsService.class.php
  lib/Wikia/src/Tasks/Tasks/CreateNewWikiTask.php
Labels: SRE, active-active

#16312 SUS-6163 - report when was the last time a given maintenance script has been run successfully
  maintenance/Maintenance.php
  maintenance/doMaintenance.php
Labels: sus

#16321 SUS-6170 | SharedHelp - use MediaWiki HTTP client and get rid of no longer needed handling of shared help source wiki article redirects
  extensions/wikia/SharedHelp/SharedHelp.php
  extensions/wikia/WikiFactory/WikiFactory.php
Labels: sus

#16280 SRE-119 | Remove legacy ProtectSite extension
  extensions/wikia/ProtectSiteII/ProtectSite.i18n.php
  extensions/wikia/SpecialProtectSite/SpecialProtectSite.aliases.php
  extensions/wikia/SpecialProtectSite/SpecialProtectSite.i18n.php
  extensions/wikia/SpecialProtectSite/SpecialProtectSite.php
  extensions/wikia/SpecialProtectSite/SpecialProtectSite_body.php
  extensions/wikia/SpecialProtectSite/crowdin.conf
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesBeforeWikiFactory.php
Labels: SRE, active-active

#16329 SUS-6163 | add docker/prod/alerting.yaml and apply it in production Jenkins pipeline
  docker/prod/Jenkinsfile
  docker/prod/alerting.yaml
Labels: sus, sus-kubernetes

#16328 SUS-6077 | CloseWikiMaintenance - handle empty sub-buckets on DFS
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus

#16331 utilize more powerful docker nodes for builds
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/sandbox/Dockerfile-php.template
  docker/sandbox/Jenkinsfile
Labels: sus, sus-kubernetes

#16306 k8s release pipeline
  docker/base/Dockerfile-php
  docker/maintenance/cronjob-template.yaml
  docker/maintenance/examples/example-one-time-job.yaml
  docker/preview/Jenkinsfile
  docker/prod/Dockerfile-php
  docker/prod/Jenkinsfile
  docker/prod/prod.template.yaml
  docker/sandbox/Dockerfile-php.template
  docker/sandbox/Jenkinsfile
  docker/sandbox/sandbox.template.yaml
Labels: sus, sus-kubernetes

#16339 Allow for redeploying latest tag to preview
  docker/preview/Jenkinsfile
Labels: sus, sus-kubernetes

#16272 IW-1152 | "Just updated" for Community Feeds
  extensions/wikia/FeedsAndPosts/FeedsAndPosts.setup.php
  extensions/wikia/FeedsAndPosts/FeedsAndPostsController.class.php
  extensions/wikia/FeedsAndPosts/FeedsAndPostsHooks.class.php
  extensions/wikia/FeedsAndPosts/WikiRecentChangesAPIProxy.class.php
  extensions/wikia/MercuryApi/models/MercuryApi.class.php
  extensions/wikia/Recirculation/js/recirculation.js
  includes/wikia/VariablesBase.php
  includes/wikia/WikiaDataAccess.class.php
Labels: Don't merge

#16342 SUS-6077 | DumpsOnDemand: store task_id in the database
  extensions/wikia/WikiFactory/Dumps/DumpsOnDemand.php
  maintenance/wikia/sql/wikicities-schema.sql
Labels: sus

#16349 SUS-5787 | fixes for prod build pipeline
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#16347 SUS-6166: PHP session handling broken on Kubernetes
  includes/Wiki.php
Labels: sus, sus-kubernetes

#16351 SUS-6189 | /opensearch_desc.php not handled by Kubernetes on wikis with language path
  docker/base/base.inc
Labels: sus, sus-kubernetes

#16357 SUS-6077 | refactor CloseWikiMaintenance to use Maintenance core-MediaWiki class
  .travis.yml
  docker/prod/alerting.yaml
  extensions/wikia/WikiFactory/Close/README.md
  extensions/wikia/WikiFactory/Close/maintenance.php
Labels: sus, sus-kubernetes

#16364 Send bit more info to slack on deploy to preview and prod
  docker/preview/Jenkinsfile
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#16365 SUS-6077 | alerting for DumpStarters cronjob
  docker/prod/alerting.yaml
Labels: sus, sus-kubernetes

#16366 SUS-6077 | properly setup env variables for cronjobs
  docker/maintenance/cronjob-template.yaml
Labels: sus, sus-kubernetes

#16383 get app and config tag from params
  docker/prod/Jenkinsfile
Labels: sus, sus-kubernetes

#16379 nginx | dev-specific image with prod/sandbox directory layout
  docker/README.md
  docker/base/Dockerfile-php
  docker/dev/Dockerfile-nginx
  docker/dev/docker-compose.yml
Labels: sus, sus-kubernetes

#16371 SUS-6262 | add Prometheus alerting for all maintenance scripts run as cron jobs
  docker/maintenance/init-stat.yaml
  docker/prod/alerting.yaml
  extensions/wikia/PhalanxII/maintenance/cleanupPhalanxStats.php
  extensions/wikia/WikiFactory/DeadWikis/maintenance.php
Labels: sus, sus-kubernetes

#16368 ADEN-7893 Adding Geo Edge Instant Global
  extensions/wikia/AdEngine/AdEngine2Hooks.class.php
  includes/wikia/DefaultSettings.php
Labels: Don't merge

#16378 SUS-6263 | internal requests inside k8s fix
  LocalSettings.php
  includes/HttpFunctions.php
  includes/wikia/GlobalFunctions.php
  includes/wikia/services/ApiService.class.php
  includes/wikia/tests/DomainUtilitiesTest.php
Labels: sus, sus-kubernetes

#16360 SRE-109: Disable automatic transactions for external DBs like blobs cluster
  includes/wikia/VariablesExpansions.php
Labels: SRE, active-active

#16358 SRE-109 | Use User::touch instead of User::invalidateCache where appropriate
  extensions/wikia/AchievementsII/services/AchAwardingService.class.php
  extensions/wikia/Blogs/BlogArticle.php
  includes/User.php
  includes/specials/SpecialEditWatchlist.php
Labels: SRE, active-active

#16361 SRE-109 | Make edit flow logic smarter
  includes/WikiPage.php
Labels: SRE, active-active

#16398 SUS-6267 | give mediawiki-prod some breathing space for heavy requests spikes
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16391 Don't proceed if no controller passed
  wikia.php
Labels: sus

#16397 SRE-109 | Use proper hook for theme settings update
  extensions/wikia/ThemeDesigner/ThemeDesignerHooks.class.php
  extensions/wikia/ThemeDesigner/ThemeDesigner_setup.php
Labels: SRE, active-active

#16399 Remove unused script
  docker/preview/Jenkinsfile
Labels: sus, sus-kubernetes

#16418 SUS-6267 | add monitoring around fpm workers usage
  docker/prod/alerting.yaml
Labels: sus, sus-kubernetes

#16363 SRE-109 | Prefer reading data from replicas rather than master during edit
  extensions/wikia/FounderEmails/events/FounderEmailsEditEvent.class.php
  includes/EmailNotification.php
  includes/LinksUpdate.php
  includes/Title.php
Labels: SRE, active-active

#16396 SRE-109 | Optimize PageStatsService
  extensions/wikia/ArticleComments/ArticleCommentsHooks.class.php
  extensions/wikia/PageHeader/ActionButton.class.php
  extensions/wikia/PageHeader/Subtitle.class.php
  includes/wikia/services/PageStatsService.class.php
  includes/wikia/services/tests/PageStatsServiceIntegrationTest.php
  skins/oasis/modules/BodyController.class.php
Labels: SRE, active-active

#16420 SRE-109 | Update cu_changes table in a background task
  extensions/CheckUser/CheckUser.hooks.php
  lib/Wikia/src/Tasks/Tasks/UpdateCheckUserTask.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: SRE, active-active

#16424 SUS-6267 | reduce CPU for mediawiki-prod k8s deployment
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16425 SUS-6267 | reduce CPU for mediawiki-prod k8s deployment even futher
  docker/prod/prod.template.yaml
Labels: sus, sus-kubernetes

#16404 SRE-109 | Add execution conditions for some expensive hooks
  extensions/wikia/ImageServing/imageServingHelper.class.php
  extensions/wikia/PortableInfobox/PortableInfoboxHooks.class.php
Labels: SRE, active-active
