Repository Wikia/app, pull requests merged in 2019-03, with the labels that each got.

#16752 CORE-110 | Edit draft
  extensions/wikia/EditDraftSaving/EditDraftSaving.i18n.php
Labels: Work in progress

#16740 CORE-123 | Edit buttons for personal CSS and JS pages should never point to VisualEditor
  extensions/wikia/EditorPreference/EditorPreference.class.php
  extensions/wikia/EditorPreference/tests/EditorPreferencesTest.php
  includes/wikia/VariablesBase.php
Labels: core-team

#16739 CORE-122 | Special:WantedPages 'exclude' option is broken, sends you to blank page
  includes/QueryPage.php
  includes/specials/SpecialWantedpages.php
Labels: core-team

#16737 CORE-114 | Drafts ignore pageid parameter for Special:CreateBlogPage
  extensions/wikia/EditDraftSaving/EditDraftSavingHooks.class.php
  extensions/wikia/EditDraftSaving/js/index.js
Labels: core-team

#16757 CORE-121 | CreateWiki is intermittently failing to properly create communities
  extensions/wikia/CreateNewWiki/CreateNewWikiController.class.php
  extensions/wikia/CreateNewWiki/CreateWikiTask.php
  extensions/wikia/CreateNewWiki/README.md
Labels: core-team

#16776 SECURITY: Make 'newbie' limit in $wgRateLimits really override 'user' limit
  includes/User.php
Labels: core-team, mediawiki-backports

#16788 CORE-95: SemanticMediaWiki performance fix backport
  extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php
Labels: core-team, smw-backports

#16793 CORE-95 | install SemanticMediaWiki via composer
  composer.json
  composer.lock
  extensions/SemanticMediaWiki/CONTRIBUTING.md
  extensions/SemanticMediaWiki/res/jquery/jquery.autocomplete.js
  extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobBase.php
  lib/composer/composer/ClassLoader.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
  lib/composer/composer/installed.json
Labels: core-team

#16792 CORE-95: performance fix backport [prod]
  extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php
Labels: core-team

#16784 CORE-117 | allow empty <span> elements in CKeditor's visual mode
  extensions/wikia/RTE/RTEReverseParser.class.php
  extensions/wikia/RTE/js/RTE.js
Labels: core-team

#16805 CORE-95 | SMWSQLStore3Readers - force an index on smw_object_ids
  extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php
Labels: core-team

#16807 CORE-95 | SMWSQLStore3Readers - force an index on smw_object_ids [prod]
  extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php
Labels: core-team

#16808 Revert "CORE-95 | SMWSQLStore3Readers - force an index on smw_object_ids"
  extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php
Labels: core-team

#16809 CORE-136 | Empty pages trigger conflicts after draft
  extensions/wikia/EditDraftSaving/js/index.js
Labels: core-team

#16795 CORE-128 | Qualtrics Site Intercept
  extensions/wikia/QualtricsSiteIntercept/QualtricsSiteIntercept.setup.php
  extensions/wikia/QualtricsSiteIntercept/QualtricsSiteInterceptHooks.class.php
  extensions/wikia/QualtricsSiteIntercept/scripts/index.js
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
Labels: core-team

#16838 CORE-175 | Move deferred insert tasks to a dedicated RabbitMQ queue
  extensions/CheckUser/CheckUser.hooks.php
  extensions/wikia/CityList/CityList.setup.php
  extensions/wikia/CoppaTool/CoppaToolController.class.php
  extensions/wikia/Listusers/SpecialListusers_hooks.php
  extensions/wikia/Pages/PagesHooks.php
  extensions/wikia/Parsoid/Parsoid.hooks.php
  extensions/wikia/SpecialMultipleLookup/MultiLookupHooks.php
  includes/User.php
  lib/Wikia/src/Tasks/AsyncTaskList.php
  lib/Wikia/src/Tasks/Queues/DeferredInsertsQueue.php
  lib/Wikia/src/Tasks/Tasks/BaseTask.php
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: core-team

#16817 Revert "CORE-108 | A/B test right rail"
  skins/oasis/js/LatestActivity.js
Labels: core-team

#16834 (PLATFORM-3949) Add a wikia.org tracking reset button
  extensions/wikia/TrackingOptIn/ResetTrackingPreferences.setup.php
  extensions/wikia/TrackingOptIn/ResetTrackingPreferencesSpecialController.class.php
  extensions/wikia/TrackingOptIn/TrackingSettingsManager.i18n.php
  extensions/wikia/TrackingOptIn/js/ext.wikia.resetTrackingSettingsManager.js
  extensions/wikia/WikiFactory/Loader/WikiFactoryLoader.php
  includes/resourceloader/ResourceLoaderStartUpModule.php
Labels: Don't merge

#16851 CORE-227 | ProtectSite needs to allow admins to edit
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesBeforeWikiFactory.php
Labels: core-team

#16850 PlacesParserHookHandler: tag pages with <place> tag using SemanticMediaWiki "Geo" property
  extensions/wikia/Places/PlacesParserHookHandler.class.php
Labels: core-team

#16823 Purge only fastly cache, PLATFORM-3973
  extensions/wikia/FilePage/FilePage.setup.php
  extensions/wikia/FilePage/FilePageHelper.class.php
  extensions/wikia/FilePage/FilePageHooks.class.php
  extensions/wikia/FilePage/WikiaFilePage.php
  extensions/wikia/Lightbox/Lightbox.setup.php
  extensions/wikia/Lightbox/LightboxController.class.php
  extensions/wikia/Lightbox/LightboxHelper.class.php
  extensions/wikia/Lightbox/LightboxHooks.class.php
  extensions/wikia/MercuryApi/MercuryApiController.class.php
  extensions/wikia/MercuryApi/handlers/MercuryApiFilePageHandler.class.php
  includes/wikia/DefaultSettings.php
  includes/wikia/Extensions.php
Labels: Don't merge

#16869 CORE-249 | Drafts: incorrectly applies section edit drafts to full editor
  extensions/wikia/EditDraftSaving/js/index.js
Labels: core-team
