Repository Wikia/app, pull requests merged in 2019-01, with the labels that each got.

#16517 DeleteArticlesByPrefix: report that no articles were found and leave the script, just please don't die
  maintenance/wikia/deleteArticlesByPrefix.php
Labels: sus

#16528 Revert "SUS-2974 | increase SQL queries logging sampling to 5%"
  includes/db/Database.php
Labels: core-team

#16369 (CAKE-4069) Update DS API links for N&S migration
  includes/wikia/models/DesignSystemGlobalFooterModel.class.php
  includes/wikia/models/DesignSystemGlobalNavigationModel.class.php
  includes/wikia/models/DesignSystemGlobalNavigationModelV2.class.php
  includes/wikia/models/DesignSystemSharedLinks.class.php
  includes/wikia/models/tests/DesignSystemGlobalFooterModelIntegrationTest.php
  includes/wikia/models/tests/fixtures/design_system_global_footer.yaml
Labels: Don't merge

#16471 PLATFORM-3881 | Redlink behaviour is broken on in classic editor previews
  extensions/wikia/SEOTweaks/scripts/uncrawlable-urls.js
Labels: stale

#16579 IW-1471 | Cleanup after getting rid of liftigniter recirculation
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/Recirculation/RecirculationHooks.class.php
  includes/wikia/DefaultSettings.php
  includes/wikia/services/LiftigniterMetadataService.class.php
  lib/Swagger/src/Liftigniter/Metadata/Api/GeosApi.php
  lib/Swagger/src/Liftigniter/Metadata/Api/ItemsApi.php
  lib/Swagger/src/Liftigniter/Metadata/Api/ItemsInternalApi.php
  lib/Swagger/src/Liftigniter/Metadata/Models/Geo.php
  lib/Swagger/src/Liftigniter/Metadata/Models/Item.php
  lib/Swagger/src/Liftigniter/Metadata/Models/ItemDto.php
  lib/Swagger/src/Liftigniter/Metadata/settings.json
  lib/composer/composer/autoload_classmap.php
  lib/composer/composer/autoload_static.php
Labels: Don't merge, Work in progress

#16600 IW-1231 | Unmute and autoplay FV on tab switch
  skins/oasis/js/jwplayer/node_modules/jwplayer-fandom/dist/index.css
  skins/oasis/js/jwplayer/node_modules/jwplayer-fandom/dist/wikiajwplayer.js
  skins/oasis/js/jwplayer/node_modules/jwplayer-fandom/package.json
  skins/oasis/js/jwplayer/node_modules/jwplayer-fandom/src/tab-active.js
  skins/oasis/js/jwplayer/package-lock.json
  skins/oasis/js/jwplayer/package.json
Labels: Don't merge
