Repository Wikia/app, pull requests merged in 2019-04, with the labels that each got.

#16895 Imstall opcache_stats.php for both Apache and k8s
  docker/base/base.inc
  opcache_stats.php
Labels: core-team

#16905 CORE-241 | Enable Draft Saving on all communities [prod]
  includes/wikia/VariablesBase.php
Labels: core-team

#16904 CORE-241 | Enable Draft Saving on all communities
  includes/wikia/VariablesBase.php
Labels: core-team

#16910 More workers for mediawiki on k8s
  docker/README.md
  docker/base/Dockerfile
  docker/base/Dockerfile-php
  docker/base/php-fpm.conf
  docker/base/php.ini
  docker/dev/Dockerfile
  docker/prod/Jenkinsfile
  docker/prod/prod.template.yaml
  docker/sandbox/Dockerfile-debug
Labels: core-team

#16925 More pods for mediawiki-prod
  docker/prod/Jenkinsfile
Labels: core-team

#16879 IW-1814 | Introduce preference to disable featured video
  extensions/wikia/AdEngine/AdEngine2ContextService.class.php
  extensions/wikia/AdEngine3/AdEngine3.class.php
  extensions/wikia/ArticleVideo/ArticleVideo.hooks.php
  extensions/wikia/ArticleVideo/ArticleVideo.i18n.php
  extensions/wikia/ArticleVideo/ArticleVideo.setup.php
  extensions/wikia/ArticleVideo/ArticleVideoContext.class.php
  extensions/wikia/ArticleVideo/tests/ArticleVideoContextTest.php
  extensions/wikia/AssetsManager/config.php
  extensions/wikia/SiteWideMessages/SiteWideMessagesController.class.php
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesBeforeWikiFactory.php
  skins/oasis/modules/NotificationsController.class.php
Labels: Don't merge

#16957 CORE-403 | Allow API requests to handle forceprofile=1 and showprofile=1
  includes/profiler/output/ProfilerOutputText.php
Labels: core-team, sus-kubernetes

#16962 CORE-406 | Disable Draft Saving
  includes/wikia/VariablesBase.php
Labels: core-team
