Repository Wikia/app, pull requests merged in 2019-07, with the labels that each got.

#17230 DE-4421 | add pdo_pgsql to MediaWiki base Docker image
  docker/README.md
  docker/base/Dockerfile
  docker/base/Dockerfile-php
  docker/dev/Dockerfile
  docker/qa/Dockerfile-rebuild-test-mw
  docker/sandbox/Dockerfile-debug
Labels: data-eng

#17122 DE-4374 | Hydralytics extension copied and enabled
  CODEOWNERS
  extensions/wikia/Hydralytics/Hydralytics.alias.php
  extensions/wikia/Hydralytics/Hydralytics.i18n.php
  extensions/wikia/Hydralytics/Hydralytics.setup.php
  extensions/wikia/Hydralytics/LICENSE
  extensions/wikia/Hydralytics/README.md
  extensions/wikia/Hydralytics/classes/Information.php
  extensions/wikia/Hydralytics/classes/Redshift.class.php
  extensions/wikia/Hydralytics/crowdin.conf
  extensions/wikia/Hydralytics/css/hydralytics.scss
  extensions/wikia/Hydralytics/js/Chart.bundle.js
  extensions/wikia/Hydralytics/js/hydralytics.js
  extensions/wikia/Hydralytics/js/lodash.min.js
  extensions/wikia/Hydralytics/js/moment.js
  extensions/wikia/Hydralytics/specials/SpecialAnalytics.php
  extensions/wikia/Hydralytics/templates/TemplateAnalytics.php
  includes/wikia/Extensions.php
  includes/wikia/VariablesBase.php
  lib/Wikia/src/Service/User/Permissions/data/PermissionsDefinesAfterWikiFactory.php
Labels: data-eng

#17279 SER-3318 Use community search to display wiki in right rail
  extensions/wikia/Search/WikiaSearchController.class.php
  extensions/wikia/Search/classes/Config.php
  extensions/wikia/Search/classes/Result/ResultHelper.php
  extensions/wikia/Search/classes/UnifiedSearch/UnifiedSearchService.php
  extensions/wikia/Search/classes/UnifiedSearch/UnifiedSearchWikiMatch.php
Labels: Don't merge

#17292 SpecialAnalytics: use $wgLang to differ the cache based on user language
  extensions/wikia/Hydralytics/specials/SpecialAnalytics.php
Labels: data-eng

#17300 IW-2182: filter sponsored content by vertical
  extensions/wikia/Recirculation/js/helpers/sponsoredContent.js
  extensions/wikia/Recirculation/js/spec/sponsoredContent.spec.js
Labels: Don't merge

#17310 Release 902 SER-3347 hotfix
  extensions/wikia/Privacy/RemoveUserDataController.php
  extensions/wikia/Privacy/RemoveUserDataOnWikiTask.php
  extensions/wikia/Privacy/UserDataRemover.php
  extensions/wikia/Search/classes/IndexService/FullContent.php
Labels: Don't merge

#17288 POC: Lua module for fetching mediawiki slot information
  docker/devbox/Dockerfile-nginx
  docker/devbox/README.md
  docker/devbox/docker-compose.yml
  docker/devbox/site.conf
  docker/devbox/slot_server.lua
  docker/devbox/spec/fake_http.lua
  docker/devbox/spec/slot_spec.lua
  extensions/wikia/SpecialVersion/WikiaSpecialVersionController.class.php
  extensions/wikia/SpecialVersion/templates/WikiaSpecialVersion_index.php
  includes/OutputPage.php
Labels: Don't merge

#16873 PLATFORM-4222 | upgrade to PHP 7.3.7 on dev
  .travis.yml
  composer.json
  composer.lock
  docker/README.md
  docker/base/Dockerfile
  docker/base/Dockerfile-php
  docker/base/php-fpm.conf
  docker/dev/Dockerfile
  docker/dev/Dockerfile-nginx
  docker/dev/docker-compose.yml
  docker/dev/phpdev.ini
  docker/dev/site.conf
  docker/dev/xdebug.ini
  docker/devbox/Dockerfile
  docker/devbox/Dockerfile-tests
  docker/devbox/composer/Dockerfile
  docker/devbox/docker-compose.yml
  docker/maintenance/examples/example-one-time-job.yaml
  docker/sandbox/Dockerfile-debug
  docker/servicesmw/servicesmw.template.yaml
  extensions/ParserFunctions/Expr.php
  extensions/wikia/Follow/FollowHelper.class.php
  extensions/wikia/PortableInfobox/services/Sanitizers/NodeSanitizer.php
  extensions/wikia/PortableInfobox/tests/PortableInfoboxMobileRenderServiceTest.php
  includes/GlobalFunctions.php
  includes/LocalisationCache.php
  includes/OutputPage.php
  includes/api/ApiQueryAllpages.php
  includes/api/ApiQueryCategoryMembers.php
  includes/json/FormatJson.php
  includes/media/XMP.php
  includes/media/XMPValidate.php
  includes/specials/SpecialVersion.php
  includes/upload/UploadStash.php
  includes/wikia/GlobalFunctions.php
  includes/wikia/helpers/CategoryHelper.class.php
  includes/wikia/parser/templatetypes/tests/ArticleHTMLCleanupTest.php
  includes/wikia/tests/core/WikiaBaseTest.class.php
  languages/LanguageConverter.php
  languages/classes/LanguageTr.php
  lib/Wikia/src/Logger/LoggerFactory.php
  lib/Wikia/tests/Logger/LoggerFactoryTest.php
  lib/composer/composer/installed.json
  lib/composer/wikia/simplehtmldom/CHANGELOG.md
  lib/composer/wikia/simplehtmldom/phpcompatibility.xml
  lib/composer/wikia/simplehtmldom/phpcs.xml
  lib/composer/wikia/simplehtmldom/simple_html_dom.php
  maintenance/storage/checkStorage.php
  skins/oasis/modules/templates/HotSpots_Index.php
Labels: core-team, mediawiki-backports, php7.3

#17324 SER-3334 Restore go search for unified search
  extensions/wikia/Search/WikiaSearchController.class.php
Labels: Don't merge

#17333 Introduce feedback, consistency with design proposal
  extensions/wikia/Hydralytics/Hydralytics.i18n.php
  extensions/wikia/Hydralytics/Hydralytics.setup.php
  extensions/wikia/Hydralytics/css/hydralytics.scss
  extensions/wikia/Hydralytics/js/hydralytics.js
  extensions/wikia/Hydralytics/specials/SpecialAnalytics.php
Labels: data-eng
