Repository Wikia/app, pull requests merged in 2020-06, with the labels that each got.

#17946 ADEN-10337 Fix typo error
  extensions/wikia/AdEngine3/src/slots.js
Labels: Patch change

#17948 ADEN-10311 Sync BFT with SafeFanTakeover
  extensions/wikia/AdEngine3/package-lock.json
  extensions/wikia/AdEngine3/package.json
  extensions/wikia/AdEngine3/src/setup.js
Labels: Minor change

#17962 ADEN-10332 Refactor EventService
  extensions/wikia/AdEngine3/package-lock.json
  extensions/wikia/AdEngine3/package.json
  extensions/wikia/AdEngine3/src/communication/communication-service.js
  extensions/wikia/AdEngine3/src/communication/of-type.js
  extensions/wikia/AdEngine3/src/platform-communication.js
  extensions/wikia/AdEngine3/src/slots.js
  extensions/wikia/AdEngine3/src/startup.js
Labels: Major change

#17989 ADEN-10329 Update PostQuecast
  extensions/wikia/AdEngine3/package-lock.json
  extensions/wikia/AdEngine3/package.json
  extensions/wikia/AdEngine3/src/communication/communication-service.js
  extensions/wikia/AdEngine3/src/communication/of-type.js
Labels: Minor change

#17969 SER-4038 CoppaTool redirects to ucp
  extensions/wikia/CoppaTool/CoppaToolSpecialController.class.php
Labels: Don't merge
