Repository Wikia/app, pull requests merged in 2020-09, with the labels that each got.

#18131 ADEN-10579 Bump TrackingOptIn version
  extensions/wikia/TrackingOptIn/dist/tracking-opt-in.min.js
  extensions/wikia/TrackingOptIn/package-lock.json
  extensions/wikia/TrackingOptIn/package.json
Labels: Patch change, dependencies

#18129 ADEN-10497 Adding affiliate_slot for IntentX contextual widget
  extensions/wikia/AdEngine3/AdEngine3.class.php
  extensions/wikia/AdEngine3/src/slots.js
  extensions/wikia/AdEngine3/src/startup.js
  extensions/wikia/AdEngine3/src/styles.scss
  extensions/wikia/AdEngine3/src/templates/big-fancy-ad-above-config.js
  extensions/wikia/AdEngine3/src/templates/roadblock-config.js
  extensions/wikia/AdEngine3/src/templates/sticky-tlb-config.js
  includes/wikia/DefaultSettings.php
Labels: Minor change, enhancement

#18141 DE-4807 | pv number counting
  extensions/wikia/Track/templates/tracking_cookies.mustache
Labels: Don't merge, Work in progress

#18128 cake-5934 | Add Fandom Store to Explore Dropdown
  extensions/wikia/CommunityHeader/Link.class.php
  extensions/wikia/CommunityHeader/Navigation.class.php
  extensions/wikia/CommunityHeader/templates/CommunityHeader_localNavigation.php
  includes/wikia/VariablesBase.php
  includes/wikia/models/DesignSystemCommunityHeaderModel.class.php
Labels: cake

#18150 cake-5810 | Remove set width
  extensions/wikia/UserProfilePageV3/css/UserProfilePage.scss
Labels: cake

#18153 cake-5934 | Add Fandom Store to Explore Dropdown
  extensions/wikia/CommunityHeader/Link.class.php
  extensions/wikia/CommunityHeader/Navigation.class.php
  extensions/wikia/CommunityHeader/templates/CommunityHeader_localNavigation.php
  includes/wikia/VariablesBase.php
  includes/wikia/api/DesignSystemApiController.class.php
  includes/wikia/models/DesignSystemCommunityHeaderModel.class.php
Labels: cake
