Repository Wikia/app, pull requests merged in 2020-08, with the labels that each got.

#17834 ADEN-9996 TCF v2.0 implementation
  extensions/wikia/AdEngine3/package-lock.json
  extensions/wikia/AdEngine3/package.json
  extensions/wikia/AdEngine3/src/setup.js
  extensions/wikia/TrackingOptIn/dist/tracking-opt-in.min.js
  extensions/wikia/TrackingOptIn/package-lock.json
  extensions/wikia/TrackingOptIn/package.json
Labels: dependencies

#18066 ADEN-10474 Expose ICBM sdk
  extensions/wikia/AdEngine3/package-lock.json
  extensions/wikia/AdEngine3/package.json
  extensions/wikia/AdEngine3/src/ad-context.js
  extensions/wikia/AdEngine3/src/setup.js
Labels: Minor change

#18089 ADEN-10262 Bump TrackingOptIn version
  extensions/wikia/AdEngine3/package-lock.json
  extensions/wikia/AdEngine3/package.json
  extensions/wikia/TrackingOptIn/dist/tracking-opt-in.min.js
  extensions/wikia/TrackingOptIn/package-lock.json
  extensions/wikia/TrackingOptIn/package.json
Labels: enhancement

#18074 ADEN-10456 Add MobileWiki Ads Platform
  extensions/wikia/AdEngine3/AdEngine3.class.php
  includes/wikia/DefaultSettings.php
Labels: Major change

#18121 ADEN-10540-2 Bump TrackingOptIn version
  extensions/wikia/TrackingOptIn/dist/tracking-opt-in.min.js
  extensions/wikia/TrackingOptIn/package-lock.json
  extensions/wikia/TrackingOptIn/package.json
Labels: Patch change, dependencies
